### ISSUE TITLE
[bug] could not login Nextcloud

### ISSUE THREAD

**Issue by J4gQBqqR** [MM2-0/Kvaesitso#10]
Stucked at "grant access" page.
I suspect the issue is the same with this one:
https://github.com/scubajeff/lespas/issues/34#issuecomment-988197013

**Comment by MM2-0** [comment]
It works for me (and I have 2FA enabled). Maybe there is something wrong with your Nextcloud server?

**Comment by J4gQBqqR** [comment]
Let me dig out my server log when I can access my PC. I will report back. Thank you!

**Comment by J4gQBqqR** [comment]
Just come across my mind, could it be my webview blocking it or non-standard API of my webview? I use bromite webview.

**Comment by MM2-0** [comment]
That's possible.

**Comment by J4gQBqqR** [comment]
I did not find any specific error in the /nextcloud/data/nextcloud.log file. 
I tried to switch my webview to other things, it still does not work.

As this issue cannot be reproduced with Nextcloud 22.2.3.0 by the developer, I am closing this issue.

**Comment by MM2-0** [comment]
I'm probably going to drop this Nextcloud integration soon anyway, in favor of Android's Storage Access Framework. This way all the authorization and networking stuff would go through the official Nextcloud app which would simplify things by a lot I think.

**Comment by CheariX** [comment]
Is there any progress on this?
Currently, nextcloud search does not work on recent version 1.26.4 with NC 27.
Usage of Android's Storage Access Framework sounds really promising!

**Comment by MM2-0** [comment]
> Currently, nextcloud search does not work on recent version 1.26.4 with NC 27.

Works fine for me?

> Usage of Android's Storage Access Framework sounds really promising!

It's not gonna happen. Only the Android OS can access DocumentProvider's search methods. The alternative would be recursively indexing the files yourself, but then you'd have to make sure that this update stays up to date, and that's just unfeasable.

**Comment by CheariX** [comment]
> Works fine for me?

OK, that's good to know. I need to figure out what's wrong on my side. (Btw. I'm using NC26 not 27, but this should not make the difference, i guess).
I've configured another owncloud. This one is working. Seems to be specific to NC.

> It's not gonna happen.
Too bad. Thank you for the information! I would also say that creating a custom index is not a good solution.
