### ISSUE TITLE
App shown multiple times while using tags

### ISSUE THREAD

**Issue by suitably** [MM2-0/Kvaesitso#1002]
When an app uses a tag, it's possible that it got found twice.
I.e. I have binary eye with the tag #barcode
If I search "bar", I find both. But if I search for "barc" I only find it once.

**Comment by MM2-0** [comment]
Are you using the latest version? I think this has been fixed in 1.32.1

**Comment by suitably** [comment]
Oh, I'm sorry. That's why I couldn't find any open issue regarding that. Nice work, I really appreciate it!
