### ISSUE TITLE
Quick actions: why can't the Google searches be disabled?

### ISSUE THREAD

**Issue by axelsimon** [MM2-0/Kvaesitso#1008]
The [quick actions documentation](https://kvaesitso.mm20.de/docs/user-guide/search/quickactions.html) explains how to add new searches (which is neat) but there doesn't seem to be an option to disable Google search, Google Play search and Youtube search. Could this be added?

I don't have Google Play and therefore will never use that search, it would be nicer for me to remove. Same for Google search, i'd rather not have it show up.

What is most confusing is that all the other built-in actions can be disabled.

Thanks!

**Comment by MM2-0** [comment]
There is a remove action in the overflow menu when you edit an action. I admit, it's a bit hard to find.

**Comment by axelsimon** [comment]
I reread your message 3 times and had a look and I just can't figure out what you are referring to :)

Also, i don't think this covers the issue i reported, which is that while all the built-in quick actions have a toggle to disable them, the Google ones don't. If only for consistency, it should be possible to disable all quick actions the same way.

Could you please reopen @MM2-0 ?

**Comment by MM2-0** [comment]
There is no toggle because unlike built-in actions, these prebuilt web search actions aren't in any way different from user created actions. Once you delete them, they are permanently gone.

![Screenshot_20240805-103204](https://github.com/user-attachments/assets/c6e48d7e-9a3c-4969-91dd-d036b5399df3)

**Comment by axelsimon** [comment]
I now understand, thanks!

I think it would then make sense to do the following to help users understand:
- put these actions in a separate section on the Quick Actions page, with a section title like "User-created actions"
- put a edit icon on the right, where the built-in Quick Actions have a toggle: three vertical dots, pen icon, whatever

Thanks!

**Comment by MM2-0** [comment]
> put these actions in a separate section on the Quick Actions page, with a section title like "User-created actions"

They are in one big list because you can customize the order via drag n drop (which isn't obvious either lol)

> put a edit icon on the right, where the built-in Quick Actions have a toggle: three vertical dots, pen icon, whatever

will do
