### ISSUE TITLE
Accessibility service is on but kvaesitso asks me to enable it

### ISSUE THREAD

**Issue by Lukalukito** [MM2-0/Kvaesitso#1013]
I'm on realme 6i. I use double tap gesture to open notification drawer but it needs accessibility service so i enable i, but still when using gesture it asks me to enable service which is already on. For some reason kvaesitso cant detect that it's enabled and that might be phone issue

**Comment by MM2-0** [comment]
https://kvaesitso.mm20.de/docs/user-guide/troubleshooting/granted-permissions.html
