### ISSUE TITLE
Hide Favourites

### ISSUE THREAD

**Issue by Henry-Hiles** [MM2-0/Kvaesitso#1015]
I use gestures for my favorite apps, and would love a simple way to hide thebwuole favourites panel. Thanks!
![Screenshot_20240803-224145_Kvaesitso_1](https://github.com/user-attachments/assets/6070e7a6-d557-489e-a463-79e980a55964)

**Comment by MM2-0** [comment]
Settings > search > favorites > turn off

**Comment by Henry-Hiles** [comment]
> Settings > search > favorites > turn off

Oh, thanks so much! Is this a new option? I haven't seen it before!

**Comment by MM2-0** [comment]
No, it's been there since pretty much the beginning 😄

**Comment by Henry-Hiles** [comment]
> No, it's been there since pretty much the beginning 😄

Huh, I must have just never seen it. Thanks so much!
