### ISSUE TITLE
Plugin doesn't show results 

### ISSUE THREAD

**Issue by drakegao** [MM2-0/Kvaesitso#1022]
Hi Team,

Thanks for developing the best launcher on the android so far. I found out that the plugin for searches, OneDrive, here plugin, open weather map as long as for places, nothing is shown. How do I search places? All the plugins are enabled and added the API key if needed. Thanks.  I tried both nightly and regular release launcher. None of them is working.

**Comment by MM2-0** [comment]
Can you provide logs? (Settings > Debug > Logs)

**Comment by drakegao** [comment]
Hi, sorry about this. You can close this issue. I didn't know that I have to click the online search filter. It doesn't say on the user guide or the website. Sorry about this.

But I pulled the source code down too, might mess around with it to see if I can add something new. Ha. Very nice launcher with the search features. Maybe if we can add the search engine for the website search it would be better.

Regards
Drake

Sent from Proton Mail Android

-------- Original Message --------
