### ISSUE TITLE
Reset of shortcuts after restart

### ISSUE THREAD

**Issue by suitably** [MM2-0/Kvaesitso#1032]
I have different websites which I add as a shortcut to my homescreen but after my phone went empty and got restarted I lost them.
I had a look into different apps and it seems that they also get resetted (i.e. Chats from Element) until they got regenerated.
If you need more information just let me know.
I'll try my best to answer it

**Comment by MM2-0** [comment]
Can you share logs? (Settings > Debug > Logs)

**Comment by suitably** [comment]
I couldn't reproduce it anymore
I'll reopen if it happens again
