### ISSUE TITLE
Can't authenticate this app to Google

### ISSUE THREAD

**Issue by pranaya2005** [MM2-0/Kvaesitso#104]
Can't seem to authenticate Kvæsitso to be able search files within Google Drive using Settings → Services → Google → Sign in with Google.
![Screenshot_20220623-134824~2](https://user-images.githubusercontent.com/61061454/175251852-adde7918-e76c-46c3-aae5-1c88dc61c45f.png)

**Comment by MM2-0** [comment]
I know. It's currently broken. I have submitted this app for verification so Google would lift the 100 user limit but they rejected it because apparently you need to have a website for your app so I'll need to build one before I can resubmit it.

**Comment by pranaya2005** [comment]
> I know. It's currently broken. I have submitted this app for verification so Google would lift the 100 user limit but they rejected it because apparently you need to have a website for your app so I'll need to build one before I can resubmit it.

Oh, sad to hear. Thanks for the info!

**Comment by MM2-0** [comment]
App is now verified, Google authentication should now work

**Comment by knirirr** [comment]
I've run into this issue as well, so presumably something else has gone wrong given that the app was verified 2 years ago.
