### ISSUE TITLE
jcenter shutdown

### ISSUE THREAD

**Issue by linsui** [MM2-0/Kvaesitso#1041]
https://jfrog.com/blog/jcenter-sunset/

https://gitlab.com/fdroid/fdroiddata/-/jobs/7604940002

Not sure if you can get it from jitpack.io. https://www.jitpack.io/#promeg/tinypinyin/v2.0.3

**Comment by MM2-0** [comment]
Thanks, will look into it when I'm done moving (~2 weeks)

**Comment by linsui** [comment]
Thanks!
