### ISSUE TITLE
(Suggestion) dial number in search bar

### ISSUE THREAD

**Issue by doonoo** [MM2-0/Kvaesitso#105]
I know you can type a contact name and dial the number that way, but what if you could dial the number itself in the search bar instead of going to the phone app itself. Just a ease of use feature.

**Comment by MM2-0** [comment]
Interesting idea. So basically check if it is a valid number (only contains +, (, ), - and digits) and display a call button if that's the case? I might actually add that, and to build on that idea, one could also display similar actions for other types of queries, for example "Create new event" if the query is a date, "Navigate" if it's an address, "Set alarm" if it's a time, and so on. Similar to the options in Android's text selection menu.

What you can already do is this:
Add a new websearch shortcut (settings > search > web search), set the title to "call" and the URL to `tel:${1}`. This will add a call button to the web searches, not context dependent though

**Comment by doonoo** [comment]
Yes sir, I was thinking of also if you send a text through the search bar depending on the message app, but I didn't want to get to complicated with the ideas. But your ideas sound awesome

**Comment by MM2-0** [comment]
Implemented in 1.19
