### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by theotheroracle** [MM2-0/Kvaesitso#106]
## Description

unsure how to reproduce

## Strack trace

```
android.app.RemoteServiceException: can't deliver broadcast
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2005)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```

## Device info
APP.VERSION : 1.12.0-20220613<br>APP.VERSIONCODE : 2022061300<br>APP.SIGNATURE : rx1fSnL7r5/OMoFC0e1KPqTndXQ=<br>LAUNCHER.APP : de.mm20.launcher2.release<br>TIMEZONE : Etc/UTC<br>VERSION.RELEASE : 11<br>VERSION.INCREMENTAL : eng.root.20220617.120314<br>VERSION.SDK.NUMBER : 30<br>BOARD : msmnile<br>BOOTLOADER : unknown<br>BRAND : OnePlus<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : lineage_hotdogb-userdebug 11 RQ3A.211001.001 eng.root.20220617.120314 dev-keys<br>FINGERPRINT : OnePlus/OnePlus7T_EEA/OnePlus7T:10/QKQ1.190716.003/1909250940:user/release-keys<br>HARDWARE : qcom<br>HOST : c751182182df<br>ID : RQ3A.211001.001<br>MANUFACTURER : OnePlus<br>MODEL : HD1905<br>PRODUCT : OnePlus7T<br>TAGS : dev-keys<br>TIME : 1655467283000<br>TYPE : userdebug

**Comment by theotheroracle** [comment]
this happens a lot and i'm not sure what causes it

**Comment by theotheroracle** [comment]
happens in the background i think

**Comment by MM2-0** [comment]
Hard to say. The stacktrace tells me nothing. Any app widgets maybe?

**Comment by theotheroracle** [comment]
i have the clock widget

**Comment by theotheroracle** [comment]
doesn't seem to crash much anymore, is it alright if i close ?

**Comment by MM2-0** [comment]
Sure
