### ISSUE TITLE
[request/suggestion] Dual-Track Release Strategy : Stable without Debug code and Nightly Builds with Debug Code for Targeted User Experience

### ISSUE THREAD

**Issue by Bhardwaj10Ankit** [MM2-0/Kvaesitso#1064]
@MM2-0 I would like to propose a development strategy where stable releases are provided without any embedded debug code, while nightly builds retain the debug code for bug reporting, crash logging, and other testing purposes.

this will provide Benefits like Enhanced Performance and Stability, Targeted User Experience, Optimized Release Cycle etc

By removing debug code from stable releases, these versions will become more lightweight and less resource-intensive. This change will contribute to a smoother and more stable user experience, making the software more appealing to general users who prioritize reliability and performance over frequent updates.

This approach allows users to choose between a stable, user-friendly version and a more development-focused nightly build. General users can enjoy a polished, stable experience with less frequent updates, while tech-savvy users who want to contribute to the development process can opt for nightly builds with enhanced logging and debugging features.

Stable releases can be scheduled at more spaced intervals, focusing on major feature updates and overall stability. This will align with the expectations of general users who typically do not require constant updates and new features. On the other hand, nightly builds can continue to be updated more frequently, catering to users who are interested in testing new features and providing feedback.

also this will make kvaesitso more Recommendable as A lighter, more stable version of Kvaesisto will be easier to recommend, particularly to general less techsavvy and never are going to provide any crash report kind of users . This could lead to increased adoption rates among general users, while still engaging a dedicated base of testers and developers through the nightly builds.

By maintaining debug code in nightly builds, you can continue to receive valuable feedback and logs from users who are willing to test new features and help identify issues, ensuring a robust development process without compromising the stability of the main product.

also if you have any uncertainity about this point of view about the releases, please consider having a poll in the telegram channel.

**Comment by MM2-0** [comment]
I'm not sure what you are talking about? Stable and nightly releases are built in release mode, with all optimizations enabled, while debug builds (which aren't published anywhere) are built in debug mode.
