### ISSUE TITLE
Search should prioritize exact result

### ISSUE THREAD

**Issue by daemon-uwa** [MM2-0/Kvaesitso#1107]
Kvaesitso currently searches by scanning app results to see if they contain the input string. This is great since you can, for example, write tube to get YouTube. However, this is doubly worse when you're searching for Tubular and have to write Tubu to finally get YouTube off of the first result. Another example is having to write RAR, instead of just R, to get RAR and not Instag(RA)m.

Is it possible to put this into place? It honestly would be a great time saver when you only have to type a single letter to open an app, rather than half of or the whole word. KISS launcher atm has this functionality, and it's the only reason I keep changing between Kvaesitso and KISS instead of just sticking to the former.

**Comment by daemon-uwa** [comment]
Another thing, why is searching "calc" showing me "calendar"? Neither does calendar contain "calc" nor does it have a second c anywhere (nor does "Google calendar" if it's taking the full name).
![Screenshot_20241012-132734_Kvaesitso](https://github.com/user-attachments/assets/4ea1bb86-7a94-492c-b789-dbe75484cdb3)

**Comment by MM2-0** [comment]
Fixed in bf6e963
