### ISSUE TITLE
[Bug] Web Search Breaking inconsistently (Firefox)

### ISSUE THREAD

**Issue by 1seco** [MM2-0/Kvaesitso#1118]
I am using the search bar to open the browser (Firefox) to that search prompt using DuckDuckGo, if that is even relevant. Either the search happens correctly, opened with my search engine, or http://(search query) gets opened instead of https://(search engine)/query , Such as http://xbps for example. It is also really inconsistent, so I was having a hard time trying to reproduce it by closing the browser, tabs, different searches, using different buttons on the launcher. (Web search vs pure enter key) I couldn't find any. If this is not a kvaesitso issue but a Firefox issue, please inform me so I can write this issue to Mozilla. I'm also free to respond for the entire next week so you can take advantage of that.

**Comment by 1seco** [comment]
I'm not really sure if this happens on other web browsers as: I don't use others, and again this issue is way too inconsistent to get it when I am ready to post here

If you need my phone info: 
A54 5G Model SM-A546E/DS, Android 14, OneUI 6.1.

**Comment by MM2-0** [comment]
What kind of action are you using? Web search? In-App search?

**Comment by 1seco** [comment]
Hi, I'm using web search, and I explicitly tap on that button above the search bar. Here is a image example I got just a while back fortunately:

![Screenshot_20241027_222221_Firefox](https://github.com/user-attachments/assets/87e62de4-2a66-407f-a028-b030e52a8a6a)

**Comment by 1seco** [comment]
And to prove inconsistency, it's working again, just a minute after:

![Screenshot_20241027_222658_Firefox](https://github.com/user-attachments/assets/752fedde-fab1-4134-8fba-d89f012f8332)

**Comment by 1seco** [comment]
I tried changing to chrome for a bit(by setting as default in system settings), but kvaesitso still opened Firefox and I don't want to go through the process of uninstalling and checking right now. My time zone isn't very friendly.

**Comment by MM2-0** [comment]
Try to add a DuckDuckGo web search action:

- go to settings > search > quick action
- tap on the + button, select "search a website"
- enter "duckduckgo.com" > next > save

**Comment by 1seco** [comment]
I did that, seems to work, the search is always prepended with duckduckgo.com/?q. I'll close this issue in a bit.
Thanks a lot and have a great day.

**Comment by 1seco** [comment]
Yep, seems to work fine. Instead of seeing purely my search query in the Firefox search bar, *then* hopefully DuckDuckGo taking over, it always prepends with DuckDuckGo with either enter or tapping the DuckDuckGo quick action.
