### ISSUE TITLE
Hide apps from favorites

### ISSUE THREAD

**Issue by Tealk** [MM2-0/Kvaesitso#113]
Hi,

is it possible to hide apps from favorites only?

**Comment by MM2-0** [comment]
Well, the obvious answer would be to not pin them in the first place so I assume you are referring to the automatically pinned, frequently used apps. There is currently no way to remove frequently used apps, the only workaround would be, to pin other apps until the app you're trying to remove disappears.

**Comment by Tealk** [comment]
An option hide From Favorites would be great

**Comment by linuxpall** [comment]
An app I launched twice within a few minutes appeared in the favorites. Will it drop out after a period of time?

**Comment by MM2-0** [comment]
> An app I launched twice within a few minutes appeared in the favorites. Will it drop out after a period of time?

It will drop out as soon as an other app takes its place. So either when you pin more apps or when another app has been launched more often (more than twice)
