### ISSUE TITLE
Tuta as a calendar

### ISSUE THREAD

**Issue by andymeakin** [MM2-0/Kvaesitso#1133]
Is it possible to pull calendar information from the Tuta calendar

**Comment by MM2-0** [comment]
The clients are [open source](https://github.com/tutao/tutanota) so it should technically be possible to build a Kvaesitso plugin that communicates with Tuta servers, decrypts the data and forwards them to Kvaesitso. But that's the only thing I can think of, I don't think there is a way to integrate with the official Tuta Android app.
