### ISSUE TITLE
Req: Long press to open apps drawer? 

### ISSUE THREAD

**Issue by bageraz88** [MM2-0/Kvaesitso#1149]
It is possible to make long press to open apps drawer in future update? Also the gestures seems to be very sensitive sometimes it's felt very jumpy especially while sliding up to see widgets. By the way the Here plugin is very superb especially with weather. Very accurate based on my location.

**Comment by MM2-0** [comment]
Settings > Gestures > Long press > Open Search ?

**Comment by KorigamiK** [comment]
> Settings > Gestures > Long press > Open Search ?

We should also allow for opening the launcher settings on long press!
