### ISSUE TITLE
app size

### ISSUE THREAD

**Issue by farfromrefug** [MM2-0/Kvaesitso#117]
your app is more than 20mb. looking at the app we can see that it almost all comes from Dex files. you should be able to reduce it with proguard.
I think the aok size could be reduced a lot.

**Comment by MM2-0** [comment]
It's on my todo list. I have disabled proguard on purpose because it breaks Retrofit and the MS SDK. So I'll first need to learn how to write proguard rules and then make sure that it doesn't break anything. Feel free to submit a pull request if you are any more experienced with proguard than I am.
