### ISSUE TITLE
Automatic color selection

### ISSUE THREAD

**Issue by Tealk** [MM2-0/Kvaesitso#119]
Android sets colors depending on background, would that be possible for this app as well?

![IMG_20220716_102232.jpg](https://user-images.githubusercontent.com/12276250/179347100-24b023b6-bdb8-47b2-9364-b7322fdb7fb0.jpg)

**Comment by MM2-0** [comment]
I'm not sure what you mean? Material You is already implemented.

**Comment by Tealk** [comment]
So the standard color scheme is not a solid color but the material you?

**Comment by MM2-0** [comment]
Yes, on Android 12+, the standard color scheme will use the system color scheme which is extracted from the user's wallpaper.

**Comment by Tealk** [comment]
Ok thank you that I did not notice, sorry
