### ISSUE TITLE
[Feature] Split layout into multiple options

### ISSUE THREAD

**Issue by Dunexus** [MM2-0/Kvaesitso#121]
Currently, choosing a layout affects :
- open app tray gesture (swipe down, swipe left, swipe right)
- position of search bar (top or bottom)
- apps order in tab tray (A-Z or Z-A)

There are currently 3 layouts available : 
- swipe down / top bar / A-Z
- swipe left / bottom bar / Z-A
- swipe right / bottom bar / Z-A

It could be great to split this into 3 options to be able to choose other combination such as having swipe down with bottom bar or bottom bar with A-Z sorting.

**Comment by labrusca** [comment]
I couldn't agree more.

**Comment by MM2-0** [comment]
Sure, I can add this.

Out of curiosity, what would your preferred layout look like if you could configure these parts independently?

**Comment by Dunexus** [comment]
> Out of curiosity, what would your preferred layout look like if you could configure these parts independently?

Bottom bar for sure, it is so much easier to use with my relatively small hands (to be honest I didn't use the search bar at all with other launcher but yours has so much useful features, calculator, contacts, wikipedia, it's so useful !).
A-Z, my mind struggles to easily find an app by going bottom to top.
Probably swipe left to keep the swipe down gesture to open notifications but I would probably try other option and see which one feels more natural on a daily usage.

**Comment by ConorIA** [comment]
Having come from KISS launcher, I would also like to tweak layout. I think the bottom bar with right swipe panel is neat, but I'd love to swap the widgets and apps so that the bottom-up swipe opens apps and the right-to-left swipe opens the widgets page.

**Comment by dv2y** [comment]
Another suggestion based on this:

A fourth option would be swap up to open the drawer and down to pull the widgets from the top

Swapping up for the drawer is natural because you just keep the same gesture afterwards to scroll through the list os apps

**Comment by Dunexus** [comment]
Latest release - [v1.21.0](https://github.com/MM2-0/Kvaesitso/releases/tag/v1.21.0) - implements the original request. Great job, the launcher gets even better after each release !

As such, I will close this issue.

@dv2y @ConorIA Could you check with latest release if your suggestions are covered by new layouts and gestures settings ? If not, I suggest to open a new ticket for these.
