### ISSUE TITLE
widgets

### ISSUE THREAD

**Issue by ahmed-tasaly** [MM2-0/Kvaesitso#124]
Aloha there

I tried to  add some widgets but it refuses to be added 

![IMG_20220726_165751](https://user-images.githubusercontent.com/64969309/181040140-e687776b-9ee0-4698-8636-a0212d9e098c.jpg)

This widow appears the create then appears again then nothing added 

Thanks in advance

**Comment by MM2-0** [comment]
Did you try to check the always allow checkbox and try it again?

**Comment by TBog** [comment]
I have the same issue.
If I don't ☑ the always allow checkbox after asking twice the widget doesn't get added.

I checked the code and I think you're binding the widget twice.

**Comment by TBog** [comment]
1. Let user choose a widget and get the `appWidgetInfo.provider`
2. generate an id with `AppWidgetHost.allocateAppWidgetId()`
3. bindAppWidgetIdIfAllowed
4. if it returned false, request permission
```
            Intent intent = new Intent(AppWidgetManager.ACTION_APPWIDGET_BIND);
            intent.putExtra(AppWidgetManager.EXTRA_APPWIDGET_ID, appWidgetId);
            intent.putExtra(AppWidgetManager.EXTRA_APPWIDGET_PROVIDER, provider);
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
                intent.putExtra(AppWidgetManager.EXTRA_APPWIDGET_PROVIDER_PROFILE, profile);
            }
            addEmptyData(intent);

            activity.startActivityForResult(intent, REQUEST_BIND_APPWIDGET);
```
5. configure widget or just create it
```
int appWidgetId = extras.getInt(AppWidgetManager.EXTRA_APPWIDGET_ID, INVALID_WIDGET_ID);
        AppWidgetProviderInfo appWidgetInfo = mAppWidgetManager.getAppWidgetInfo(appWidgetId);
        if (appWidgetInfo == null)
            return;
        AppWidgetHostView hostView = mAppWidgetHost.createView(activity.getApplicationContext(), appWidgetId, appWidgetInfo);
 ```

**Comment by MM2-0** [comment]
Thanks, I will try that

**Comment by MM2-0** [comment]
Seems to work now, thanks again for your help @TBog
