### ISSUE TITLE
[Bug?] Scrollable widgets not scrolling

### ISSUE THREAD

**Issue by conrad82** [MM2-0/Kvaesitso#127]
I use Tasks.org for tasks. The tasks widget is scrollable, but it is not working in Kvæsitso, as it scrolls the list of widgets instead.

Is this intentional? I am not sure what is the best solution, but it is limiting my work flow

**Comment by MM2-0** [comment]
Two finger scroll works most of the time. I can try to make it work normally but I don't know how bad that would interfere with the scrolling of the widget list itself.

Also, duplicate of #125
