### ISSUE TITLE
[QoL] Launch app even if in long press mode

### ISSUE THREAD

**Issue by 0xlne** [MM2-0/Kvaesitso#13]
While in the app drawer, whenever an icon is longpressed, there's a number of useful options displayed.
However, that same app cannot be launched until it exits from this mode.
My suggestion would be to enable an app to be launched regardless whether it's in that mode or not.
This saves on clicking on the left arrow to exit the mode each time.

**Comment by MM2-0** [comment]
Yeah, sounds reasonable. I was thinking about how to implement this and I basically came up with two ideas: either add an additional chip above the shortcuts / notifications or add it to the bottom toolbar (where it would probably be hidden in the overflow menu, unless we move the app-info action to the overflow menu and let the launch action take its place).

I think the first option is more accessible but it could lead to a pretty large size of that view. If an app has 5 shortcuts (the maximum amount) and 2 (or even more) notificiations that would sum up to a total of 8 chips. The second option would be more consistent with the calendar and contacts view but would still need two clicks to launch an app.

Any thoughts on this?

**Comment by lessgoo00** [comment]
Seems fine to me

**Comment by MM2-0** [comment]
Added in 665664d
