### ISSUE TITLE
Delete user-generated shortcuts

### ISSUE THREAD

**Issue by glemco** [MM2-0/Kvaesitso#131]
The shortcuts handling works great, however I couldn't find a way how to delete a shortcut I no longer need or accidentally made (e.g. whatsapp chat or browser page).
Some applications allow to delete their own shortcuts but most others rely on the launcher for that.
All I could do is to hide them, although this way they'd remain among the hidden items.
Is there a way I completely missed or is it not implemented yet?
Thanks in advance

**Comment by MM2-0** [comment]
The intended way to remove anything from the favorites is to long press it and press the star icon. However, if you have used that shortcut a lot, this will only move it down from the pinned to the frequently used items and there currently no way to remove items from the frequently used list.

**Comment by glemco** [comment]
Ok probably I didn't explain my point clearly. What I mean by shortcut is not the favorite itself, rather the searchable item (I never keep the shortcuts as favorites, I search for them, basically what you implemented in #42 ).
In other words: after a shortcut is created, removing it from the favourites doesn't remove it from the launcher (I can still search for it). What I'm looking for is a way to actually delete it, as I would with a simple drag and drop in the stock launcher.
Think of it as: you install a PWA from a browser, you always open it from the search bar (no favourites involved), you don't need it anymore, how do you get rid of it? (Can you at all?)

**Comment by MM2-0** [comment]
Will be fixed in 1.14.1

**Comment by glemco** [comment]
Great, thanks!
