### ISSUE TITLE
[Feature Request] Custom app drawer sorting

### ISSUE THREAD

**Issue by ggdorman** [MM2-0/Kvaesitso#134]
Hi. It would be great if we could reorder the apps in the apps drawer to our liking. This way we can have the same drawer layout we are used to thus making switching to and using this launcher faster.

Cheers!

**Comment by MM2-0** [comment]
I don't think I will add this. Personally, I don't find it useful and it just makes things unnecessarily complicated. Use favorites for custom order. Also what other launcher does allow that?

**Comment by ggdorman** [comment]
It's a standard feature of most launcher apps I'm pretty sure (1st and 3rd party). An example would be OneUI Home (Samsung). But if you don't want to add it then so be it. Focus on the more important things!
