### ISSUE TITLE
[Feature Request] To launch the universal-search part of the app independently

### ISSUE THREAD

**Issue by justpeanuts** [MM2-0/Kvaesitso#143]
Kvaesitso has two parts i) the homescreen-part  ii) the universal-search part
The universal-search part of the app (being able to search for apps, files, contacts etc. quickly from one search bar) is what makes this app super useful for me (i have been searching for an app like this for ages; my humble gratitude for making this app, and that too foss :heart: :heart_eyes:).
My request is to be able to launch just the search-part of the app as an independent app. The advantage of this is two-fold :- 
i) people can use a "side-launcher" like the "quick-ball" in xiaomi phones to quickly switch to the search-part of the app from another app (currently doing so would take me to the homescreen and then requires another swipe to go to the search - it is this two-click friction that i would like to eliminate )
ii) people who want to use some other launcher are free to do so, but can use the universal-search part of kvaesitso independently

another simpler way to achieve advantage i) would be to make it so that pressing the home-button while on the homescreen would launch the search. So that upon double tapping the home-button the user could go directly to the search in single gesture.

**Comment by MM2-0** [comment]
> You would at least lose access to the app shortcuts if Kvaesitso is no longer used as launcher. Only the default launcher has access to the shortcuts.

I think the default assistant app has access as well, but I'm not sure

**Comment by MM2-0** [comment]
Added in 1.15 and your right @eengnr, no shortcut access in assistant mode

**Comment by justpeanuts** [comment]
Can someone tell me how exactly to set kvaesitso as the default assistant app instead of google assistant? (sorry for the noob question but i couldn't figure it out even after some googling)

**Comment by MM2-0** [comment]
System settings > Apps > Default Apps > Digital assistant app > Default digital assistant app

**Comment by justpeanuts** [comment]
Thank you! It's working well. 
-- 
 Sent with Tutanota, enjoy secure & ad-free emails. 



19 Sep 2022, 19:59 by ***@***.***:
