### ISSUE TITLE
[Feature request] being able to fix widgets to the homescreen without having to swipe up

### ISSUE THREAD

**Issue by justpeanuts** [MM2-0/Kvaesitso#144]
i understand that this is aimed to be a minimal launcher but now to do anything - but to launch even frequently used apps from the homescreen requires two clicks - i) swipe up to get favorite app widget ii) tap the app 
This can be minimised to one click if a few widgets can be optionally placed permanently on the homescreen.

**Comment by MM2-0** [comment]
Add an option to make the clock not fill the entire screen height maybe?

**Comment by MM2-0** [comment]
> Add an option to make the clock not fill the entire screen height maybe?

I have added this in 1.15, does this solve this issue for you?
