### ISSUE TITLE
visual feedback

### ISSUE THREAD

**Issue by xi7** [MM2-0/Kvaesitso#146]
add visual feedback while open app

add visual feedback after new app instalation and after update

**Comment by lonelytheraphosidae** [comment]
Could you describe further: what kind, why and where on the screen. Thank you

**Comment by xi7** [comment]
drawer - just put effect icons
same after install new app or update. 

you can do it like "lens launcher" showing point white, yellow,green...  very discreet.  (also that onepage drawer looks more elegant with ur launcher ^_^ )

https://play.google.com/store/apps/details?id=nickrout.lenslauncher
