### ISSUE TITLE
Divide app drawer

### ISSUE THREAD

**Issue by bornhustler07** [MM2-0/Kvaesitso#147]
Hi sir first of thank you for your hard work I would like to ask can you divide between personal and work it will be nice if separated not all together👍

**Comment by sandorfimarci** [comment]
I think this one can be solved with tags, which is[ under development](https://github.com/MM2-0/Kvaesitso/issues/94) already.

**Comment by MM2-0** [comment]
> I think this one can be solved with tags, which is[ under development](https://github.com/MM2-0/Kvaesitso/issues/94) already.

No, not really, I think.

**Comment by sandorfimarci** [comment]
If you add `work` tag to every one of the work apps, and same with the personal apps (so add `personal` tag to them), then you have to only search for `work`/`personal` and it will show up.
At least this is my understanding with tags. (And this is how it works in kiss launcher)

Idk how you are planning to implement it, maybe in a different way, but it could be solved by that as well.

**Comment by MM2-0** [comment]
> If you add `work` tag to every one of the work apps, and same with the personal apps (so add `personal` tag to them), then you have to only search for `work`/`personal` and it will show up.

That would work but I don't think this is want OP wants. What OP wants is an app drawer that is not cluttered with work profile apps. Tagging all apps individually is a ton of work and doesn't really help with that.

**Comment by MM2-0** [comment]
Added in 1.16
