### ISSUE TITLE
Allow creation of shortcut widgets

### ISSUE THREAD

**Issue by eengnr** [MM2-0/Kvaesitso#154]
Currently I can't find a way to add a shortcut widget from outside of an app.

E.g. the ConnectBot app allows to add a shortcut widget with one of the configured SSH connections. But this cannot be done from within the app, only by adding it as "widget" in other launchers. Kvaesitso however does not show this kind of widget as option. Only "normal" widgets can be added to the widget section, but no shortcut widgets can be created/added to the favourites/apps overview.
If a shortcut widget could be added, it would also be possible to quickly find it from the search bar, i.e. in the case of ConnectBot to quickly open an SSH connection from the search bar.
The same might apply to other apps, e.g. radio stations of radio apps, specific podcasts of podcast apps, contacts of chat apps and so on...

Probably this would be a good addition to #133

**Comment by MM2-0** [comment]
I will probably rework the "edit favorites" panel in the future and I'll make sure to include a way to create new shortcuts

**Comment by eengnr** [comment]
Adding shortcuts from the launcher works in the latest release, thanks!
But it's not possible to find them with the search. Is this intended behavior?

**Comment by MM2-0** [comment]
> But it's not possible to find them with the search. Is this intended behavior?

If they use the modern (introduced on Android 8.0) shortcut API, then they are searchable. If they use the legacy API, then they are not. Not sure if I want to fix that since it is a legacy API (even though it's still used by many apps).

As a workaround, you can set a custom label to the shortcut, this will make it searchable.

**Comment by eengnr** [comment]
> If they use the modern (introduced on Android 8.0) shortcut API, then they are searchable. If they use the legacy API, then they are not. Not sure if I want to fix that since it is a legacy API (even though it's still used by many apps).

I see, thanks! From a user perspective it's just not clear why it doesn't work.
But I won't open a new issue and leave it up to you to support this or not.

**Comment by MM2-0** [comment]
True. But I wonder how many users actually see this as an issue. You can open a new issue if you want. If more users support this, I'll reconsider it.
