### ISSUE TITLE
Text in Settings -> Icon shape

### ISSUE THREAD

**Issue by mapi68** [MM2-0/Kvaesitso#165]
Can you enlarge Settings -> Icon shape, because "arrotondato" is shown in 2 lines

![_20220909_182012](https://user-images.githubusercontent.com/41143572/189397905-3b777743-cb5a-4166-a26d-949f2e8e4929.png)

**Comment by MM2-0** [comment]
I'll probably just remove the text, the icons are way more meaningful anyway

**Comment by mapi68** [comment]
I have found another word
