### ISSUE TITLE
Adding Kvaesitso widget (Weather, Music, Calendar) crashes Kvaesitso

### ISSUE THREAD

**Issue by HerrHellmus** [MM2-0/Kvaesitso#17]
When I try to add a native Kvaesitso widget, the launcher crashes. Third party widgets work fine.
Below the crash report:

> java.lang.ClassCastException: android.view.ContextThemeWrapper cannot be cast to androidx.lifecycle.LifecycleOwner
> 	at de.mm20.launcher2.ktx.ViewKt.getLifecycleScope(View.kt:20)
> 	at de.mm20.launcher2.ui.legacy.view.LauncherCardView.onAttachedToWindow(LauncherCardView.kt:84)
> 	at android.view.View.dispatchAttachedToWindow(View.java:21971)
> 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4293)
> 	at android.view.ViewGroup.addViewInner(ViewGroup.java:6127)
> 	at android.view.ViewGroup.addView(ViewGroup.java:5903)
> 	at android.view.ViewGroup.addView(ViewGroup.java:5843)
> 	at android.view.ViewGroup.addView(ViewGroup.java:5815)
> 	at com.jmedeisis.draglinearlayout.DragLinearLayout.addDragView(DragLinearLayout.java:237)
> 	at de.mm20.launcher2.ui.launcher.widgets.WidgetsView$addWidget$1$2.invoke(WidgetsView.kt:217)
> 	at de.mm20.launcher2.ui.launcher.widgets.WidgetsView$addWidget$1$2.invoke(WidgetsView.kt:206)
> 	at com.afollestad.materialdialogs.internal.list.PlainListDialogAdapter.itemClicked(PlainListDialogAdapter.kt:76)
> 	at com.afollestad.materialdialogs.internal.list.PlainListViewHolder.onClick(PlainListDialogAdapter.kt:46)
> 	at android.view.View.performClick(View.java:7792)
> 	at android.view.View.performClickInternal(View.java:7769)
> 	at android.view.View.access$3800(View.java:910)
> 	at android.view.View$PerformClick.run(View.java:30184)
> 	at android.os.Handler.handleCallback(Handler.java:938)
> 	at android.os.Handler.dispatchMessage(Handler.java:99)
> 	at android.os.Looper.loopOnce(Looper.java:226)
> 	at android.os.Looper.loop(Looper.java:313)
> 	at android.app.ActivityThread.main(ActivityThread.java:8633)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)

Device Information

DEVICE.ID : d3200eec34f60ff7
APP.VERSION : 2022013001
LAUNCHER.APP : de.mm20.launcher2.release
TIMEZONE : Europe/Amsterdam
VERSION.RELEASE : 12
VERSION.INCREMENTAL : G970FXXUEGVA4
VERSION.SDK.NUMBER : 31
BOARD : exynos9820
BOOTLOADER : G970FXXUEGVA4
BRAND : samsung
CPU_ABI : arm64-v8a
CPU_ABI2 :
DISPLAY : SP1A.210812.016.G970FXXUEGVA4
FINGERPRINT : samsung/beyond0lteeea/beyond0:12/SP1A.210812.016/G970FXXUEGVA4:user/release-keys
HARDWARE : exynos9820
HOST : 21DJ7D18
ID : SP1A.210812.016
MANUFACTURER : samsung
MODEL : SM-G970F
PRODUCT : beyond0lteeea
SERIAL : unknown
TAGS : release-keys
TIME : 1642001741000
TYPE : user
UNKNOWN : unknown
USER : dpi

**Comment by MM2-0** [comment]
Fixed in 8a3b828
