### ISSUE TITLE
Auto Change Wallpaper 

### ISSUE THREAD

**Issue by fossimprove** [MM2-0/Kvaesitso#173]
Since launcher has been greatly focus on Material You, Themed Icons and Colours!

Auto changing wallpaper would be great and have different colourschemes all time.

I know, some apps exist to do that, but its another load. So simply embedding this feature in a launcher will work even more well.

Hey Dev, please dont deny this feature. Many people would feel it required and will be happy to have this feature.

Thank you!

**Comment by MM2-0** [comment]
I'm sorry but I won't add this.

I agree that changing wallpapers are great, especially on Android 12.
But I don't see any good reasons for why this should be part of a launcher. There are already dozens of apps our there that do exactly what you are asking for, including FOSS ones. There isn't much benefit in baking this directly into the launcher.
Maybe you underestimate the amount of work that is needed to build such a wallpaper app but I would rather use my time to actually improve the core functionality of the launcher and not to reinvent functionality that can easily achieved using other, already existing apps.
