### ISSUE TITLE
[Feature Request] Ability to customize the background color of the containers

### ISSUE THREAD

**Issue by Occhioverde** [MM2-0/Kvaesitso#184]
In the current version of Kvæsitso, the background color of the containers holding the application icons and the widgets contents is automatically calculated from the primary color, even if "Advanced mode" is checked in the color scheme page.

In my opinion, it would be a better choice to allow the user to manually pick the background color of the containers, keeping the automatic generation confined to the "Simple mode".

**Comment by MM2-0** [comment]
The way surface background colors are calculated is they have a base color (`colorSurface`) and then, depending on their elevation, a tint overlay is applied (so in dark mode, higher elevated surfaces appear brighter, in light mode they appear darker). This overlay color (`surfaceTint`) defaults to the primary color. IIRC it wasn't possible to customize that overlay color when I implemented custom color schemes, but now it is so I'll add the missing field to the advanced color schemes.
