### ISSUE TITLE
[Feature Request] Hide apps in drawer but not search results

### ISSUE THREAD

**Issue by ForeverFloating** [MM2-0/Kvaesitso#194]
I want to hide my tagged apps from the app drawer, which I can do manually but this automatically results in the apps also being hidden from search results. I want to hide my tagged apps from view in the drawer (not removing them from the tag groups) and still search for them in the search bar. I can think a non-exhaustive list of potential ways to address this:

1. An option to automatically hide tagged apps from the drawer but still enable searching the apps
2. Two separate options for hiding apps: one for the drawer, and one for search results
3. An option to enable searching all apps regardless of whether these apps are hidden

**Comment by MM2-0** [comment]
Implemented in c7ea840
