### ISSUE TITLE
[Feature Request] Open Nextcloud files in app

### ISSUE THREAD

**Issue by HerrHellmus** [MM2-0/Kvaesitso#20]
I noticed that when I select a file on my Nextcloud in the search bar, it opens in the webbrowser. I think it would be nice if it opened in the Android app. 
I'm no expert, but I think thos should be possible with `nc:[url]`.

**Comment by MM2-0** [comment]
I couldn't verify the `nc:[url]` part but I found a different way. Implemented in 7ad3668
