### ISSUE TITLE
Bug when trying to search alternative icon for an app

### ISSUE THREAD

**Issue by luimu64** [MM2-0/Kvaesitso#202]
If I want to change app icon located at the top of the list, when searching for the icon, the popup closes prematurely.

Demo with first the bug, then how it should work and then the bug again:

https://user-images.githubusercontent.com/54173370/199809787-946dcc89-c904-4f57-83b6-ec75b5dd7fb1.mp4

As a work around I can add the app to favorites and change the icon using the favorites shortcut, so clearly the icon location on the list is important factor in this.

**Comment by KrisadaFantasy** [comment]
I can reproduce this bug. Seems like it's only effect layout that swipe left/right for app drawer. It's not happening with pull down layout I'm using.
