### ISSUE TITLE
Add a result to search for the input on the web

### ISSUE THREAD

**Issue by BrightDV** [MM2-0/Kvaesitso#21]
Hello,
It would be nice to have a feature similar to Blue line console :
<img src="https://user-images.githubusercontent.com/92821484/152699012-8f820d54-8521-4303-9261-c830598bdbe3.jpg" alt="blue line console screen" height="200">
When you search for something, it adds a possibility to open the input in a web search.

It could be implemented by selecting the first search engine of the launcher 
For example, it would open 
<img src="https://user-images.githubusercontent.com/92821484/152699116-df37d7a4-7c99-4dbe-a0c7-91589912ebe5.jpg" alt="kvaesitso screen"  height="100">
In Brave Search.

**Comment by MM2-0** [comment]
I don't understand…? Isn't that exactly what is already implemented?

**Comment by BrightDV** [comment]
Yes, you're right sorry
