### ISSUE TITLE
Search text doesn't clear after searching for an app

### ISSUE THREAD

**Issue by tomvernon** [MM2-0/Kvaesitso#211]
Other launchers will reset the state of the launcher back to the home screen after searching and opening an app. It would save a lot of time if this was the case. Maybe set a toggle in the settings to do this? Love the app btw, my favourite launcher atm. A little stuttery on my pixel 7 but I can live with it for now. Thanks!

**Comment by sandorfimarci** [comment]
Duplicated, and fixed. 
Could be closed
