### ISSUE TITLE
Add Bandcamp to audio applications

### ISSUE THREAD

**Issue by Sir-Photch** [MM2-0/Kvaesitso#212]
Media playback of com.bandcamp.android does not show up in the clock widget unless "show non music players" is checked. It should be considered to be one of them, IMO.

**Comment by Sir-Photch** [comment]
I had a look at the code, namely [MusicRepository.kt L449](https://github.com/MM2-0/Kvaesitso/blob/main/music/src/main/java/de/mm20/launcher2/music/MusicRepository.kt#L449), and it seems like you just filter by the android intents. Is this a problem of the bandcamp-app then? Or do you further define that filter somewhere else?

**Comment by MM2-0** [comment]
> I had a look at the code, namely [MusicRepository.kt L449](https://github.com/MM2-0/Kvaesitso/blob/main/music/src/main/java/de/mm20/launcher2/music/MusicRepository.kt#L449), and it seems like you just filter by the android intents. Is this a problem of the bandcamp-app then? Or do you further define that filter somewhere else?

Yep, that's exactly what happens. Apps that don't declare a CATEGORY_MUSIC intent are not recognized as music apps. Might be worth considering to add a hardcoded list of packages, given that there are a few popular apps that are not recognized because of this.

**Comment by Sir-Photch** [comment]
Lets see, I'll contact the support. Maybe they add this 👍🏼

**Comment by MM2-0** [comment]
Added in fe06548.

**Comment by Sir-Photch** [comment]
@MM2-0 this is also the case for `com.qobuz.music`

**Comment by MM2-0** [comment]
> @MM2-0 this is also the case for com.qobuz.music

Added!
