### ISSUE TITLE
Smart (frequency+recency) and instant search everything

### ISSUE THREAD

**Issue by nv2p** [MM2-0/Kvaesitso#223]
Thanks a lot for this very nice and complete launcher!

I like very much the ability to search a bit everything (have all _on_ except Wikipedia and websites preview), but struggle to understand the underlying mechanisms and think it could be improved.

1. When I insert only 1 letter, I don't get app suggestions, contacts or shortcuts, only folders or files (if _on_), which is a pity and not what most people want, I think.
2. I need to type sometimes up to 3 characters (sometimes 2 are enough) to get the app I want and even more for a file.
3. Maybe the most important: my choices are not remembered, although you seem to have this mechanism implemented for the favorites.

Am I right? If yes, do you have any ideas on how to implement this? Although it doesn’t search files, the [KISS launcher](https://github.com/Neamar/KISS/) have this implemented for its app/shortcuts/contacts search and its source is open, so I guess inspiration could be taken there. Sesame shortcuts, which is more complete but unfortunately closed source, have this for all, so it means it should be possible.

**Comment by MM2-0** [comment]
I understand that search might appear to behave unpredictable. There are two reasons that contribute to this:

1. Each of the underlying search providers uses its own method of searching so it's not always consistent whether an item matches a certain search query:
   - App and shortcut search are performed by the launcher itself; all available apps and shortcuts are loaded in memory and each item is matched against the search query using some sort of fuzzy matching. As an unintended side effect, 1-letter rarely pass the fuzzy matching which I should probably fix.
   - Calendar and contact search use Android's content provider APIs which unfortunately do not support any form of fuzzy matching so they only test whether or not the item contains the query string as a whole.
   - Local files uses the same mechanics but for cloud files, the query is forwarded to the corresponding cloud service and the searching is performed by the server.
   - Wikipedia search is performed by the Wikipedia server as well.
2. Most of the providers have a threshold and won't return anything when the query is shorter than this threshold:
   - calendar and contacts threshold is 3
   - for files the threshold is 4 (but if a file with a filename that is shorter than 4 letters exactly matches the query, it is returned nevertheless)
   - cloud file searches have a threshold of 4 as well
   - Wikipedia apparently doesn't have a threshold, this is most certainly a mistake

Thresholds exist to reduce the potential number of search results. They are capped anyway but there is no point in showing 30 different files containing the letter 'a' when there is in reality a total of 1000 files that would also match that query but aren't shown. It's pretty unlikely that the one file you are looking for is actually part of that list. To encourage users to use longer, more precise search terms, results are only shown when a certain threshold is reached.

As for your third point, the launcher does not "learn" from your searches. Search queries are never stored. The only that is ever tracked is how often you tap on a search result. Each time you tap on it, a counter is incremented but the search query you used to get there isn't stored. If you find yourself searching for the same item over and over again, you should consider pinning it to favorites, or at least that is the intended way.

**Comment by nv2p** [comment]
Thank you very much for this detailed answer, which explains well what I indeed found incoherent and now better understand. It fits with my experience so far. I think it would be worth putting this somewhere in your doc.

> As an unintended side effect, 1-letter rarely pass the fuzzy matching which I should probably fix.

100% agree 😉

> calendar and contacts threshold is 3

I understand the need for a threshold for files and maybe for calendar, but it's unfortunate for contacts, I think.

> Wikipedia apparently doesn't have a threshold, this is most certainly a mistake

I disabled it, because I found annoying to have it popping all the time.

> As for your third point, the launcher does not "learn" from your searches.

I think this is a big loss. It can be faster to enter few letters (knowing what you will get) than adding favorites, which is a manual operation by the way (not very time-consuming, but still you have to do it for each + maybe sort).

In my view, 3 lines of favorites would be a maximum to not undermine its purpose (fast finding is hindered if you have to visually search among all of them). With 6 per line, it's 18 for all (apps, shortcuts, contacts, few files maybe, etc.). I use more than this on a regular basis and it would help a lot if the non-favorites would pop in a smart way.

I think this "learning" from my search is exactly one of the main reason KISS is so popular. It's also something built-in Windows searches, Rofi on GNU/Linux, etc.

If it's too difficult to implement for all the providers, to do it just for apps and contacts, for instance, would be already a nice add you should consider very seriously in my opinion.

**Comment by MM2-0** [comment]
I don't quite get what learning does? Could you elaborate? How does it work? Say you type "pho" and tap on phone. Now the launcher knows that "pho" should display the phone app but it already knew that (the user couldn't have tapped on it if that wasn't the case) so what should the launcher learn from that?

**Comment by nv2p** [comment]
I mean that the launcher remember what I click on the most, not just for a specific _entry_ ideally. If I type "pho" and get 3 possible apps, from which I choose the phone one, this result should be the first. If the name of my wife, which I often call (click) is "Phoebe", the same. Of course, this is much more useful if it works already with only 1 letter.

KISS has a history setting, where you can choose between accessed "recently", "frequently", both, "adapted to user usage" (no idea...) and "alphabetically", and where you see your current number of items (ex. mine now is 1595) and delete all if you want. My guess is that KISS add the app/contact/shortcut, etc., to a file each time you click on it and count the repetition of the same. It then gives you, according to your choice (let's say frequency, to keep it simple), the item you click most often on, depending on what you typed (if you typed "pho", it won't give you "Rafael", even if that's the most contacted person).

In your actual system, I may have to type quite a lot if the item I want is a very common name (and the threshold high) and it's a bit frustrating that I have to do this each time, without the system remembering what I like. Of course, I can use favorites, but as said, there are limits to this in my view.

**Comment by MM2-0** [comment]
Ah, I see. I guess we could use the usage stats that are stored for favorites/frequently used items to order the search results accordingly. This wouldn't map items to specific search terms but it would certainly improve the relevance of the topmost item.

**Comment by nv2p** [comment]
Yes, that sounds very nice. If you lower the threshold to 1 letter for apps (and contacts/others too, ideally), that would be a big improvement I think. Thanks for considering!

**Comment by MM2-0** [comment]
I have tweaked the thresholds and fixed the substring matching for apps and shortcuts in 1.20. I'll attend to the order of search results in a later update.

**Comment by nv2p** [comment]
Just tried and indeed, I get apps when I enter only 1 letter and contacts with 2 letters. Ideally in the future, you could consider leaving these choices to the user, with options in the settings. Anyway, great improvement already. Thanks!

**Comment by myhrmans** [comment]
> Ah, I see. I guess we could use the usage stats that are stored for favorites/frequently used items to order the search results accordingly. This wouldn't map items to specific search terms but it would certainly improve the relevance of the topmost item.

This.

This is one of the remaining reasons I'm sticking to Nova Launcher with Sesame.

It makes it really easy to quickly open apps.
