### ISSUE TITLE
Inclusion to F-Droid?

### ISSUE THREAD

**Issue by ClockGen** [MM2-0/Kvaesitso#227]
As I understand, the app relies on a number of proprietary libraries for search providers. Would it be possible to remove them during the build, or the app would require extensive rewrite rather than simply patching out gradle modules? If that so, is it possible to create a FOSS build flavor to include the app to mainline F-Droid repos in the future? (Assuming you'd still want this app to be published in F-Droid with reduced functionality).

**Comment by MM2-0** [comment]
There aren't any proprietary libraries included, all included libraries are using a FOSS license. You can simply checkout the code and build it and you'll get an APK that is 100% FOSS.

However, certain API keys are required for certain external services (for example, you must set up a project in the Google Cloud console to enable the Google Drive search feature). If you do not set up these keys, the corresponding feature will be disabled in the final APK. This would be the case for F-Droid builds.

The exact steps how to setup the external services are described here: https://kvaesitso.mm20.de/docs/developer-guide/external-apis/

**Comment by Diniboy1123** [comment]
Sorry to hop into the conversation, but can't you just create a settings page where the user can supply their API keys for those services in the fdroid version? That way if they want, they can still generate one on their own, but the app is free from those keys during the build time. Or is that also not welcomed by fdroid?

Don't get me wrong, I am totally fine with the way how things are now, just thinking about certain possibilities.

**Comment by MM2-0** [comment]
> Sorry to hop into the conversation, but can't you just create a settings page where the user can supply their API keys for those services in the fdroid version? That way if they want, they can still generate one on their own, but the app is free from those keys during the build time.

I think that might be against the TOS of the API services. Because the number of free API calls is usually limited and you'd circumvent that if you promped users to provide their own API keys.

Also you can't use the same package name / signature combination in multiple Google cloud projects so that one can't be configured by users.

I think the intended way is to use [reproducible builds](https://f-droid.org/docs/Reproducible_Builds/) but I haven't really looked into this yet.

**Comment by Diniboy1123** [comment]
Oh I see. Good point. Didn't think about the package name limitation. I usually use their apis in cli applications where package name isn't necessary.

And I understand that you don't want others to use your API keys. All I could think of is a static file served by some webserver (could also be a free one, like a private repo with github pages [iirc this requires a github pro account though] or cloudflare pages/workers) that the clients would request and cache upon the first launch. Not sure if that's a decent idea though or tolerated by fdroid.

**Comment by MM2-0** [comment]
One thing I was thinking about is to introduce some kind of plugin API and move all parts that depend on external APIs to plugins. Another advantage of this would be, that it would be easier for 3rd party developers to add support for other cloud services. The disadvantage is, that users would need to install a dozen of different APKs to enable the full functionality of the launcher.

**Comment by ClockGen** [comment]
> There aren't any proprietary libraries included, all included libraries are using a FOSS license. You can simply checkout the code and build it and you'll get an APK that is 100% FOSS.
> 
> However, certain API keys are required for certain external services (for example, you must set up a project in the Google Cloud console to enable the Google Drive search feature). If you do not set up these keys, the corresponding feature will be disabled in the final APK. This would be the case for F-Droid builds.
> 
> The exact steps how to setup the external services are described here: https://kvaesitso.mm20.de/docs/developer-guide/external-apis/

Yes, but the included maven repos (especially google()) can contain proprietary libs, while the entirety of code in this repo would be 100% FOSS, the project would still use proprietary libs.  Just making sure that all libraries included in all modules are also FOSS, considering, how much onedrive and gdrive functionality there is.

Regarding disabled functionality in the resulting APK: I can't talk for the entirety of the F-Droid userbase, but many switch to F-Droid specifically to avoid google and proprietary services/apps, so lack of such probably wouldn't be big issue.

One concerning thing though, is the custom microsoft azure maven repo. F-Droid doesn't permit custom maven repos.

**Comment by MM2-0** [comment]
> Yes, but the included maven repos (especially google()) can contain proprietary libs, while the entirety of code in this repo would be 100% FOSS, the project would still use proprietary libs. Just making sure that all libraries included in all modules are also FOSS, considering, how much onedrive and gdrive functionality there is.

It can happen (if dependencies I use have other, non-free transitive dependencies) but it shouldn't. If a library is licensed under a FOSS license, it shouldn't have unfree dependencies as that would make the library as a whole unfree. All libraries the launcher depends on directly are licensed under an open source license (Apache 2.0, MIT, Simplified BSD or Modified BSD).

It's totally normal for Android projects to include the `google()` repository because this is the only repository that serves Google's AndroidX libraries.

I don't know why the Microsoft Auth library depends on the Surface Duo SDK but it's MIT licensed so that's all that matters.

Here is a complete list of all dependencies including transitive and compile time only dependencies:
<details>

```
com.google.accompanist:accompanist-drawablepainter:0.25.1
com.google.accompanist:accompanist-flowlayout:0.27.0
com.google.accompanist:accompanist-insets:0.27.0
com.google.accompanist:accompanist-navigation-animation:0.27.0
com.google.accompanist:accompanist-pager-indicators:0.27.0
com.google.accompanist:accompanist-pager:0.27.0
com.google.accompanist:accompanist-systemuicontroller:0.27.0
androidx.activity:activity-compose:1.6.0-rc02
androidx.activity:activity-ktx:1.4.0
androidx.activity:activity:1.6.0-rc02
org.ahocorasick:ahocorasick:0.3.0
com.caverock:androidsvg-aar:1.4
androidx.compose.animation:animation-core:1.4.0-alpha02
androidx.compose.animation:animation-graphics:1.4.0-alpha02
androidx.compose.animation:animation:1.4.0-alpha02
androidx.annotation:annotation-experimental:1.3.0
androidx.annotation:annotation:1.3.0
org.jetbrains:annotations:13.0
androidx.appcompat:appcompat-resources:1.6.0-rc01
androidx.appcompat:appcompat:1.6.0-rc01
org.ow2.asm:asm-analysis:9.1
org.ow2.asm:asm-commons:9.1
org.ow2.asm:asm-tree:9.1
org.ow2.asm:asm:9.1
org.jetbrains.kotlinx:atomicfu:0.17.3
com.google.auto.value:auto-value-annotations:1.9
androidx.autofill:autofill:1.0.0
com.azure:azure-core:1.28.0
androidx.browser:browser:1.4.0
androidx.cardview:cardview:1.0.0
org.checkerframework:checker-qual:3.12.0
io.coil-kt:coil-base:2.2.1
io.coil-kt:coil-compose-base:2.2.1
io.coil-kt:coil-compose:2.2.1
io.coil-kt:coil-svg:2.2.1
io.coil-kt:coil:2.2.1
androidx.collection:collection-ktx:1.1.0
androidx.collection:collection:1.1.0
com.github.ajalt.colormath:colormath-jvm:3.2.0
com.github.ajalt.colormath:colormath:3.2.0
com.microsoft.identity:common4j:3.0.1
com.microsoft.identity:common:6.0.1
org.apache.commons:commons-lang3:3.11
org.shredzone.commons:commons-suncalc:3.5
org.apache.commons:commons-text:1.9
com.godaddy.android.colorpicker:compose-color-picker-android:0.5.0
com.godaddy.android.colorpicker:compose-color-picker:0.5.0
androidx.concurrent:concurrent-futures:1.0.0
androidx.constraintlayout:constraintlayout-core:1.0.3
androidx.constraintlayout:constraintlayout:2.1.3
com.squareup.retrofit2:converter-gson:2.9.0
androidx.coordinatorlayout:coordinatorlayout:1.1.0
androidx.arch.core:core-common:2.1.0
androidx.core:core-ktx:1.9.0
androidx.arch.core:core-runtime:2.1.0
androidx.core:core:1.9.0
androidx.cursoradapter:cursoradapter:1.0.0
androidx.customview:customview-poolingcontainer:1.0.0
androidx.customview:customview:1.1.0
androidx.datastore:datastore-core:1.0.0
androidx.datastore:datastore:1.0.0
com.microsoft.device.display:display-mask:0.3.0
androidx.documentfile:documentfile:1.0.0
androidx.drawerlayout:drawerlayout:1.1.1
androidx.dynamicanimation:dynamicanimation-ktx:1.0.0-alpha03
androidx.dynamicanimation:dynamicanimation:1.0.0
androidx.emoji2:emoji2-views-helper:1.2.0-rc01
androidx.emoji2:emoji2:1.2.0-rc01
com.google.errorprone:error_prone_annotations:2.15.0
androidx.exifinterface:exifinterface:1.3.3
com.google.guava:failureaccess:1.0.1
androidx.compose.foundation:foundation-layout:1.4.0-alpha02
org.jetbrains.compose.foundation:foundation:1.1.0
androidx.compose.foundation:foundation:1.4.0-alpha02
androidx.fragment:fragment-ktx:1.4.1
androidx.fragment:fragment:1.3.6
com.google.api-client:google-api-client-android:2.0.0
com.google.api-client:google-api-client:1.25.0
com.google.apis:google-api-services-drive:v3-rev197-1.25.0
com.google.apis:google-api-services-oauth2:v2-rev157-1.25.0
com.google.auth:google-auth-library-credentials:1.11.0
com.google.auth:google-auth-library-oauth2-http:1.11.0
com.google.http-client:google-http-client-gson:1.42.2
com.google.http-client:google-http-client-jackson2:1.25.0
com.google.http-client:google-http-client:1.42.2
com.google.oauth-client:google-oauth-client:1.25.0
io.grpc:grpc-context:1.27.2
com.google.code.gson:gson:2.9.1
com.google.guava:guava:31.1-jre
cz.msebera.android:httpclient:4.5.8
org.apache.httpcomponents:httpcore:4.4.15
androidx.interpolator:interpolator:1.0.0
com.google.j2objc:j2objc-annotations:1.3
com.fasterxml.jackson.core:jackson-annotations:2.13.2
com.fasterxml.jackson:jackson-bom:2.13.2
com.fasterxml.jackson.core:jackson-core:2.13.2
com.fasterxml.jackson.core:jackson-databind:2.13.2.2
com.fasterxml.jackson.dataformat:jackson-dataformat-xml:2.13.2
com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.13.2
com.github.stephenc.jcip:jcip-annotations:1.0-1
net.java.dev.jna:jna:5.6.0
org.jsoup:jsoup:1.15.3
com.google.code.findbugs:jsr305:3.0.2
io.insert-koin:koin-android:3.2.0
io.insert-koin:koin-androidx-compose:3.2.0
io.insert-koin:koin-core-jvm:3.2.0
io.insert-koin:koin-core:3.2.0
org.jetbrains.kotlin:kotlin-compiler-embeddable:1.7.21
org.jetbrains.kotlin:kotlin-daemon-embeddable:1.7.21
org.jetbrains.kotlin:kotlin-klib-commonizer-embeddable:1.7.21
org.jetbrains.kotlin:kotlin-reflect:1.7.21
org.jetbrains.kotlin:kotlin-script-runtime:1.7.21
org.jetbrains.kotlin:kotlin-stdlib-common:1.7.21
org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.7.10
org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.7.10
org.jetbrains.kotlin:kotlin-stdlib:1.7.21
org.jetbrains.kotlinx:kotlinx-collections-immutable-jvm:0.3.5
org.jetbrains.kotlinx:kotlinx-collections-immutable:0.3.5
org.jetbrains.kotlinx:kotlinx-coroutines-android:1.6.4
org.jetbrains.kotlinx:kotlinx-coroutines-bom:1.6.4
org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.6.4
org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4
androidx.legacy:legacy-support-core-utils:1.0.0
androidx.lifecycle:lifecycle-common-java8:2.6.0-alpha02
androidx.lifecycle:lifecycle-common:2.6.0-alpha02
androidx.lifecycle:lifecycle-extensions:2.2.0
androidx.lifecycle:lifecycle-livedata-core-ktx:2.6.0-alpha02
androidx.lifecycle:lifecycle-livedata-core:2.6.0-alpha02
androidx.lifecycle:lifecycle-livedata-ktx:2.6.0-alpha02
androidx.lifecycle:lifecycle-livedata:2.6.0-alpha02
androidx.lifecycle:lifecycle-process:2.4.1
androidx.lifecycle:lifecycle-runtime-ktx:2.6.0-alpha02
androidx.lifecycle:lifecycle-runtime:2.6.0-alpha02
androidx.lifecycle:lifecycle-service:2.1.0
androidx.lifecycle:lifecycle-viewmodel-compose:2.6.0-alpha02
androidx.lifecycle:lifecycle-viewmodel-ktx:2.6.0-alpha02
androidx.lifecycle:lifecycle-viewmodel-savedstate:2.5.1
androidx.lifecycle:lifecycle-viewmodel:2.6.0-alpha02
androidx.loader:loader:1.0.0
androidx.localbroadcastmanager:localbroadcastmanager:1.0.0
com.airbnb.android:lottie-compose:5.2.0
com.airbnb.android:lottie:5.2.0
androidx.compose.material:material-icons-core:1.4.0-alpha02
androidx.compose.material:material-icons-extended:1.4.0-alpha02
androidx.compose.material:material-ripple:1.4.0-alpha02
androidx.compose.material3:material3:1.1.0-alpha02
org.jetbrains.compose.material:material:1.1.0
androidx.compose.material:material:1.4.0-alpha02
com.google.android.material:material:1.8.0-alpha01
org.mariuszgromada.math:MathParser.org-mXparser:4.4.2
com.microsoft.graph:microsoft-graph-core:2.0.13
com.microsoft.graph:microsoft-graph:5.34.0
com.microsoft.identity.client:msal:4.0.1
io.github.aakira:napier-android-debug:1.4.1
io.github.aakira:napier-android:1.4.1
io.github.aakira:napier:1.4.1
androidx.navigation:navigation-common-ktx:2.6.0-alpha01
androidx.navigation:navigation-common:2.6.0-alpha01
androidx.navigation:navigation-compose:2.6.0-alpha01
androidx.navigation:navigation-runtime-ktx:2.6.0-alpha01
androidx.navigation:navigation-runtime:2.6.0-alpha01
com.nimbusds:nimbus-jose-jwt:9.9
com.squareup.okhttp3:okhttp:4.10.0
com.squareup.okio:okio-jvm:3.2.0
com.squareup.okio:okio:3.2.0
io.opencensus:opencensus-api:0.31.1
io.opencensus:opencensus-contrib-http-util:0.31.1
org.jacoco:org.jacoco.agent:0.8.7
org.jacoco:org.jacoco.ant:0.8.7
org.jacoco:org.jacoco.core:0.8.7
org.jacoco:org.jacoco.report:0.8.7
androidx.palette:palette:1.0.0
androidx.print:print:1.0.0
androidx.profileinstaller:profileinstaller:1.2.0
com.google.protobuf:protobuf-javalite:3.14.0
org.reactivestreams:reactive-streams:1.0.3
io.projectreactor:reactor-core:3.4.17
androidx.recyclerview:recyclerview:1.1.0
androidx.resourceinspection:resourceinspection-annotation:1.0.1
com.squareup.retrofit2:retrofit:2.9.0
androidx.room:room-common:2.5.0-alpha03
androidx.room:room-ktx:2.5.0-alpha03
androidx.room:room-runtime:2.5.0-alpha03
androidx.compose.runtime:runtime-livedata:1.4.0-alpha02
androidx.compose.runtime:runtime-saveable:1.3.0-rc01
org.jetbrains.compose.runtime:runtime:1.1.0
androidx.compose.runtime:runtime:1.4.0-alpha02
androidx.savedstate:savedstate-ktx:1.1.0
androidx.savedstate:savedstate:1.2.0
androidx.security:security-crypto:1.1.0-alpha03
org.slf4j:slf4j-api:1.7.36
dev.chrisbanes.snapper:snapper:0.2.2
androidx.sqlite:sqlite-framework:2.3.0-alpha05
androidx.sqlite:sqlite:2.3.0-alpha05
androidx.startup:startup-runtime:1.0.0
co.touchlab:stately-common:1.2.0
co.touchlab:stately-concurrency:1.2.0
org.codehaus.woodstox:stax2-api:4.2.1
com.google.crypto.tink:tink-android:1.5.0
com.github.promeg:tinypinyin:2.0.2
androidx.tracing:tracing:1.0.0
androidx.transition:transition:1.2.0
org.jetbrains.intellij.deps:trove4j:1.0.20200330
androidx.compose.ui:ui-geometry:1.4.0-alpha02
androidx.compose.ui:ui-graphics:1.4.0-alpha02
androidx.compose.ui:ui-text:1.4.0-alpha02
androidx.compose.ui:ui-tooling-data:1.4.0-alpha02
androidx.compose.ui:ui-tooling-preview:1.4.0-alpha02
androidx.compose.ui:ui-tooling:1.4.0-alpha02
androidx.compose.ui:ui-unit:1.4.0-alpha02
androidx.compose.ui:ui-util:1.4.0-alpha02
androidx.compose.ui:ui:1.4.0-alpha02
androidx.vectordrawable:vectordrawable-animated:1.1.0
androidx.vectordrawable:vectordrawable:1.1.0
androidx.versionedparcelable:versionedparcelable:1.1.1
androidx.databinding:viewbinding:7.3.1
androidx.viewpager2:viewpager2:1.0.0
androidx.viewpager:viewpager:1.0.0
com.fasterxml.woodstox:woodstox-core:6.2.7
androidx.work:work-runtime-ktx:2.8.0-alpha04
androidx.work:work-runtime:2.8.0-alpha04
```

</details>

> Regarding disabled functionality in the resulting APK: I can't talk for the entirety of the F-Droid userbase, but many switch to F-Droid specifically to avoid google and proprietary services/apps, so lack of such probably wouldn't be big issue.

You're probably right, the main thing that'll stop working is the weather widget. The only weather provider that works out of the box is the Deutscher Wetterdienst provider but I don't know how well they support locations outside Germany.

**Comment by ClockGen** [comment]
> I don't know why the Microsoft Auth library depends on the Surface Duo SDK but it's MIT licensed so that's all that matters.

Well, even if it's MIT licensed, that maven repo isn't allowed in F-Droid.
The list of allowed repos can be found here:
https://gitlab.com/fdroid/fdroidserver/-/blob/master/fdroidserver/scanner.py#L439
It appears right now this repo is the only hard blocker for f-droid inclusion.

**Comment by ClockGen** [comment]
I opened a draft merge request: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/12443
So far it builds but without google drive, onedrive and weather providers.

**Comment by MM2-0** [comment]
Great! How would these patches affect the future development? Do I need to make sure that I don't break anything?

**Comment by ClockGen** [comment]
Certainly not, these patches are just some makeshift solution to build the current version. Besides, they're so massive and affect so many files it'd be impossible to tiptoe around them.

It'd be greatly appreciated if you set up a separate gradle flavor for f-droid in the future, without onedrive functionality, as it relies on microsoft's maven repo. I'm no gradle expert, so I don't know how much work it'd be to create separate source sets with current structure of modules in this project.

There's still a few problems, though, microsoft maven repo in the topmost `build.gradle.kts` would still be present irrelevant of build flavor, f-droid scanner would not allow to build the app, and `settings.gradle.kts` also includes `:libs:ms-services` so it's gonna be built anyway. However, these two can be easily patched with sed during the build.

Also, f-droid relies on literal versionCode and versionName to detect updates, however they're autogenerated based on current date during the build, it would be great if you rather use static versionCode and versionName and just bump them on each release.

With a separate build flavor and static versionCode and versionName, it would be possible to enable automatic updates in f-droid.

**Comment by ClockGen** [comment]
There's two more problems:  
It seems that gdrive respective libraries have some non-free dependencies https://gitlab.com/fdroid/fdroiddata/-/merge_requests/12443#note_1243832368 so I patched them out as well.

Also, 
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/12443#note_1245273832
Is this line needed?
https://github.com/MM2-0/Kvaesitso/blob/b4f5e3f75478854b6ebeed3e178b38d862512b23/app/app/src/main/AndroidManifest.xml#L40.

**Comment by MM2-0** [comment]
I have removed the date from the version name and replaced the version code with a static one.

I have also created a new flavor, `fdroid` which is pretty much the same as the `default` flavor but it appends `-fdroid` to the version name.

**Comment by russianbot91** [comment]
In the meantime, you can add the IzzySoft F-Droid Repository to your preferred F-Droid client. It works by grabbing the releases directly from the app developer's GitHub and are signed by the developer's keys.

https://apt.izzysoft.de/fdroid/

**Comment by IzzySoft** [comment]
Just wondering aloud: it wasn't explicitly mentioned (at least I have no corresponding notes), but I take it you want me to keep the app in my repo, @MM2-0?

* It's still linked to from the readme
* you point out there's a difference (full version in my repo, F-Droid having removed the non-FOSS parts)
* it's still referred to, like in the above comment

So if that's correct, I'd mark it to be kept – otherwise it would have been due for removal already back in February :see_no_evil:

**Comment by MM2-0** [comment]
> Just wondering aloud: it wasn't explicitly mentioned (at least I have no corresponding notes), but I take it you want me to keep the app in my repo, @MM2-0?

Yes, please keep it. Your repo is probably responsible for the majority of downloads this app gets (do you collect any stats for that?). I also assume most of my users use your repo to keep their app version up to date. The F-Droid version, besides having fewer features, is also pretty outdated, so I don't recommend it to anyone. The other alternative would be my own repo (https://fdroid.mm20.de) but I don't think anyone uses that (apart from maybe a few die-hard fans).

You would do me a favor though if you could update the app icon: ![](https://raw.githubusercontent.com/MM2-0/Kvaesitso/main/assets/icons/ic_launcher.png)

**Comment by IzzySoft** [comment]
> Yes, please keep it.

Marked such (so my dupe-scanner no longer reports it for removal).

> do you collect any stats for that?

Nope, no stats beyond the technically necessary (i.e. web logs in a "ring buffer", in case something needs troubleshooting).

> but I don't think anyone uses that (apart from maybe a few die-hard fans).

:rofl: 

> You would do me a favor though if you could update the app icon: 

Maybe I could even do you a greater favor by telling you how you can do such things yourself? If you'd establish fastlane structures and then let me know about your doing so, I'd enable that on my end – and you'd be in control about description, graphics and even per-release changelogs. After all, who knows better what should be there? You can use my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688) for guidance. If you wish, I can also send you a "starter package" with what I've set up here for your app. How does that sound?

Whichever you decide: icon is replaced now (effective with the next sync).

**Comment by MM2-0** [comment]
> Maybe I could even do you a greater favor by telling you how you can do such things yourself? If you'd establish fastlane structures and then let me know about your doing so, I'd enable that on my end – and you'd be in control about description, graphics and even per-release changelogs. After all, who knows better what should be there? You can use my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688) for guidance. If you wish, I can also send you a "starter package" with what I've set up here for your app. How does that sound?

Thanks, I will make sure to add this

**Comment by IzzySoft** [comment]
Do you want my "starter package"?

**Comment by MM2-0** [comment]
Sure, why not

**Comment by IzzySoft** [comment]
OK, there you go :smiley:
