### ISSUE TITLE
Add Tidal as a music application

### ISSUE THREAD

**Issue by oliverhoerberg** [MM2-0/Kvaesitso#229]
It seems like Tidal isn't registered as a music application by the music widget. It is possible to add Tidal as a music app?

**Comment by Sir-Photch** [comment]
This is up to the Tidal Devs, for them to register their app as a music player

**Comment by MM2-0** [comment]
>This is up to the Tidal Devs, for them to register their app as a music player

In theory yes, but I think it would make sense to add a hardcoded list for popular music apps since it is impractical to contact every music app's developer and request that they add the music player filter

**Comment by MM2-0** [comment]
Added in fe06548.
