### ISSUE TITLE
Openweather position not accurate

### ISSUE THREAD

**Issue by mebitek** [MM2-0/Kvaesitso#230]
I notice that the openweather position in the weather widget is not accurate. I'm trying to set up the api key but I cannot find where I put cause I found that with api key other openweather apps works as expected

**Comment by MM2-0** [comment]
I can't imagine how using a different API key would change anything about that.

**Comment by mebitek** [comment]
yes me too, but as you see in attached image yout widget location are different.
the correct one is from geometric weather and both are using openweather provider.
correct one is from geometric weather. your location is about 25km away

![image](https://user-images.githubusercontent.com/1067967/212556320-bbabbc5d-a515-4c89-af4d-9f6b732cd861.png)

**Comment by MM2-0** [comment]
Maybe the location services do not work as expected? Have you granted the access fine location permission?

**Comment by mebitek** [comment]
Yes launcher has fine permission ans weather data are different

**Comment by mebitek** [comment]
analysing the situation with satstat I find that I get two position, one from gps and one from network. gps position is correct so I guess apps are using network position instead of gps position

**Comment by mebitek** [comment]
found a solution. installing "local NLP service" and disabling "mozilla location service" in microg all work as expected
