### ISSUE TITLE
Music Apps that aren't recognized as well (boum and vlc)

### ISSUE THREAD

**Issue by shruuub** [MM2-0/Kvaesitso#234]
Hi,
so I suppose an issue is the best way to tell you these apps, so here you go:
Boum (A client for jellyfin):
- https://apt.izzysoft.de/fdroid/index/apk/de.eindm.boum
- https://github.com/henniaufmrenni/boum
and VLC (should be known :D technically video as well, not sure bout that):
- https://f-droid.org/en/packages/org.videolan.vlc/
- https://code.videolan.org/videolan/vlc-android
Thanks a lot for the great launcher!

**Comment by eengnr** [comment]
Could you please also add these two to the list?

org.y20k.transistor
https://codeberg.org/y20k/transistor

com.angrygoat.android.squeezectrl
https://play.google.com/store/apps/details?id=com.angrygoat.android.squeezectrl

And/or maybe provide an option to manually select "media apps" with the already known ones pre-selected?

**Comment by MM2-0** [comment]
> And/or maybe provide an option to manually select "media apps" with the already known ones pre-selected?

That would be the best solution

**Comment by shruuub** [comment]
So the "planned" solution is this?

> > And/or maybe provide an option to manually select "media apps" with the already known ones pre-selected?
> 
> That would be the best solution
