### ISSUE TITLE
How to send a geo intent?

### ISSUE THREAD

**Issue by eengnr** [MM2-0/Kvaesitso#259]
I tried to send a geo intent to open a search in OsmAnd.
In Tasker, it's possible by setting the "Action" to "android.intent.action.VIEW",  "Data" to "geo:0,0?q=Test" and target "Activity":

Captured with Intent Interceptor this results in 
```
intent:0,0?q=test#Intent;scheme=geo;launchFlags=0x33000004;end 
------------ 
ACTION: android.intent.action.VIEW 
DATA: geo:0,0?q=test 
URI: intent:0,0?q=test#Intent;scheme=geo;launchFlags=0x33000004;end 
```
And this can be opened in OsmAnd.
But how can I do this on Kvæsitso?
I set "Action" to android.intent.action.VIEW as well, but I cannot add the "DATA" value and adding "Data:geo:0,0?q=${1}" in the extra key field does not work.
Everything is only added as extras to the intent:
```
intent:#Intent;launchFlags=0x3000000;S.Type%3ANone=;S.Target%3AActivity=;S.Data%3Ageo%3A0%2C0%3Fq%3D%24%7B1%7D=test;end 
------------ 
ACTION: android.intent.action.VIEW 
URI: intent:#Intent;launchFlags=0x3000000;S.Type%3ANone=;S.Target%3AActivity=;S.Data%3Ageo%3A0%2C0%3Fq%3D%24%7B1%7D=test;end 
FLAGS: 
FLAG_ACTIVITY_FORWARD_RESULT 
FLAG_ACTIVITY_PREVIOUS_IS_TOP 
EXTRAS: 
1 Typ: java.lang.String 
Key: Type:None 
Wert: 
2 Typ: java.lang.String 
Key: Target:Activity 
Wert: 
3 Typ: java.lang.String 
Key: Data:geo:0,0?q=${1} 
Wert: test 
```

Do you have any advice here?
Thanks a lot!

**Comment by MM2-0** [comment]
I thought it was possible using a web search action but it turns out it's not because the Uri is automatically prefixed with `https://`. I'll make sure to add a data field to the custom intent action.

**Comment by eengnr** [comment]
Great, thanks!
It's also necessary to URL encode the query, i.e. this should also be possible: https://developer.android.com/guide/components/intents-common

**Comment by MM2-0** [comment]
I have removed the web search action's restrictions to only support `http` and `https` URIs; all URI schemes are allowed now. You can add a web search action and set its URL template to `geo:0,0?q=${1}`.

**Comment by eengnr** [comment]
Thanks a lot! 🤩
