### ISSUE TITLE
[Bugs] Items showing up twice in search / launch on enter

### ISSUE THREAD

**Issue by Sir-Photch** [MM2-0/Kvaesitso#262]
Yay, finally the new release :)

Seems like some things did not go as smoothly:

1. Some apps show up twice upon search
2. Search-button does not switch to "Go" on keyboard. The imeOptions do not seem to get applied properly, hence causing that the launch on enter will also not work since it is bound to the "Go" action.

<details>

![double](https://user-images.githubusercontent.com/47949835/220429565-526e1dfa-a8eb-4d7d-a161-22d8e906d4d3.png)

</details>

**Comment by MM2-0** [comment]
> Some apps show up twice upon search

I have never seen that, is that reproducible?

**Comment by MM2-0** [comment]
Ah merde, I think one is from tags / custom label search.

**Comment by Sir-Photch** [comment]
Well, I don't really know, I just updated to the latest version and enabled:
1. rotation blocking
2. launch on enter

**Comment by MM2-0** [comment]
> Search-button does not switch to "Go" on keyboard. The imeOptions do not seem to get applied properly, hence causing that the launch on enter will also not work since it is bound to the "Go" action.

Works fine for me

**Comment by MM2-0** [comment]
Oh, I see, we forgot to add it to `PagerScaffold` so it only works in `PullDownScaffold`

**Comment by Sir-Photch** [comment]
Bless your intuition :D
