### ISSUE TITLE
Change font of lock screen clock

### ISSUE THREAD

**Issue by RasheedAZ** [MM2-0/Kvaesitso#268]
Thanks for making this beautiful app and making it available on F-Droid. I've been using it for a few days without any issues.

I just noticed that there's a huge difference in the look of lock screen clock's font and the home screen clock which is using Outfit.

Is there any way to make the lock screen clock same as the home screen clock?

Or change font to Outfit system-wide?

**Comment by MM2-0** [comment]
You can set the launcher's font to "system" which will use the system's default headline font (e.g. Google Sans on a Pixel device).
Besides that, I don't know whether it's possible to change the system font to Outfit. Some OEMs might allow it, and if your device is rooted, there are probably ways to do that but I don't know how.

**Comment by RasheedAZ** [comment]
OK thanks for replying :)
