### ISSUE TITLE
Disable carat on compact clock

### ISSUE THREAD

**Issue by exstntlmsnthrp** [MM2-0/Kvaesitso#269]
I cannot find a way to disable the carat on the compact clock. I don't know if this is a bug or it's intentional. But I would like to disable that. 

See image. 

![Screenshot_20230225-101415.png](https://user-images.githubusercontent.com/57594290/221365283-42998106-d9e5-4ca8-9c22-7d584f90cca5.png)

Device: Pixel 7 Pro
Android version: 13
App version: 1.22.2
App source: GitHub

**Comment by MM2-0** [comment]
It's intentional but it's a bit of a remnant of an older design. The standard clock layout doesn't have it and it's probably not necessary to indicate that you can scroll up. I can remove it if you want.

**Comment by exstntlmsnthrp** [comment]
While on the one hand, I appreciate it being there. On the other, most people using Android know to scroll up from the bottom to display something. I'd go so far as to say that a majority of people using your brilliant app don't need the reminder. 

But that's just my opinion. Do what you feel is best.
