### ISSUE TITLE
Disable date or change date format

### ISSUE THREAD

**Issue by exstntlmsnthrp** [MM2-0/Kvaesitso#270]
I cannot find a way to either change the date formatting or disable it on the home screen. See image. 

![Screenshot_20230225-102751.png](https://user-images.githubusercontent.com/57594290/221365486-f795caaf-4a82-451e-9eba-2320d7a537c8.png)

Device: Pixel 7 Pro
Android version: 13
App version: 1.22.2
App source: GitHub

**Comment by gilcu3** [comment]
I think the option to disable it was fixed last week here [d54b904](https://github.com/MM2-0/Kvaesitso/commit/d54b904c0af760d880c00c84a12407cca2fb9956) and it was previously discussed in #265

**Comment by exstntlmsnthrp** [comment]
Apologies, I didn't see #265 when I previously searched. I'm currently using version version 1.22.2 from last week. 

Maybe I'm missing something, but I've looked through all of the settings but cannot find that option to disable it.

**Comment by gilcu3** [comment]
Yes, I think that change will be in the next release.

**Comment by MM2-0** [comment]
Added in 1.23.0
