### ISSUE TITLE
No options to edit home screen?

### ISSUE THREAD

**Issue by gajang** [MM2-0/Kvaesitso#271]
Am I wrong in believing that my only option is changing the clock?

Can't find any way to add widgets or apps to the home screen, nothing in settings or documentation.

I like the feel of this launcher but if I need to swipe from home every time I want to open another up its kinda a bust,
I use my home as an easily accessible hub, so only having a clock and being forced to swipe or scroll etc isn't ideal.

Any workarounds I can do? Am I dumb?

**Comment by sandorfimarci** [comment]
If the edit button is not under widgets, press the 3 dots menu -> Settings -> Widgets -> (Here you can enable edit button, so you can add widgets from the home screen too).
Under clock when you turn on 'Fill screen height' you don't have to scroll down on the home screen every time.

I hope that's what you have looked for. In general, under settings you can customise a lot of things.

**Comment by gajang** [comment]
It's definitely close to what I'm after,

**Comment by gajang** [comment]
It's close to what I'm after, but it seems I can only have 1 extreme or another, as in its either nothing but the clock at the home screen or it's fully covered by everything, no middle ground.

Especially with how much of it feels like dead space, not being able to change the widgets background alpha, its either all wallpaper or no wallpaper. And the added row to Favorites to show that it is Favorites and the edit button is a small annoyance too.

Sorry, I know I'm nitpicking but its so close to perfect that I can't help it.
Also accidentally clicked Close instead of the drop down, I do this often it seems.

**Comment by MM2-0** [comment]
>  can only have 1 extreme or another, as in its either nothing but the clock at the home screen or it's fully covered by everything, no middle ground.

True.

> not being able to change the widgets background 

You can, settings > appearance > cards

> And the added row to Favorites to show that it is Favorites and the edit button is a small annoyance too.

You can hide that in the favorite widget's settings

**Comment by gajang** [comment]
I've spent some time with the launcher now and can definitely say everything I've brought up is a non-issue by this point, what you pointed out with cards is a big comfort, didn't realize what it did before so it seems my vernacular is still a bit slack when it comes to android stuff.

On my comment about the favorites, as I said it's a non-issue but to clarify, on the apps page, at least with my layout with 2 rows of favorites, there is a gap almost the height of a row between the apps on top and the favorites below that is mostly dead space consisting of the Favorites label on the left and the edit pen to the right, I can't find any option to hide it in the Edit Favorites menu or in the Widgets settings but its really just nitpicking.

Additionally, and unrelated to the original post sorry, I think its a new feature, the Clock having the first row of favorites, I wish there was a way to manually select at least the row that is shown, as I personally have higher value apps further up to reduce their distance from my hands resting position.

As I said, non-issue, so feel free to close this if I'm just driveling shit, I'm still fresh with android so thanks for the help.

**Comment by MM2-0** [comment]
> there is a gap almost the height of a row between the apps on top and the favorites below that is mostly dead space consisting of the Favorites label on the left and the edit pen to the right

That gap is there for the edit button and to show your pinned tags. You can hide the edit button at settings > search > favorites > show edit button. If you don't have any tags pinned to favorites this hides the entire row.

**Comment by gajang** [comment]
Oh I see now, I had no clue that lead to nested settings, thanks again for the help, I appreciate it.

Since everything I've brought up has been covered and I have no more to add, I'll close the issue here.
