### ISSUE TITLE
[Feature Request] Gesture open app

### ISSUE THREAD

**Issue by Henry-Hiles** [MM2-0/Kvaesitso#275]
Hello there! This launcher is incredible, and my new favorite by far! However, one key functionality it's missing is gesture to open app. On other launchers I have double tap to open an app, but that doesn't seem to be an option here. This feature is already implemented in many FOSS Launchers, so it shouldn't be too hard. If this could be implemented, this launcher would be truly perfect. Thank you for reading!

**Comment by MM2-0** [comment]
I have good news for you: it's already implemented (in nightlies). You can download the latest nightly from the action tab to try it.

**Comment by Henry-Hiles** [comment]
Thanks!
