### ISSUE TITLE
 Dynamic calendar support

### ISSUE THREAD

**Issue by Donnnno** [MM2-0/Kvaesitso#277]
Hi, 
The devs of Nova launcher made it very easy to include support for dynamic calendar icons :)
See:
https://github.com/teslacoil/Example_NovaTheme/blob/master/DynamicCalendarIconAPI.md

It would be a good addition to the launcher.
Thanks :^)

**Comment by MM2-0** [comment]
…it is supported? Is there an app or icon pack that doesn't work?

**Comment by Donnnno** [comment]
Ahh, I noticed that it didn't work with proton calendar and the default calendar on my device! 

I'm using Arcticons Dark, and it works in other launchers right now.

**Comment by MM2-0** [comment]
Proton Calendar + Arcticons Dark is working in my current debug build, but it is certainly possible that there is some kind of bug in the latest release. There have been quite a few changes under the hook so maybe I fixed a bug by accident since then.

**Comment by Donnnno** [comment]
Haha good to know that it's solved already then :-) 

Thanks for the quick reply
