### ISSUE TITLE
[Enhancement] Allow tagging apps for search

### ISSUE THREAD

**Issue by dugite-code** [MM2-0/Kvaesitso#28]
One of the features I used commonly in the KISS launcher that might fit with this launcher is simple text tags for apps to help when searching.

**Comment by MM2-0** [comment]
Could you please elaborate? What's the use case of this?

**Comment by dugite-code** [comment]
You could almost see this as a substitute for traditional folder organization with the advantage that apps can have more than one tag. Many apps that the names are not particularly helpful when searching of what you want, for example [markor](https://github.com/gsantner/markor) could be tagged as notes, tasks and journal. If you are using the launcher search first (as I tend to do) this allows for a dynamic and customizable experience.

Some uses I would have for this feature:

* Tagging of all the nextcloud related apps with the tag nextcloud to simplify finding all the related applications via the search. 
* Tagging all my games with "games" and also the various genres "racing", "casual", "memory", ect
* Tagging a government app recently re-released using a different account and name with the old apps name to facilitate muscle memory typing.
* Building "worksets" by tagging all my work related apps and government related apps (some of these would have both the "government" and "work" tag). I don't use these all the time so it can be difficult to remember the names of these apps causing me to scroll through a main app drawer to re-discover apps I already have.

Here is a screenshot of the Nextcloud apps tagged in the KISS launch
![image](https://user-images.githubusercontent.com/12742064/153315280-c92ffe9f-fa4c-4e02-aa51-edd4505a55af.png)

**Comment by glemco** [comment]
I guess that could be quite useful, especially for people using many FOSS apps (which can have very inventive names not easy to remember, Kvaesitso being among them), those people could tag at least the most used apps (phone, gallery, camera, etc.)
A quick and dirty solution could be to allow just renaming applications (a feature many launchers implement already), without the hassle of managing tags on their own.
Enlightened users could rename their apps as, for instance, a comma separated list of names and tags (e.g. _Markor,notes,tasks,journal_), I suppose the search algorithm would work just as expected, showing matches for any of the names/tags separated by commas.
A further development could even split and show the names after the first commas as the tags in KISS.
I'm not sure how easy would be to implement a simple app renaming, but it could be relevant for more users.

**Comment by MM2-0** [comment]
I have create a new issue to track this, #11 and #41

See #94
