### ISSUE TITLE
Dynamic colors persist on custom chosen icons

### ISSUE THREAD

**Issue by Mokura** [MM2-0/Kvaesitso#289]
Just updated to 1.23.1, and I've noticed that even if I toggle Dynamic Colors off (for Arcticons Dark), they persist on both existing customized icons, as well as the icon picker while customizing an app.  Not a dealbreaker bug, just strange.  Thanks for all your work on this excellent launcher!

![Screenshot_20230315-154903_Kvaesitso](https://user-images.githubusercontent.com/5167919/225431483-3462932c-50b3-4b34-8e25-9a47f06e57fd.png)
![Screenshot_20230315-154941_Kvaesitso](https://user-images.githubusercontent.com/5167919/225431495-8ffe1b83-1f0c-431a-b6c3-2207949d8f5f.png)
![Screenshot_20230315-155239_Kvaesitso](https://user-images.githubusercontent.com/5167919/225431498-8a99e644-e539-4ac7-80ff-fd7c650a9203.png)

**Comment by exstntlmsnthrp** [comment]
I have the same issue. I'm also using the Arcticon dark icon pack. I've tried every setting and it will not change. 

Device: Pixel 7 Pro
Android: LineageOS 20
App version: 1.23.1
App source: GitHub

**Comment by exstntlmsnthrp** [comment]
Ok. @Mokura I figured out how to disable the feature and get the icons looking like they are intended to look. In the settings, where you select the icon pack, you can enable/disable the adaptive colors. See 👇.

![Screenshot_20230316-163311_Trebuchet.png](https://user-images.githubusercontent.com/57594290/225746727-48417976-9fc1-4d77-a11e-370a4ad4e3db.png)

**Comment by exstntlmsnthrp** [comment]
Nevermind. That didn't solve it for me either. It seems that when you select a custom icon or the icon name does not match the app name exactly, then for some reason the dynamic colors persist. 

Alas, it's still a problem.

**Comment by Mokura** [comment]
That's actually what my third screenshot was for, but thank you for pointing it out.  UI can be tricky.

**Comment by exstntlmsnthrp** [comment]
Thanks. I realized that after I commented, which made me look again and see I was wrong.

**Comment by Donnnno** [comment]
Same issue here!

**Comment by MM2-0** [comment]
Closed in 8ae3d74512939da39f781259dda6fe401bcc6f64
