### ISSUE TITLE
Feature Request: Per-app icons

### ISSUE THREAD

**Issue by Mokura** [MM2-0/Kvaesitso#29]
Would it be possible to assign arbitrary icons to a single app, in addition to (or instead of) icon pack assignment?

**Comment by Mokura** [comment]
Seems I can't change an app's icon to other icons in the iconpack.  Is this still a work in progress?

**Comment by MM2-0** [comment]
This should be possible. You can use the search icon field to search for icons in any icon pack.

**Comment by Mokura** [comment]
Oh, so it does.  It just takes a moment for it to show up.  Thanks!
