### ISSUE TITLE
Replace # in tag label with emoji if tag-name starts with emoji

### ISSUE THREAD

**Issue by TimoLS9921** [MM2-0/Kvaesitso#292]
When using the favorites widget the tags take up quite some space so I decided to duplicate my tags and make an emoji version of them. Now the space the tag takes up is the width of “# 🎶” instead of “# Music”. It would be nice if it was detected that the name was just an emoji and it left the “# “ out. In the same manner this would make it possible to start the name of a tag with an emoji, to go with my “# Music@“ example tag, it would become “🎶 Music” instead.

**Comment by MM2-0** [comment]
Good idea, this would also close #180
