### ISSUE TITLE
Nice, but ...

### ISSUE THREAD

**Issue by LeOS-GSI** [MM2-0/Kvaesitso#294]
I like the concept, but 
- why only one 'card' per line ? 2 or 3 per line is absolute needed for daily use
-  weather widget is much to big
-  creation of 'folders' in favorites

**Comment by Sir-Photch** [comment]
> weather widget is much to big

There is an option to have a compact weather widget.

**Comment by LeOS-GSI** [comment]
> > weather widget is much to big
> 
> There is an option to have a compact weather widget.

Yes, but then the forecast is gone

**Comment by Sir-Photch** [comment]
That's what I call a "tradeoff"

**Comment by LeOS-GSI** [comment]
> That's what I call a "tradeoff"

For me that's a "not helpful command which no one needs and which is only wasting our time"

**Comment by russianbot91** [comment]
Maybe in addition to the default width widget card on the homescreen, the user could have the ability to have add cards with the width set to the grid size configured under Appearance > Grid and the height the same as any other widget where you can drag up or down to change the height.

I use an app called Loop Habits Tracker and use 6 columns within Kvaesitso. I'd like if I could add 12 1x1 widgets in a 6 wide x 2 high grid.
