### ISSUE TITLE
Custom per-application icons are reset upon updating the launcher

### ISSUE THREAD

**Issue by voidscuttle** [MM2-0/Kvaesitso#296]
Custom per-application icon choices set in Kvaesitso's application launcher are currently reset upon updating Kvaesitso to a new version. It would be nice if custom per-app icons set using Kvaesitso are saved across versions (and also included in the backup file). 

This occurs with the latest f-droid versions of the Kvaesitso launcher and Kvaesitso icon pack.

**Comment by MM2-0** [comment]
I think this is a one time issue, because the last update changed the way themed icons and the Kvaesitso icon pack are handled internally. Sorry for the inconvienience, but I don't think this will happen again. Or did you observe that kind of behavior in earlier version upgrades as well?

**Comment by voidscuttle** [comment]
I can't comment on prior versions as this was the first time I updated it. I'll assume you're correct and close this.
