### ISSUE TITLE
[Enhancement] Add a favorites widget

### ISSUE THREAD

**Issue by dugite-code** [MM2-0/Kvaesitso#30]
Could be nice to have a widget to display your favorite apps for when a user wishes to hide the favorites bar in the app drawer.

Optionally having it as something you could swap the fixed clock widget out for would address the more "traditional" launcher feel some users may prefer without necessarily impinging the main style of Kvaesitso.

**Comment by MM2-0** [comment]
This is planned.

**Comment by MM2-0** [comment]
Added in 0b7704c
