### ISSUE TITLE
[Feature Request] Select app activity in gestures

### ISSUE THREAD

**Issue by Havock94** [MM2-0/Kvaesitso#305]
Hi,
it would be useful if gestures could also launch app activities.
A few use cases would be:

- instead of starting Gmail, start the activity for a new email
- instead of launching the Muzei App and change background, execute the activity to skip to the next background
- instead of starting Lightroom and opening the camera, launch the activity to immediately open the camera

**Comment by MM2-0** [comment]
I think this is already be possible. You can "search" for activities by typing their component name into the search bar, like this: `com.example/com.example.ExampleActivity`. This should also work in the gesture settings search bar field when you select "launch app" as gesture action.
