### ISSUE TITLE
[Feature Request] Support for swipe gestures

### ISSUE THREAD

**Issue by PredatoryEyesLOL** [MM2-0/Kvaesitso#308]
I just discovered this launcher from a youtube video and am in the process of discovering its different features but would love if it supported swipe gestures I have been using swipe gestures for a few years now and it feels weird going back to buttons.

**Comment by MM2-0** [comment]
There are a number of different swipe gestures available, what are you missing?

**Comment by refrigerador67** [comment]
> There are a number of different swipe gestures available, what are you missing?

He's talking about the gesture navigation intrudoced in Android 10. It usually doesn't work with 3rd party launchers out of the box.

**Comment by MM2-0** [comment]
> It usually doesn't work with 3rd party launchers out of the box.

But it does?

**Comment by refrigerador67** [comment]
> > It usually doesn't work with 3rd party launchers out of the box.
> 
> But it does?

No, it doesn't, usually 3rd party launcher developers add support for quick switch for the seamless animations

**Comment by MM2-0** [comment]
> usually 3rd party launcher developers add support for quick switch for the seamless animations

For seamless animations, yes, but not for gestures in general. Gesture nav works out of the box with every launcher (except forearly versions of Android 10, where gesture nav was disabled when you were using a third party launcher).

**Comment by refrigerador67** [comment]
The issue is that it could get frustrating over time, because in some devices even messes up some things not completely related to the animations
I would recommend to add quickswitch support if you're able to, I really like this launcher

**Comment by exstntlmsnthrp** [comment]
Then that's possibly a device issue, not app issue. As @MM2-0 said, gestures already work, regardless of launcher.
