### ISSUE TITLE
Home icons row

### ISSUE THREAD

**Issue by Wrakor** [MM2-0/Kvaesitso#317]
Hey,

Saw this launcher in a video by HowToMen, and it looked great.

One thing that it was showcased and it seems to be missing after I've tried it is the bottom row of icons on the Home Screen: 
<img width="1253" alt="image" src="https://user-images.githubusercontent.com/2973191/229357961-fadf759b-b9cc-4687-bea6-191295c8b75d.png">

Having a bottom row of icons would be great, to have 1 less swipe to access those really frequent apps (like phone, camera, etc).

Is this something that exists within the current build?

**Comment by MM2-0** [comment]
Yes, you can enable it at Settings > Widgets > Clock > Favorites

**Comment by Wrakor** [comment]
I really tried to find it in settings and I couldn't! I'm only know realising that the Clock widget is the "Home" screen. 
Thanks a lot!

**Comment by MM2-0** [comment]
Yeah, settings need a restructure, it is a bit messy right now.

**Comment by Wrakor** [comment]
Fyi, I'm currently a main iPhone user with a "side" Android phone, and man, your launcher alone is tempting me to switch back. Awesome work.

Would love to see this in the Play Store sometime (with maybe a simpler name), to have a broader reach.

And maybe consider having a "Buy me a coffee" thing in your page for people to show their appreciation in a more meaningful way ;)
