### ISSUE TITLE
[Feature Request] Kvaesitso's native note widget

### ISSUE THREAD

**Issue by Terkyz** [MM2-0/Kvaesitso#319]
Among the native widgets of Kvaesitso are the music, calendar and weather widget. If possible, I would appreciate another note widget to take notes.

I know I could just add the widget from some notes app, but aesthetically it doesn't look good, and I like the style of Kvaesitso.

**Comment by MM2-0** [comment]
I guess a widget that holds a simple, editable text field would be possible, but we need to be careful here to not go beyond the scope of this application. I don't want to turn this into a full-blown note application.

**Comment by MM2-0** [comment]
It's in the latest nightly build. Feel free to try it out and give feedback.

**Comment by Terkyz** [comment]
I've been using it and it's exactly what I expected, a simple and quick note to have on hand, super useful to write things down (mainly because if I write it down in a note app, I'll forget to check it and it loses its usefulness).

Do you think it would be possible to add ToDos to this note widget? A button on the side with a check symbol that would add a ToDo line, and if you have more than one todo that would show a bar to drag the todo attached from top to bottom.

Something like what the [Carnet todo](https://i.imgur.com/b6wlx7r.png)  does.

**Comment by MM2-0** [comment]
It has (partial) markdown support, you can create a checkbox list using the following syntax:

```md
- [ ] unchecked item
- [x] checked item
```

**Comment by olbotta** [comment]
this is by far the most useful widget, expecially with markdown support i use it to quickly pin down my daily tasks and take some fast notes.

> we need to be careful here to not go beyond the scope of this application

I would like to suggest a small feature, if it fits the purpose:
adding 6 dots glyph at the left of every line to make items reorderable. Expecially for checkboxes is very useful.

something like [this](https://support.teamwork.com/desk/file/12463555/list%20view%20manually%20reorder%20task%20lists.gif)

**Comment by KorigamiK** [comment]
> this is by far the most useful widget, expecially with markdown support i use it to quickly pin down my daily tasks and take some fast notes.
> 
> > we need to be careful here to not go beyond the scope of this application
> 
> I would like to suggest a small feature, if it fits the purpose:
> adding 6 dots glyph at the left of every line to make items reorderable. Expecially for checkboxes is very useful.
> 
> something like [this](https://support.teamwork.com/desk/file/12463555/list%20view%20manually%20reorder%20task%20lists.gif)

Love this, please create a new issue to track this as well :)

**Comment by Bhardwaj10Ankit** [comment]
@MM2-0 would love if note widget somehow can support [obsidian](https://obsidian.md/) (a seriosly powerful md based notetaking tool), like taking an note in obsidian will also reflect in my obsidian an notwe taken on kvaesitso...... (i think can be achived by saving the note as md file in the obsidian vault folder)..... or please consider making an plugin for this .
