### ISSUE TITLE
[Feature Request/Enhancement] Add shortcut for opening the Kvaesitso Search

### ISSUE THREAD

**Issue by DumbledoreCalrissian** [MM2-0/Kvaesitso#322]
Hi :)

The search-focused nature of your launcher is really well done! But, there is one quirk - I need to be in the home-screen to access the search function. 
I currently use Sesame Universal Search as my primary navigation console (I do not use the app drawer or have any apps shortcuts in my home-screen). The USP of this app, for me, is that I can access it from anywhere (I create an accessibility shortcut and launch it from anywhere).
If there was a shortcut to Kvaesitso's search area, it would be perfect! It takes two swipes/actions to get to the search from an app, that would become one swipe/action.

Thank you !

**Comment by MM2-0** [comment]
You can already set it as assistant app (replace Google Assistant with it) if that helps

**Comment by Warden20** [comment]
+1 For this
With this, any gesture app could work to launche search or even tasker and macrodroid
