### ISSUE TITLE
Lag/stutter in app drawer.

### ISSUE THREAD

**Issue by winpower21** [MM2-0/Kvaesitso#327]
I am using a Motorola G72. When opening and using the app drawer, there is noticable stutter. It feels like it is running below 30hz. Occurs no matter what I set the refresh rate to. Tried auto, 60hz and 120hz. The app drawer and search still show the same issue.

**Comment by 1ndomitus** [comment]
Same. Mine is a OnePlus Nord, the original AC2001 model, Android 12.

**Comment by MM2-0** [comment]
Duplicate of #257
