### ISSUE TITLE
[Feature Request] Hiding Status Bar

### ISSUE THREAD

**Issue by 1ndomitus** [MM2-0/Kvaesitso#329]
An option to hide the status bar (time, Wi-Fi, Network Coverage etc) from the Home screen like the one implemented in Niagara Launcher would be pretty sweet!

**Comment by MM2-0** [comment]
Settings > Appearance > Hide Status Bar

**Comment by 1ndomitus** [comment]
Do forgive my bird-brained ignorance.

**Comment by yaomtc** [comment]
This option is no longer there. Is it not possible on Android 14? What about changing the status bar icons from white to black, or giving it a background

**Comment by MM2-0** [comment]
It has been moved to settings > home screen
