### ISSUE TITLE
[Feature request] Allow user to add search engines

### ISSUE THREAD

**Issue by silverwings15** [MM2-0/Kvaesitso#34]
Hi, just found out about this project and i'm loving it so far, very refreshing take on the launcher style. My small suggestion is to have the ability to add custom search engines, would be very useful to not have to go through google for starters. Thank you for reading!

Off-topic p.s.: This may be subjective but when you clear the search bar, i feel like the animation for the application list to return is still just a too slow. Probably because i'm coming from Nova which is instant (no animation), but maybe being able to tweak the value of the animation duration could be considered as well. Would love to hear what you think.

**Comment by MM2-0** [comment]
Hi, glad you like it.

> My small suggestion is to have the ability to add custom search engines, would be very useful to not have to go through google for starters.

This is already possible! Settings > Search > Websearches

> This may be subjective but when you clear the search bar, i feel like the animation for the application list to return is still just a too slow. Probably because i'm coming from Nova which is instant (no animation), but maybe being able to tweak the value of the animation duration could be considered as well. Would love to hear what you think.

I don't know, feels pretty instant to me. I can try to tweak it a little bit but I don't think speeding it up will have a significant impact on the perceived performance.

**Comment by silverwings15** [comment]
oh silly me, i thought it was just a toggle and didn't realize i could click on it. awesome!

> I don't know, feels pretty instant to me. I can try to tweak it a little bit but I don't think speeding it up will have a significant impact on the perceived performance.

totally understandable, very minor thing for me anyway. thank you again for the prompt response!
