### ISSUE TITLE
Android 10+ gesture navigation fix

### ISSUE THREAD

**Issue by humzasadiq** [MM2-0/Kvaesitso#341]
On android 10+ there is a bottom bar gesture nav like in IOS. Back and home gestures works great but the recents menu gesture is buggy. There is an existing app on github named "Quickswitch" that can fix this. Please just add the support for it😷
Only rooted apps will support this fix tho...

If there is a way around for non rooted that would be great because android 10+ doesn't let 3rd party launchers to support its gesture nav fully.

**Comment by MM2-0** [comment]
See https://github.com/MM2-0/Kvaesitso/issues/5#issuecomment-1139111408
