### ISSUE TITLE
Muzei Support

### ISSUE THREAD

**Issue by lessgoo00** [MM2-0/Kvaesitso#35]

**Comment by MM2-0** [comment]
Sorry, I only understand half of the words you have written, could you please elaborate?

**Comment by BrightDV** [comment]
It's *maybe* about the support for the wallpaper's gestures.

> Simply double touch the wallpaper or open the Muzei app to enjoy and explore the artwork in its full glory. 

Said on its [GitHub repo](https://github.com/muzei/muzei).
Muzei is an app which provides "famous works of art" as wallpaper.
