### ISSUE TITLE
Music Widget does not recognize Tidal app

### ISSUE THREAD

**Issue by johndoorzon** [MM2-0/Kvaesitso#354]
When I play music via the Tidal app, this is not displayed in the music widget like my other  music apps (for example Spotify or Omnia)

Version 1.24.1, Google Pixel 7 Pro

**Comment by exstntlmsnthrp** [comment]
Have you tried checking the Media Control Integration?

Tap edit widget > 

![Screenshot_20230421-141805.png](https://user-images.githubusercontent.com/57594290/233707374-f1e02397-ce33-4574-a704-55b23848d034.png)

Then tap the edit button for music >

![Screenshot_20230421-141749.png](https://user-images.githubusercontent.com/57594290/233707497-b515d7d8-71b0-4b62-8d31-039954854365.png)

Next, tap Media Control Integration at the bottom >

![Screenshot_20230421-141619.png](https://user-images.githubusercontent.com/57594290/233707647-eadcf29e-2efe-483b-aca6-ab6ff8ff2822.png)


From there, scroll down and make sure that Tidal app is selected.

Hope that solves the problem.

**Comment by johndoorzon** [comment]
Hmm, at first the app list didn't unfold, so I must have overlooked it. 
It works now, so I will close this issue. Thanks for the help!
