### ISSUE TITLE
I don't need apps on my home screen. Frequent apps appear at the home screen. 

### ISSUE THREAD

**Issue by akashshyam** [MM2-0/Kvaesitso#355]
There should be an option of whether we want to show frequent apps or any apps on the home screen or not. 
Not an issue but it will make the user experience better because I have been removing the apps one by one everytime an apps gets into frequent apps list which will make the app to appear at the homescreen.

**Comment by exstntlmsnthrp** [comment]
This already exists in the app. As you can see, I do not have apps on my home screen either. 

I will post photos in a moment. Problems with uploading to GitHub.
