### ISSUE TITLE
localization:Chinese

### ISSUE THREAD

**Issue by labrusca** [MM2-0/Kvaesitso#36]
I’m interesting in this APP,and maybe I can help you guys to translate to Chinese.
could I be a contributor or reviewer?

**Comment by labrusca** [comment]
@MM2-0 Registration done. I'm ready for this, how can I start doing translate into chinese?

**Comment by MM2-0** [comment]
There are two components, `i18n` and `units` (as described [here](https://github.com/MM2-0/Kvaesitso/blob/main/i18n/readme.md)). I'd recommend you start with i18n. First step ist to add your language to one of the components (you shouldn't need any special permissions for that and available languages are synced between the two components) and after that you can start translating. If you need further assistance, let me know.
