### ISSUE TITLE
App is listed as "tracking and reporting" by common foss repository..

### ISSUE THREAD

**Issue by texturesplunky** [MM2-0/Kvaesitso#363]
Hello, please pardon the silly question as I have much to learn..

On izzydroid they list Kvaesitso app as 

"Tracking: The application tracks and reports your activity to somewhere.."

I dont see this listed anywhere else, is there any way I could ask for a brief, even basic explanation? All detials and any reply is appreciated immensely!

Great work, very appealing launcher!

**Comment by exstntlmsnthrp** [comment]
I'm just another user, so I'm not sure what the developer will respond. 

However, according to Exodus Privacy analysis, there are no known trackers in this app. My guess is, if you use one of the integrations (ex. Google) the dev cannot control if Google tracks you. But that is just an educated guess.

**Comment by MM2-0** [comment]
Possibly the Microsoft SDK. But I have now idea. I'm not responsible for the IzzyOnDroid repo so I don't know.

**Comment by texturesplunky** [comment]
> Possibly the Microsoft SDK. But I have now idea. I'm not responsible for the IzzyOnDroid repo so I don't know.

Greetings, thanks for the reply. I love the launcher.

Do I understand correctly that the app doesnt do what i quoted in my original post? Should I use the fdroid repo, or is this nothing to be concerned about? 

Thats my last question on this, just trying to understand the basics on this. Ty again!

**Comment by amoshydra** [comment]
This is what izzy mentions in their page:

> Ads & Analytics:
> OpenTelemetry JavaⓉ (Mobile Analytics) 
> the merging of OpenCensus and OpenTracing into a single project; high-quality, ubiquitous, and portable telemetry to enable effective observability. Create and collect telemetry data from your services and software, then forward them to a variety of analysis tools.
>
> - https://android.izzysoft.de/repo/apk/de.mm20.launcher2.release

**Comment by MM2-0** [comment]
I have removed the Microsoft SDK from the app (it was already inactive for several versions), now it's no longer listed as tracking.
