### ISSUE TITLE
App drawer laggy

### ISSUE THREAD

**Issue by vascontuin** [MM2-0/Kvaesitso#364]
It's like there's only 15fps it's kinda weird and bad, but I would love using it on a daily, I hope it gets better (me writing a review as if I was on play store lol)

**Comment by MM2-0** [comment]
Which device / version are you using? Most performance issues should have been resolved in 1.24.2

**Comment by MM2-0** [comment]
Also duplicate of #257

**Comment by vascontuin** [comment]
> Which device / version are you using? Most performance issues should have been resolved in 1.24.2

I'm using the 1.24.2 version, phone is Samsung's A32 android 13
