### ISSUE TITLE
Render size discrepancy between themed and unthemend icons

### ISSUE THREAD

**Issue by Sir-Photch** [MM2-0/Kvaesitso#366]
Steps to reproduce:

Install and enable Lawnicons.
Switch between themed and unthemed icons.

The screenshots should make the issue clearer:

<details>
<summary>Themed, the icons appear small</summary>

![Screenshot_20230422-160745](https://user-images.githubusercontent.com/47949835/234483533-007594b5-4b23-4597-be1e-99c41008cad1.png)

</details>
<details>
<summary>Unthemed, the icons appear big</summary>

![Screenshot_20230422-160753](https://user-images.githubusercontent.com/47949835/234483541-529a26e0-d260-45fb-b632-99c702c20008.png)

</details>

**Comment by jamal2362** [comment]
I can confirm that the icons are displayed too small.

Pixel Launcher / Nothing Launcher:
![photo_2023-04-29_11-58-36](https://user-images.githubusercontent.com/15986930/235296834-b5470181-57ea-4dcf-9965-a3f706950d5a.jpg)

Kvaesitso:
![photo_2023-04-29_11-58-41](https://user-images.githubusercontent.com/15986930/235296841-0cdd61d7-b319-46c2-b113-32b42a49641f.jpg)

**Comment by exstntlmsnthrp** [comment]
On the one hand, I agree. Default icons in Kvaesitso are slightly smaller than the default launcher (Pixel launcher in my case). However, all you need to do is adjust the icon size in Kvaesitso settings. 

Settings > Grid & icons

![Screenshot_20230429-140920.png](https://user-images.githubusercontent.com/57594290/235317782-d0dab2c0-305b-47fc-a143-292a2043f038.png)

**Comment by jamal2362** [comment]
> On the one hand, I agree. Default icons in Kvaesitso are slightly smaller than the default launcher (Pixel launcher in my case). However, all you need to do is adjust the icon size in Kvaesitso settings.
> 
> Settings > Grid & icons
> 
> ![Screenshot_20230429-140920.png](https://user-images.githubusercontent.com/57594290/235317782-d0dab2c0-305b-47fc-a143-292a2043f038.png)

We are talking about the symbols inside the circle

**Comment by MM2-0** [comment]
Closed in 29620e69cd37a8fde2a7618517f29ffa59ef12aa

**Comment by Fxsch** [comment]
I don't think the fix worked. The icons from Kvæsitso Icons are now too big (they were fine before) but Lawnicons icons look the same size to me. I have version 1.26.4 installed btw.

Here's a screenshot with Lawnicons (notice how Finamp, which isn't part of the icon pack, is noticebly larger than the other icons):
![Screenshot_20230714-163709_Kvaesitso](https://github.com/MM2-0/Kvaesitso/assets/77849217/ec6ea359-0c19-4548-a785-d6c453204483)
