### ISSUE TITLE
[Improvement suggestion] Respect Android notification dot policy

### ISSUE THREAD

**Issue by FrameXX** [MM2-0/Kvaesitso#368]
AFAIK since Android 8+ every notification channel of every app can be set to show or to not show notification dots in launcher.
![Screenshot_20230426-105405_Settings](https://user-images.githubusercontent.com/56247804/234524883-5ddd78e3-6f28-4ff7-90c7-eb8102620f28.png)
Most of the third party launchers based on launcher3 do respect this policy, however Kvaesitso doesn't seem to respect it and shows the notification no matter what settings the channel has. I think it would be reasonable to make Kvaesitso also respect this policy.

**Comment by MM2-0** [comment]
Added in 1.25.0
