### ISSUE TITLE
[Bug] Glitched keyboard closing when scrolling down from search 

### ISSUE THREAD

**Issue by EdwinRodger** [MM2-0/Kvaesitso#370]
https://user-images.githubusercontent.com/92982808/234880339-cc5030d7-dd7f-4c1e-b5ff-1545a4fe563b.mp4

Device Name - Redmi Note 8 Pro
MIUI Version - 12.5.10 Stable
Android Version - 11

<details>

<summary>Logs</summary>

[kvaesitso-log-2023-04-27-191444.txt](https://github.com/MM2-0/Kvaesitso/files/11344200/kvaesitso-log-2023-04-27-191444.txt)

Device: begoniain
SDK version: 30
====================================
04-27 19:03:03.483 12792 12792 W Activity: Slow Operation: Activity de.mm20.launcher2.release/de.mm20.launcher2.ui.launcher.LauncherActivity onResume took 1317ms
04-27 19:03:03.501 12792 12792 W Looper  : PerfMonitor longMsg : seq=3 plan=19:03:02.010 late=110ms wall=1381ms running=496ms runnable=15ms io=749ms h=android.app.ActivityThread$H w=159 procState=2
04-27 19:03:03.502 12792 12792 W Looper  : PerfMonitor looperActivity : package=de.mm20.launcher2.release/de.mm20.launcher2.ui.launcher.LauncherActivity time=0ms latency=1492ms running=0ms  procState=2 ClientTransaction{ callbacks=[android.app.servertransaction.TopResumedActivityChangeItem] } historyMsgCount=3 (msgIndex=2 wall=99ms seq=2 running=42ms runnable=1ms io=44ms late=12ms h=android.app.ActivityThread$H w=110) (msgIndex=3 wall=1381ms seq=3 running=496ms runnable=15ms io=749ms late=110ms h=android.app.ActivityThread$H w=159)
04-27 19:03:03.555 12792 12792 W Looper  : PerfMonitor doFrame : time=53ms vsyncFrame=0 latency=1385ms procState=2 historyMsgCount=3 (msgIndex=1 wall=99ms seq=2 running=42ms runnable=1ms io=44ms late=12ms h=android.app.ActivityThread$H w=110) (msgIndex=2 wall=1381ms seq=3 running=496ms runnable=15ms io=749ms late=110ms h=android.app.ActivityThread$H w=159)
04-27 19:03:36.517 12792 12859 W BpBinder: Slow Binder: BpBinder transact took 262 ms, interface=android.app.IActivityManager, code=22 oneway=false
04-27 19:03:37.487 12792 12995 W BpBinder: Slow Binder: BpBinder transact took 254 ms, interface=android.media.IMediaMetadataRetriever, code=5 oneway=false
04-27 19:03:37.586 12792 12996 W BpBinder: Slow Binder: BpBinder transact took 352 ms, interface=android.media.IMediaMetadataRetriever, code=5 oneway=false
04-27 19:03:37.684 12792 12825 W BpBinder: Slow Binder: BpBinder transact took 450 ms, interface=android.media.IMediaMetadataRetriever, code=5 oneway=false
04-27 19:03:37.797 12792 12835 W BpBinder: Slow Binder: BpBinder transact took 562 ms, interface=android.media.IMediaMetadataRetriever, code=5 oneway=false
04-27 19:03:37.914 12792 12928 W BpBinder: Slow Binder: BpBinder transact took 678 ms, interface=android.media.IMediaMetadataRetriever, code=5 oneway=false
04-27 19:03:38.018 12792 12966 W BpBinder: Slow Binder: BpBinder transact took 781 ms, interface=android.media.IMediaMetadataRetriever, code=5 oneway=false
04-27 19:03:38.131 12792 12975 W BpBinder: Slow Binder: BpBinder transact took 891 ms, interface=android.media.IMediaMetadataRetriever, code=5 oneway=false
04-27 19:03:41.214 12792 12856 W BpBinder: Slow Binder: BpBinder transact took 226 ms, interface=android.media.IMediaMetadataRetriever, code=5 oneway=false
04-27 19:05:42.277 15175 15175 W Activity: Slow Operation: Activity de.mm20.launcher2.release/de.mm20.launcher2.ui.launcher.LauncherActivity onResume took 508ms
04-27 19:05:42.299 15175 15175 W Looper  : PerfMonitor looperActivity : package=de.mm20.launcher2.release/de.mm20.launcher2.ui.launcher.LauncherActivity time=0ms latency=698ms running=0ms  procState=2 ClientTransaction{ callbacks=[android.app.servertransaction.TopResumedActivityChangeItem] } historyMsgCount=3 (msgIndex=2 wall=103ms seq=2 running=48ms runnable=2ms io=40ms late=3ms h=android.app.ActivityThread$H w=110) (msgIndex=3 wall=593ms seq=3 running=438ms runnable=6ms io=49ms late=105ms h=android.app.ActivityThread$H w=159)
04-27 19:05:42.347 15175 15175 W Looper  : PerfMonitor doFrame : time=48ms vsyncFrame=0 latency=593ms procState=2 historyMsgCount=2 (msgIndex=1 wall=593ms seq=3 running=438ms runnable=6ms io=49ms late=105ms h=android.app.ActivityThread$H w=159)
--------- beginning of main
04-27 19:07:12.406 15175 15188 I uncher2.releas: Background concurrent copying GC freed 372671(10MB) AllocSpace objects, 0(0B) LOS objects, 49% free, 9884KB/19MB, paused 232us total 201.782ms
04-27 19:08:20.494 15175 15188 I uncher2.releas: Background concurrent copying GC freed 360851(9861KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 9878KB/19MB, paused 374us total 347.522ms
04-27 19:09:37.083 15175 15175 W IInputConnectionWrapper: getTextAfterCursor on inactive InputConnection
04-27 19:09:37.100 15175 15175 W IInputConnectionWrapper: getSelectedText on inactive InputConnection
04-27 19:09:37.160 15175 15175 W IInputConnectionWrapper: getTextBeforeCursor on inactive InputConnection
04-27 19:09:37.209 15175 15175 W IInputConnectionWrapper: getTextAfterCursor on inactive InputConnection
04-27 19:09:37.239 15175 15175 W IInputConnectionWrapper: getSelectedText on inactive InputConnection
04-27 19:09:37.287 15175 15175 W IInputConnectionWrapper: getTextBeforeCursor on inactive InputConnection
04-27 19:09:37.332 15175 15175 W IInputConnectionWrapper: getTextAfterCursor on inactive InputConnection
04-27 19:09:37.358 15175 15175 W IInputConnectionWrapper: getSelectedText on inactive InputConnection
04-27 19:09:37.409 15175 15175 W IInputConnectionWrapper: getTextBeforeCursor on inactive InputConnection
04-27 19:09:37.460 15175 15175 W IInputConnectionWrapper: getTextAfterCursor on inactive InputConnection
04-27 19:09:37.486 15175 15175 W IInputConnectionWrapper: getSelectedText on inactive InputConnection
04-27 19:09:38.504 15175 15175 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
04-27 19:09:38.518 15175 15175 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
04-27 19:09:38.521 15175 15175 I chatty  : uid=10504(de.mm20.launcher2.release) identical 1 line
04-27 19:09:38.524 15175 15175 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
04-27 19:09:38.624 15175 15175 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
04-27 19:09:38.626 15175 15175 I chatty  : uid=10504(de.mm20.launcher2.release) identical 2 lines
04-27 19:09:38.627 15175 15175 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
04-27 19:09:38.698 15175 15175 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
04-27 19:09:38.705 15175 15175 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
04-27 19:09:38.716 15175 15175 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
04-27 19:09:38.717 15175 15175 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
04-27 19:09:38.791 15175 15175 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
04-27 19:09:38.792 15175 15175 I chatty  : uid=10504(de.mm20.launcher2.release) identical 1 line
04-27 19:09:38.797 15175 15175 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
04-27 19:09:39.003 15175 15175 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
04-27 19:09:39.007 15175 15175 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
04-27 19:09:39.013 15175 15217 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
04-27 19:09:39.082 15175 15188 I uncher2.releas: Background concurrent copying GC freed 367533(10MB) AllocSpace objects, 0(0B) LOS objects, 49% free, 11MB/22MB, paused 42us total 106.346ms
04-27 19:09:44.622 15175 15175 V PhoneWindow: DecorView setVisiblity: visibility = 0, Parent = android.view.ViewRootImpl@25e2165, this = DecorView@95f2e3a[LauncherActivity]
04-27 19:09:45.403 15175 15175 V PhoneWindow: DecorView setVisiblity: visibility = 4, Parent = android.view.ViewRootImpl@25e2165, this = DecorView@95f2e3a[LauncherActivity]
04-27 19:09:45.422 15175 15211 I GED     : ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 27, oppidx_max 27, oppidx_min 0
04-27 19:12:14.371 15175 15175 V PhoneWindow: DecorView setVisiblity: visibility = 0, Parent = android.view.ViewRootImpl@25e2165, this = DecorView@95f2e3a[LauncherActivity]
04-27 19:12:14.372 15175 15175 V PhoneWindow: DecorView setVisiblity: visibility = 0, Parent = android.view.ViewRootImpl@25e2165, this = DecorView@95f2e3a[LauncherActivity]
04-27 19:12:17.192 15175 15188 I uncher2.releas: Background concurrent copying GC freed 389032(10MB) AllocSpace objects, 0(0B) LOS objects, 49% free, 11MB/23MB, paused 919us total 108.791ms
04-27 19:12:18.229 15175 15188 I uncher2.releas: Background young concurrent copying GC freed 400172(11MB) AllocSpace objects, 0(0B) LOS objects, 47% free, 12MB/23MB, paused 57us total 102.356ms
04-27 19:12:18.493 15175 15175 V PhoneWindow: DecorView setVisiblity: visibility = 4, Parent = android.view.ViewRootImpl@25e2165, this = DecorView@95f2e3a[LauncherActivity]
04-27 19:12:18.500 15175 15211 I GED     : ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 27, oppidx_max 27, oppidx_min 0
04-27 19:13:23.148 15175 15175 V PhoneWindow: DecorView setVisiblity: visibility = 0, Parent = android.view.ViewRootImpl@25e2165, this = DecorView@95f2e3a[LauncherActivity]
04-27 19:13:23.149 15175 15175 V PhoneWindow: DecorView setVisiblity: visibility = 0, Parent = android.view.ViewRootImpl@25e2165, this = DecorView@95f2e3a[LauncherActivity]
04-27 19:13:23.932 15175 15188 I uncher2.releas: Background concurrent copying GC freed 356985(9944KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 10MB/21MB, paused 54us total 136.094ms
04-27 19:13:25.013 15175 15211 I GED     : ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 27, oppidx_max 27, oppidx_min 0
04-27 19:13:25.049 15175 15175 V PhoneWindow: DecorView setVisiblity: visibility = 4, Parent = android.view.ViewRootImpl@25e2165, this = DecorView@95f2e3a[LauncherActivity]
04-27 19:13:39.122 15175 15175 V PhoneWindow: DecorView setVisiblity: visibility = 0, Parent = android.view.ViewRootImpl@25e2165, this = DecorView@95f2e3a[LauncherActivity]
04-27 19:13:39.123 15175 15175 V PhoneWindow: DecorView setVisiblity: visibility = 0, Parent = android.view.ViewRootImpl@25e2165, this = DecorView@95f2e3a[LauncherActivity]
04-27 19:13:40.855 15175 15175 D ViewRootImpl[Pop-up window]: hardware acceleration = true , fakeHwAccelerated = false, sRendererDisabled = false, forceHwAccelerated = false, sSystemRendererDisabled = false
04-27 19:13:40.860 15175 15175 I InputTransport: Create ARC handle: 0xb4000073b3ade620
04-27 19:13:41.516 15175 15175 I Timeline: Timeline: Activity_launch_request time:117707117
04-27 19:13:41.559 15175 17344 D libMEOW : applied 1 plugins for [de.mm20.launcher2.release]:
04-27 19:13:41.559 15175 17344 D libMEOW :   plugin 1: [libMEOW_gift.so]:
04-27 19:13:41.577 15175 15175 D DecorView[]: getWindowModeFromSystem  windowmode is 1
04-27 19:13:41.577 15175 15175 D DecorView: createDecorCaptionView windowingMode:1 mWindowMode 1 isFullscreen: true
04-27 19:13:41.583 15175 15175 V PhoneWindow: DecorView setVisiblity: visibility = 4, Parent = null, this = DecorView@ea711c8[]
04-27 19:13:41.585 15175 15175 D ViewRootImpl[SettingsActivity]: hardware acceleration = true , fakeHwAccelerated = false, sRendererDisabled = false, forceHwAccelerated = false, sSystemRendererDisabled = false
04-27 19:13:41.590 15175 15175 I InputTransport: Create ARC handle: 0xb4000073b3bc70e0
04-27 19:13:41.591 15175 15175 V PhoneWindow: DecorView setVisiblity: visibility = 0, Parent = android.view.ViewRootImpl@2da9a47, this = DecorView@ea711c8[SettingsActivity]
04-27 19:13:41.714 15175 15211 D OpenGLRenderer: endAllActiveAnimators on 0xb40000734a0ea000 (UnprojectedRipple) with handle 0xb4000073b3aff820
04-27 19:13:41.715 15175 15175 D View    : [Warning] assignParent to null: this = androidx.compose.ui.window.PopupLayout{2023965 V.E...... ......ID 0,0-347,440 #1020002 android:id/content aid=1073741825}
04-27 19:13:41.716 15175 15175 I InputTransport: Destroy ARC handle: 0xb4000073b3ade620
04-27 19:13:42.027 15175 15175 V PhoneWindow: DecorView setVisiblity: visibility = 4, Parent = android.view.ViewRootImpl@25e2165, this = DecorView@95f2e3a[LauncherActivity]
04-27 19:13:45.933 15175 15188 I uncher2.releas: Background concurrent copying GC freed 309666(9166KB) AllocSpace objects, 1(24KB) LOS objects, 49% free, 12MB/24MB, paused 69us total 197.450ms
null

</details>

**Comment by EdwinRodger** [comment]
This bug was happening on old version. I just updated the app to it's latest version and the bad keyboard animation is still happening although not quite often and now the keyboard open and close only one time.

1. I scroll down
2. Keyboard closes as expected
3. Keyboard opens
4. Keyboard closes
5. App work as normal

**Comment by Wrakor** [comment]
Came here to report exactly this. Happening on my OnePlus as well.

https://user-images.githubusercontent.com/2973191/235937854-117450cf-6f28-4e50-b27a-4a7ddf3a1378.mp4

**Comment by EdwinRodger** [comment]
Yep couldn't reproduce  the issue myself, on redmi device at least.
I think it got fixed.
Closing the issue.
