### ISSUE TITLE
Kvæsitso searches with the wrong app

### ISSUE THREAD

**Issue by rahaaatul** [MM2-0/Kvaesitso#373]
I have Google app installed. When I try to search something with the google option, it prompts me to select a browser, even though the google search app is available.

https://user-images.githubusercontent.com/86149861/235140284-e20b0433-3bd1-442f-8d3b-c3574a097405.mp4

 In most other app it's default to search with the Google app. So, In kvaesitso, is it a bug or a feature?

**Comment by exstntlmsnthrp** [comment]
Depending on what phone you have and what version of Android you use, that should be in your system settings. In Android 12 and 13 (I don't remember older versions) it should be Settings > Apps > Default apps. 

In your video, you open the Chrome browser not the Google app. Which one do you want to open?

**Comment by rahaaatul** [comment]
> Depending on what phone you have and what version of Android you use, that should be in your system settings. In Android 12 and 13 (I don't remember older versions) it should be Settings > Apps > Default apps.

I'm on Android 11.

> In your video, you open the Chrome browser not the Google app. Which one do you want to open?

I'm talking about the Google app. But it doesn't show up in the prompt, only browsers.

**Comment by exstntlmsnthrp** [comment]
I think Android 11 is similar to 12, from what I read, so your settings should likely be similar.

Did you check your settings for default apps? What is the default for digital assistant? 

I don't have the Google app on my phone, so I can't check.

**Comment by rahaaatul** [comment]
> I think Android 11 is similar to 12, from what I read, so your settings should likely be similar.

![Screenshot_2023_0429_085349](https://user-images.githubusercontent.com/86149861/235280341-31af0a2f-6d6c-4036-9058-8d5ef7b54df6.jpg)


> Did you check your settings for default apps? What is the default for digital assistant?

It's Google.

> I don't have the Google app on my phone, so I can't check.

I may have found a way, but it's not working. Can you help, please?

https://user-images.githubusercontent.com/86149861/235280703-30bacc6f-8940-4dea-95c3-f75b544c99c2.mp4

**Comment by MM2-0** [comment]
> I have Google app installed. When I try to search something with the google option, it prompts me to select a browser, even though the google search app is available.

Confirmed. Apparently the Google app doesn't handle google.com links.

As a workaround, you can create a custom intent action with
- action: `android.intent.action.WEB_SEARCH`
- extra key: `query`

**Comment by rahaaatul** [comment]
> Confirmed. Apparently the Google app doesn't handle google.com links. 
> As a workaround, you can create a custom intent action with
> 
> * action: `android.intent.action.WEB_SEARCH`
> * extra key: `query`

This workaround works perfectly. Thank you @MM2-0 , you're the best!
