### ISSUE TITLE
[Feature request] Option to reverse drawer direction

### ISSUE THREAD

**Issue by luimu64** [MM2-0/Kvaesitso#39]
Currently the search results and drawer in general is bottom to top with most relevant results and favorites being at the very top. This is fine in general but with big screen it becomes major inconvenience. I have screen of 6.67 inches and I can only touch up to half of the screen comfortably, you can probably imagine how annoying it becomes when you would have to change your hand position every time you do something like opening app which is quite common task.

My suggestion to fix this is quite simple in theory but may be hard to implement, basically I would suggest just reversing the whole drawer structure to be top to bottom with bottom having the most relevant results. For consistency the search bar should be at the bottom too just above the keyboard.

This would make it less unique since all the other search based launchers do it this way, but the accessibility for bigger phone users would greatly increase.

**Comment by labrusca** [comment]
I have some idea:
1. The pull down gesture to open Notification bar.
2. Move the search bar to the bottom, and move the search bar to the top when you focus/open the search bar.

**Comment by luimu64** [comment]
The pull down gesture would make perfect sense to open it if the animation brings it down from above the screen to keyboard level instead of below the screen. Sorting would go from bottom left or bottom right to top nearest result being beside the search bar like it is now. I don't get why having gap is a problem, the gap will just fill all the space above found results.

**Comment by MM2-0** [comment]
> I don't get why having gap is a problem, the gap will just fill all the space above found results.

I meant the gap at the end of the grid (because there are usually bot enough items to fill the last grid row. But I guess that gap would just be moved to the top right, so not a big deal after all.

I think it is possible to implement this, but I'd like to keep the current layout as an option as well so the challenge is to make both layouts work at the same time. Should be doable though.

**Comment by MM2-0** [comment]
Added in 1.10.0
