### ISSUE TITLE
[ENHANCEMENT] Customise Grid Size

### ISSUE THREAD

**Issue by 0xlne** [MM2-0/Kvaesitso#4]
As a user of a large screen device, I'd like to maximize the use of my screen realestate & would thus appreciate the consideration of options to customize the grid size of the app drawer - number of icons per row/column or number of rows/columns, size of the icons.

**Comment by MM2-0** [comment]
Adjustable grid column count has been implemented in 185e54b .
I don't think I will implement any options for icon sizes for now.
