### ISSUE TITLE
[Feature request] Add option to change the clock position 

### ISSUE THREAD

**Issue by Hmt-9** [MM2-0/Kvaesitso#403]
Add option to change the position of the clock (at the bottom as it is or at the top)

**Comment by exstntlmsnthrp** [comment]
This already exists. 

Found here:
![Screenshot_20230524-130127.png](https://github.com/MM2-0/Kvaesitso/assets/57594290/aeab3696-e314-4325-b2da-b53e0c38a8b3)




Bottom:
![Screenshot_20230524-125854.png](https://github.com/MM2-0/Kvaesitso/assets/57594290/287a4a8f-8d51-4d8d-8b78-6be32e514443)




Top:
![Screenshot_20230524-125949.png](https://github.com/MM2-0/Kvaesitso/assets/57594290/bd7f3c1a-482b-442c-bc05-f5555a06eb1e)

**Comment by DestroyerV** [comment]
Feature added in version 1.28
