### ISSUE TITLE
[Feature Request] change app names

### ISSUE THREAD

**Issue by HerrHellmus** [MM2-0/Kvaesitso#41]
I'd like to be able to change the name of apps as they appear in the drawer. For instance, I use Open Camera, but I'd like to be able to rename it to "Camera". Similarly, I would like to be able to rename Material-Files to "My Files".

**Comment by MM2-0** [comment]
I think this is kinda related to #11 and #28. I might add this later.

**Comment by MM2-0** [comment]
I have create a new issue to track this, #11 and #28

See #94
