### ISSUE TITLE
Integrate Simple Calendar to the Calendar Widget

### ISSUE THREAD

**Issue by yant0** [MM2-0/Kvaesitso#411]
Hi

Im using the [Simple Mobile Tools Calendar](https://github.com/SimpleMobileTools/Simple-Calendar) and it doesnt show the events from that app. Thank you

**Comment by exstntlmsnthrp** [comment]
I also use Simple Calendar Pro. However, I have no problems. Are you using a local calendar in the app that is only on your phone? Or are you using a calendar synced from another service?

If it's the latter, the calendar widget uses the settings from Android to sync those, not the app. Have you enabled calendar permissions for Kvaesitso?

**Comment by yant0** [comment]
I have the calendar on local device. I tried syncing a gmail calendar and it works fine

**Comment by yant0** [comment]
> As far as I understand, if it's a local only event (i.e. only in the calendar app and not synced), it does not get picked up by the widget.

How do i get around this without using a service? (Gmail/davx)

**Comment by MM2-0** [comment]
> > As far as I understand, if it's a local only event (i.e. only in the calendar app and not synced), it does not get picked up by the widget.
> 
> How do i get around this without using a service? (Gmail/davx)

Use install an offline calendar provider, like [Etar](https://www.f-droid.org/packages/ws.xsoh.etar/) or [Offline Calendar](https://www.f-droid.org/packages/org.sufficientlysecure.localcalendar/) (no longer maintained) to create an offline calendar. You can then add that local calendar to Simple Calendar.

**Comment by exstntlmsnthrp** [comment]
> Install an offline calendar provider, like [Etar](https://www.f-droid.org/packages/ws.xsoh.etar/) (which is a full blown calendar app but has the capability to create offline calendars) or [Offline Calendar](https://www.f-droid.org/packages/org.sufficientlysecure.localcalendar/) (simpler but no longer maintained) to create an offline calendar. You can then add that local calendar to Simple Calendar.

So are you saying that Simple Calendar is not a full blown calendar app? To my understanding (which I admit may be wrong), it also can create offline calendars. Albeit, when I tried it did not sync with the widget.
