### ISSUE TITLE
Transparent icon shape / background

### ISSUE THREAD

**Issue by TK-NC** [MM2-0/Kvaesitso#412]
Hello!

Before the 1.25 update I was a Lawnchair Dev user. I'm really enjoying this launcher, but there's one thing I miss from Lawnchair: transparent / no icon shapes.

Lawnchair
![Screenshot_20230529_101305_Lawnchair (Debug)](https://github.com/MM2-0/Kvaesitso/assets/70816294/2d44e66a-d30d-4fa9-9fe1-8ccc8e87fe60)
Kvaesitso
![Screenshot_20230529_101153_Kvaesitso](https://github.com/MM2-0/Kvaesitso/assets/70816294/8d8bc2c4-2575-42f9-a9ca-20be5c603efe)

Sorry if this is already a planned feature or if it is an existing issue, I tried searching but couldn't find any.

**Comment by TK-NC** [comment]
I found an issue and a pull request from Lawnchair regarding transparent backgrounds. Hope they can be of help.
https://github.com/LawnchairLauncher/lawnchair/issues/3003
https://github.com/LawnchairLauncher/lawnchair/pull/3011

**Comment by MM2-0** [comment]
![Screenshot_20230529-155155_Kvaesitso~2](https://github.com/MM2-0/Kvaesitso/assets/15646950/ec82c1e4-29b7-4686-8aa8-3ffd5ca3567e)

Make sure you have this two settings **disabled**

**Comment by TK-NC** [comment]
It worked! Thanks.

**Comment by qkrrmsdud1** [comment]
Sorry if I'm missing something, but this doesn't seem to be fixed yet. I have those settings disabled, but my icons aren't transparent. I'm using Lawnicons, whose transparency works in Lawnchair. 
![Screenshot_20260512-100953.png](https://github.com/user-attachments/assets/0b7930e7-f21a-482c-8d4a-3a7c0c124339)
