### ISSUE TITLE
Permissions issues 

### ISSUE THREAD

**Issue by reivajpg** [MM2-0/Kvaesitso#419]
I am not getting access to notifications on Android 13.

![Screenshot_20230603-112318_Settings.png](https://github.com/MM2-0/Kvaesitso/assets/59809259/4e6c18a5-84f3-4dd4-b0f3-a16794564820)

**Comment by MM2-0** [comment]
https://kvaesitso.mm20.de/docs/user-guide/troubleshooting/restricted-settings
