### ISSUE TITLE
Search among shortcuts

### ISSUE THREAD

**Issue by glemco** [MM2-0/Kvaesitso#42]
This launcher has a much nicer interface compared a similar search based (KISS), however I'm missing the way it manages shortcuts.
As far as I understood, shortcuts on Kvaesitso are normal favorites and stay in the favorite bar, with no possibility to search among them as they don't belong to the app drawer.
What KISS does is to allow to search among any user-generated shortcut (e.g. browser favourites or chats) as well as showing all automatic shortcuts (simple actions from apps, like new tab in a browser or take a selfie from the camera, I suppose those are the same shown on long-press, which you can already set as favourites in Kvaesitso). Whatever is not an app doesn't stay in the drawer, but everything can be searched for.
I understand this could require quite some work, but it would be very nice, especially to avoid running out of spots in the favourite bar, by filling it with shortcuts that could appear only when needed.

**Comment by MM2-0** [comment]
This is a good idea, I will add this. Searching system-generated (the ones you find when you long-press an app item) and user-generated (the ones that are pinned to the favorites) shouldn't be very difficult.

**Comment by glemco** [comment]
Great, thanks!

**Comment by glemco** [comment]
That was fast, good job!
