### ISSUE TITLE
Cut off corners of widgets instead of scaling them

### ISSUE THREAD

**Issue by Fxsch** [MM2-0/Kvaesitso#426]
It would look better if corners of widgets would get cut off by the rounded corners (like Lawnchair does it) instead of the widget getting scaled to fit into the rounded corners without overlapping.

Here's what it looks like with this launcher:
![Screenshot_20230616-092735_Kvaesitso_1](https://github.com/MM2-0/Kvaesitso/assets/77849217/d0434d89-9e11-4019-b346-6f6962792052)

Here's what it looks like in Lawnchair:
![Screenshot_20230616-092816_Lawnchair_1](https://github.com/MM2-0/Kvaesitso/assets/77849217/73693d14-a153-426c-9f25-ecc980e28c80)

**Comment by exstntlmsnthrp** [comment]
This already exists. 

Assistance > cards

![Screenshot_20230616-085313.png](https://github.com/MM2-0/Kvaesitso/assets/57594290/0c75e47d-a9da-4cfe-80db-b227a84ac67c)

**Comment by MM2-0** [comment]
You can remove the padding around the widget by selecting edit widget > tap the tune icon on the widget that you want to edit and enable "borderless". You can also remove the card background the same way.

**Comment by Fxsch** [comment]
Thanks, I somehow entirely missed that there was a settings button for each widget
