### ISSUE TITLE
Question on Calling WEB API

### ISSUE THREAD

**Issue by tengkuizdihar** [MM2-0/Kvaesitso#434]
I found through my firewall that the app is hitting this screenshoted IP. According to https://ipinfo.io/185.5.82.138 this is a live server. May I know what this IP meant to be? Thank you, love the app btw!

![SmartSelect_20230624_071213_Rethink](https://github.com/MM2-0/Kvaesitso/assets/22078730/ebbeeedb-754a-4101-b3f7-9e2ef3a423cf)

**Comment by MM2-0** [comment]
Looks like a European Central Bank server to me if you scroll down to domains on that page. The launcher uses [their API](https://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml) to fetch currency exchange rates. You can turn it off in launcher settings (search > settings > unit converter > currency converter).

**Comment by tengkuizdihar** [comment]
thank you! I thought the app is phoning on to something, guess its just a currency converter.
