### ISSUE TITLE
Visual bug in "Hidden search results"

### ISSUE THREAD

**Issue by UcraNerd** [MM2-0/Kvaesitso#442]
![Screenshot_20230625-152824_Kvaesitso.jpg](https://github.com/MM2-0/Kvaesitso/assets/102480084/b9938897-2611-4fb3-80bc-89791ec457ca)

*The bottom and the high part of the screen are the problem

**Comment by MM2-0** [comment]
It's weird. Yesterday I had this issue as well, today everything is back to normal. How?!

**Comment by UcraNerd** [comment]
The owner itself is stunned!? What???

**Comment by UcraNerd** [comment]
The only usefull thing i personaly know is that this problem emerged since an update of the app like 1 month ago

**Comment by UcraNerd** [comment]
Any progress?

**Comment by MM2-0** [comment]
Can you try the following?
Change your system navigation to 3 button nav. Then set it back to gesture. Yesterday, when I had this issue, this fixed it for me. So perhaps a bug in the Android OS?

**Comment by UcraNerd** [comment]
> Can you try the following?
> Change your system navigation to 3 button nav. Then set it back to gesture. Yesterday, when I had this issue, this fixed it for me. So perhaps a bug in the Android OS?

Doesn't work, maybe its the samsung nav bar the problem.
