### ISSUE TITLE
Work Profile Compatibility Issue: Android and Third-Party App (Shelter, Insular, Island, etc.) Not Appearing in App Search or Drawer

### ISSUE THREAD

**Issue by andrewquach-dev** [MM2-0/Kvaesitso#445]
**Issue Description:**

When enabling work profiles using Android or third-party apps such as Shelter, Insular, Island, etc., there is an issue where the cloned or work version of certain applications, like Chrome, fails to appear in the app search or drawer as expected.

**Steps to Reproduce:**
1. Enable work profiles on the Android device or set up a third-party app like Shelter, Insular, Island, etc.
2. Clone or create a work version of an application, for example, Chrome.
3. Check the app drawer or perform a search to locate the cloned or work version of the application.
4. Observe that the cloned or work version of the application is missing and does not appear in the search results or app drawer.

**Expected Behavior:**

Upon enabling work profiles or creating a work version of an application, users should be able to see both the regular version and the work version of the application in the app search and drawer.

**Additional Information:**

This issue affects the visibility and accessibility of work versions of applications, preventing users from easily accessing them. It can hinder productivity and the seamless use of work-related apps alongside regular apps.

**Possible Solution:**

To address the issue of work apps not appearing in the app search or drawer, a potential solution is to utilize the functionality available in the Pixel Launcher. Users can access work apps by following these steps:

1. Open the app drawer by swiping up on the home screen or tapping the app drawer icon.
2. Swipe right or tap the "Work" tab, which should be located on the rightmost side of the app drawer.
3. Look for the desired work app within the "Work" tab.
4. Tap on the work app to launch and use it.

By leveraging the "Work" tab in the Pixel Launcher, users can easily locate and access their work apps alongside regular apps, ensuring a more seamless and convenient experience when using work profiles or cloned versions of applications.

**Comment by TheHawaiianKoala** [comment]
I do have a Work Tab while using Shelter. For frozen apps I made Shortcuts which I added to a Tag while unforzen apps appear in the app drawer under the "Work" Tab

**Comment by MM2-0** [comment]
You might need to restart (force close) the launcher. It is bugged as in it doesn't detect when a work profile is added / removed / enabled / disabled. Each of these action require a launcher restart for the change to be detected.

**Comment by andrewquach-dev** [comment]
> You might need to restart (force close) the launcher. It is bugged as in it doesn't detect when a work profile is added / removed / enabled / disabled. Each of these action require a launcher restart for the change to be detected.

Restarting fixed it. Thank you!
