### ISSUE TITLE
Crash when editing favorites

### ISSUE THREAD

**Issue by bartlibert** [MM2-0/Kvaesitso#45]
Starting with version 1.7.0, I get a crash when using the "Edit favourites" function.

If I clear all data, the crash is gone, but if at least 1 favourite is present, I get the crash.
[2022-03-22 16:44:03_crash.txt](https://github.com/MM2-0/Kvaesitso/files/8343495/2022-03-22.16.44.03_crash.txt)

**Comment by MM2-0** [comment]
Thanks for your report, I have located the issue and will release an update soon.

<sub>(It doesn't crash in dark mode btw)</sub>
