### ISSUE TITLE
[Feature Request] Digital Wellbeing

### ISSUE THREAD

**Issue by Twinsees** [MM2-0/Kvaesitso#452]
I would find it really cool if I'd be able to have a widget that shows my digital wellbeing stats something like Samsung's Lockscreen widget.
![Screenshot_20230702_110335_GitHub.png](https://github.com/MM2-0/Kvaesitso/assets/49679315/fa403b6b-3a5f-4fae-9c42-7da496384718)

**Comment by conrad82** [comment]
I am able to add this widget. 

Scroll down to the bottom on your home screen and click add widget. Search for digital wellbeing or screen time, and add the widget

![Screenshot_20230706_223853_Kvaesitso.png](https://github.com/MM2-0/Kvaesitso/assets/17353007/a0656c9d-4884-4032-be28-5292d1b56157)
