### ISSUE TITLE
Disable desktop 'bubbles'?

### ISSUE THREAD

**Issue by pallaswept** [MM2-0/Kvaesitso#456]
I saw this new launcher and thought I'd try it out, and I really liked it, except there's always this animation of little bubbles rising from the bottom of the home screen. Can I turn those off somehow?

**Comment by MM2-0** [comment]
This animation should only play while the device is charging. Is that not working correctly for you?

**Comment by pallaswept** [comment]
> This animation should only play while the device is charging. Is that not working correctly for you?

That makes sense, my phone is always connected to a charge cable. The animation stays though, even when the battery is fully charged, which also makes sense since it's drawing  power from the cable.

I imagine that it could be very useful and informative but I found it distracting. An option to disable the animation would be very much appreciated.

**Comment by pallaswept** [comment]
Hey, thanks! 😃
