### ISSUE TITLE
Random shortcut appeared on apps and can't be removed

### ISSUE THREAD

**Issue by theswordsgame** [MM2-0/Kvaesitso#458]
Randomly a Wikipedia shortcut was added to my app drawer and it can't be removed at all.

![Screenshot_2023-07-08-10-19-51-900_de mm20 launcher2 release](https://github.com/MM2-0/Kvaesitso/assets/72705300/b283e362-69cc-49e6-8201-656d4d41d223)

**Comment by MM2-0** [comment]
You can tap the edit button in the favorites section, long press the item you wish to remove, and select remove. Or, if you just ignore it and wait until another item taked its place (which shouldn't take long if you don't use that particular result).

Either way, this is the intended behavior.
