### ISSUE TITLE
Show PWAs and other browser shortcuts in apps

### ISSUE THREAD

**Issue by erazemk** [MM2-0/Kvaesitso#459]
Currently there is no way to show apps that are "Added to Home screen" from the browser in the launcher (both PWAs and regular sites with just a desktop icon).

It would be useful to be able to show those apps in the app screen. Right now they can be searched for and added through that, but that makes it hard if you forget a website's name or want to remove a website.

**Comment by erazemk** [comment]
Here's an example of what I mean
![Screenshot_20230710-124323_Kvaesitso](https://github.com/MM2-0/Kvaesitso/assets/46302511/9bd15ad0-635d-4b66-976c-fb17d567bdff)

**Comment by MM2-0** [comment]
Do you mean like a list that shows all shortcuts that belong to one specific app?

**Comment by erazemk** [comment]
I meant with some launchers that have desktop icons you can add an icon for a website to the desktop. Since Kvaesitso doesn't have desktop icons it could be useful to show these icons with other apps, in the same menu.

Screenshot is of an example of a desktop icon, what I propose is to have that same icon in the apps list. There is no need to group icons by app.

![Screenshot_20230710-133109_Pixel_Launcher](https://github.com/MM2-0/Kvaesitso/assets/46302511/f43e812d-ecbd-4453-970a-7c05a1417c50)

**Comment by MM2-0** [comment]
They should appear in the favorites section as you add them. Is that not working for you?

**Comment by erazemk** [comment]
Ah, indeed they do, I just had favorites disabled. Thank you!
