### ISSUE TITLE
How do you change the weather provider?

### ISSUE THREAD

**Issue by Parmjot-Singh** [MM2-0/Kvaesitso#460]
![Screenshot_20230712_133022_Kvaesitso.png](https://github.com/MM2-0/Kvaesitso/assets/100116708/08cc17e2-3eec-497a-867b-fb74fe9c4e6d)

I only have one provider, which is for Germany, and as such, I cannot get weather for my location, which is outside of Germany. How do I add more, since I can't find a way in the documentation.

**Comment by adienox** [comment]
Are you using the nightly version? Only German weather is available in the nightly build as far as I know.

**Comment by Parmjot-Singh** [comment]
I just installed it from F-Droid

**Comment by adienox** [comment]
Which repo are you using on F-Droid for the launcher?

**Comment by Parmjot-Singh** [comment]
I'm on the F-Droid repos. I'm assuming that the other APIs are available on the non-foss version, but that isn't ideal for me.

**Comment by adienox** [comment]
Additional API features are only available in the IzzyOnDroid repo, and the owner provided repo.

**Comment by Parmjot-Singh** [comment]
OK, I'll live with no weather then. Closing.
