### ISSUE TITLE
[1.26.3] All Icons White

### ISSUE THREAD

**Issue by yukiqt** [MM2-0/Kvaesitso#462]
![Screenshot_20230712-204318_Kvaesitso](https://github.com/MM2-0/Kvaesitso/assets/83128586/0c6e1bff-fd0b-4084-a0e6-14497cb2e34c)
![Screenshot_20230712-204230_Kvaesitso](https://github.com/MM2-0/Kvaesitso/assets/83128586/377c55bb-098f-47ef-bc20-cfce22c14aa0)

**Comment by Pouncingkitten** [comment]
How did you solve this?
