### ISSUE TITLE
Weird icons after update

### ISSUE THREAD

**Issue by Henry-Hiles** [MM2-0/Kvaesitso#466]
Hello! I just updated, and now my icon backgrounds are a different (worse) color, not the same nice blue from Monet they were before, and also the icons are huge inside of the squares, any ideas? Thanks.
![Screenshot_20230713-150942_Kvaesitso](https://github.com/MM2-0/Kvaesitso/assets/71790868/89a7c079-1cba-4dff-b8f9-503d27109409)

**Comment by Henry-Hiles** [comment]
Before this, the background of the icons was similar to the background of the edit button, and the foreground was much smaller in the buttons.

**Comment by Henry-Hiles** [comment]
That's a shame, it makes it practically unusable. Thanks for the reply anyways.

**Comment by Henry-Hiles** [comment]
Is it not possible for the icon size thing to be a setting instead?

**Comment by Henry-Hiles** [comment]
As for the colors, I think they should absolutely be changed back.

**Comment by yant0** [comment]
Yeah i agree please change it back
