### ISSUE TITLE
Don't focus on search bar by default.

### ISSUE THREAD

**Issue by avuton** [MM2-0/Kvaesitso#470]
I'd like to request not to focus on the search bar by default, so the keyboard doesn't popup when pulling the app bar down (or an option, perhaps?).

**Comment by MM2-0** [comment]
There is an option for that: Settings > Search > Open Keyboard
And it's on by default to encourage users to use the search, but you can turn it off if you want.

**Comment by yaomtc** [comment]
I think it makes more sense for it to say "when opening the app drawer" as when this is disabled, the gesture to open the app drawer doesn't affect the search bar. I would consider tapping the search bar to be opening the search, and that action isn't affected by this setting (appropriately). Could I make a pull request with this text change or would that be unnecessary?

**Comment by MM2-0** [comment]
> Could I make a pull request with this text change or would that be unnecessary?

Better submit text change suggestions to our Weblate instance: https://i18n.mm20.de/projects/kvaesitso/
