### ISSUE TITLE
can't change language pixel 7

### ISSUE THREAD

**Issue by RafaeldeGomesMonteiro** [MM2-0/Kvaesitso#479]
There's no option to change language either on app or system settings.
Im also trying to set the default search engine as ddg instead of Google and that's not possible (at least in Portuguese)

**Comment by exstntlmsnthrp** [comment]
The language should be whatever the system default is set at for your phone. I see you mention Portuguese. Thus far it seems the app has only been translated into 24 languages and currently it appears the only Portuguese translation is Brasil and not European. 

To add Duckduckgo (or any other search option you wish to use) go to kvaesitso settings > quick actions. 

![Screenshot_2023073.png](https://github.com/MM2-0/Kvaesitso/assets/57594290/d5dcca98-9156-417c-8332-3e23cc94d1ec)

Select the plus (+) in the bottom corner to add DDG. You can also select an existing option to change or delete it.
