### ISSUE TITLE
[Feature request] Displaying two widgets in one row

### ISSUE THREAD

**Issue by quintus3236** [MM2-0/Kvaesitso#481]
I think it would be pretty useful to be able display two widgets side-by-side. Especially ones that are square shaped.

**Comment by BlackberrieCake137** [comment]
this would be really useful. Something Windows Phone's Metro UI did really well was having vertical scrolling like on Kvaesitso, but widgets could be placed next to each other for better space management

**Comment by kaibagley** [comment]
Same as https://github.com/MM2-0/Kvaesitso/issues/380

I agree, this would be a great feature
