### ISSUE TITLE
Security Issue (or not)

### ISSUE THREAD

**Issue by Zyban117** [MM2-0/Kvaesitso#483]
While monitoring my phone internet, the launcher made contact to "Europe Central Bank" which is werid because the only thing the launcher have is the weather that only works for German Weather. I don't know if this is a DoSS attack undercover or something suspicions software.

I have proof 
![Screenshot_2023-08-04-02-14-28-292](https://github.com/MM2-0/Kvaesitso/assets/141384625/f13f6201-b677-4499-9f75-7624300cec26)

**Comment by MM2-0** [comment]
Thr launcher contacts the an ECB endpoint to fetch the currency rates that are used in the unit converter. You can turn it off in Settings > Search > Unit Converter > Currency Converter.

**Comment by Zyban117** [comment]
Oh I see, sorry for misunderstanding.
