### ISSUE TITLE
🎟️ Color scheme feature

### ISSUE THREAD

**Issue by rahaaatul** [MM2-0/Kvaesitso#484]
# Description
Lot of times we set wallpapers and the default color is just what we like. But we don't know the color scheme, so if we change the wallpaper the color scheme is gone.

# Request
Add an option to save current default color scheme and use it later.

Options could be:
- Save in a txt file
- Save default color scheme as a template for later use in launcher with other wallpapers
- Option to select and view the default color codes (idea by @exstntlmsnthrp).

**Comment by MM2-0** [comment]
Added in 1.27.0
