### ISSUE TITLE
Clock app for clock widget

### ISSUE THREAD

**Issue by kaibagley** [MM2-0/Kvaesitso#489]
I haven't been able to find a way, and maybe this is something that needs to be set within the phone OS, but it would be nice to be able to choose the default clock app for the launcher. Such that when tapping on the clock widget, a clock app of your choosing opens.

I'm using GrapheneOS and there isn't an option for default clock app within this OS (from what I can tell), so doing this within Kvaesitso would be very handy for me at least.

Thanks!

**Comment by MM2-0** [comment]
Kvaesitso launches the default alarm app when you tap the clock widget (or shows a chooser if you haven't set one yet):

 <details>

![Screenshot_20230809-202920_Android System](https://github.com/MM2-0/Kvaesitso/assets/15646950/c4a76b20-fe29-41a7-bdd5-595d324a3e4f)

</details>

If that doesn't happen, you either don't have an alarm app installed, or your alarm app does not implement basic Android standards.

**Comment by kaibagley** [comment]
I see, in that case the problem is the clock app, looks like I'll need to get a better one.

Thanks!
