### ISSUE TITLE
[Feature request] Options to show widget drawer by default

### ISSUE THREAD

**Issue by uhkeller** [MM2-0/Kvaesitso#501]
Thanks for Kvaesitso, I'm enjoying using it a lot! I have one gripe though:

I know a lot of people like to look at their smartphone wallpaper, but I'm not one of them – when I unlock my phone, I want to do something with it as quickly as possible. With Kvaesitso, I always swipe up to see the widgets (which include the favorites widget with multiple lines so I can open apps quickly). It would be nice if if there was an option for the Kvaesitso to always show the widget drawer when launching it so I could skip the swiping up step.

**Comment by MM2-0** [comment]
Glad you like it. The option you requested already exists: go to settings > home screen > clock and disable fill screen height.

**Comment by uhkeller** [comment]
Wow, thank you! And sorry, seems I got lost in the settings a bit.

**Comment by MM2-0** [comment]
No worries. Clock widget settings are definitely unintuitive and something I need to improve in a future update.
