### ISSUE TITLE
[Feature Idea] Having app shortcuts in tags

### ISSUE THREAD

**Issue by kud** [MM2-0/Kvaesitso#509]
Hey,

We've got tags, and we can make favourite some app shortcuts, which is great.

It could be even better if we were able to have some app shortcuts into tags as well.

Thanks, 😌

**Comment by kud** [comment]
I'm sorry, I've tried, I don't see how I can have an app shortcut INSIDE a tag, like messaging to someone on Whatsapp.

**Comment by madx** [comment]
That would be a great feature, just to be extra clear what @kud means is being able to add a tag by long pressing an app shortcut such as the one circled in red in the screenshot below:

![Screenshot_20230824-163856.png](https://github.com/MM2-0/Kvaesitso/assets/5723/c5749beb-3db1-4900-997e-fd6cb2212751)

**Comment by madx** [comment]
Oh yeah that works perfectly 👌
Thanks for the heads up and keep up the great work, this launcher is reaaaaallly cool!

**Comment by kud** [comment]
Good point! Thank you 😌
