### ISSUE TITLE
Group widgets per app

### ISSUE THREAD

**Issue by HerrHellmus** [MM2-0/Kvaesitso#51]
When adding widgets, they're sorted alphabetically, bit it's not always clear to which app they belong. 
I think this could be solved by either adding an app icon to the widget preview or grouping the widgets per app.
It's no deal breaker for me, but I think it will improve the user experience.

**Comment by MM2-0** [comment]
You are right. The current widget selection screen was kinda slapped together in order to fix some widget related issues but I plan to improve it sooner or later.
