### ISSUE TITLE
[Enhancement] Sort app search results by relevance

### ISSUE THREAD

**Issue by laurentlbm** [MM2-0/Kvaesitso#52]
At the moment, the results are sorted alphabetically. I think that it would be better if it was sorted by "relevance". By that, I'm thinking of something like this:
- apps starting with the search term
- apps with a word starting with the term (also taking into account that some apps are in PascalCase)
- substring match
- other fuzzy matches

**Comment by laurentlbm** [comment]
Maybe if the matches are visually highlighted. For example, if you search for "bro":
- **Bro**mite
- Tor **Bro**wser
- Li**br**era P**r**o
- Invizi**b**le P**ro**

I have no idea how hard it is to implement though. 

Another option would be that it's a setting to sort the results either alphabetically or by relevance.

**Comment by deepu2** [comment]
> For reference, this is how KISS Launcher shows it (in reverse order from the bottom):
> ![Screenshot_20220404-094330826 (1)](https://user-images.githubusercontent.com/1180863/161557635-ed977146-fa6b-40fa-ad26-4421abbc538a.jpg)
> 
> 

Kiss launcher is such an incredible software, I find it nearly impossible to switch to other launchers even for a day. 
Kvaesitso has a nice widgets drawer that I really liked but the search isn't quite there yet. An hybrid of two apps would be quite perfect.

**Comment by sadellie** [comment]
Hello @MM2-0, I think this is the implementation you are looking for. It sorts objects by their similarity to the search query:
1. Full match
2. Starts with the query
3. Contains the query
4. Similar to query (fuzzy)

https://github.com/sadellie/unitto/blob/0c69cb90fa630ac9ffd66ad230ebb2201a0ed11c/data/model/src/main/java/com/sadellie/unitto/data/model/AbstractUnit.kt#L76

Hope my code is not too difficult to understand.

**Comment by Sir-Photch** [comment]
This was added and can be closed

**Comment by AidanRB** [comment]
> This was added and can be closed

Was this added? I'm unable to find this behavior in the latest release. Searching for "ma" orders Gmail before Maps when sorting search results both alphabetically and by usage, despite Maps starting with "ma".

**Comment by Sir-Photch** [comment]
How do you sort both alphabetically and by relevance?

**Comment by AidanRB** [comment]
Either or, sorry. I meant it happens with both individually.

**Comment by AidanRB** [comment]
This issue appears to be about sorting by relevance, as opposed to usage. I understand why Gmail comes before Maps in both cases, but a sort as described in this issue would change that. Can this be left open if/until that is implemented?

**Comment by Sasuchisama** [comment]
Like the other comments, it would be nice If "ing" ist First App in row "Ing" to start with enter. At the Moment there are "Shopping"-Apps at first place.

For me its a more Natural and faster was to start Apps or Open websites.

**Comment by AidanRB** [comment]
This is added in the latest release, 1.34.0!

**Comment by deepu2** [comment]
Ok, just to confirm,
1. yt doesn't return YouTube
2. Ppe doesn't return PhonePe

Isht this what OP requested?
