### ISSUE TITLE
[BUG] Quick Action for Google not working

### ISSUE THREAD

**Issue by Cosmic-Wolf** [MM2-0/Kvaesitso#520]
When I try to use the quick action for Google App, it seems to be unresponsive. There is nothing indicative of an error in the debug page either.

https://github.com/MM2-0/Kvaesitso/assets/143350197/51fbcfdd-cbb7-4125-8861-e80ac3b78e1e

I am on Samsung Galaxy A7 (2018), Android 10, One UI 2.

**Comment by MM2-0** [comment]
Known issue. Half of the apps are broken, unfortunately. You should always prefer a websearch action when possible.

**Comment by Cosmic-Wolf** [comment]
I know that it is an experimental feature. But app default does not work either. So, all my Google searches are by default opened via Chrome, which is kinda inconvenient. I have not seen this issue with other apps such as YouTube or Spotify.

**Comment by MM2-0** [comment]
If you want to search in the Google app, enable the default "web search" action that has been added in 1.27

**Comment by Cosmic-Wolf** [comment]
> If you want to search in the Google app, enable the default "web search" action that has been added in 1.27

I am not able to install 1.27, it constantly throws me a App Not Installed error. (It's a thing with Samsung idk)

Also, just wondering, what's the lowest Android version supported? I tested on a Samsung with Android 11 and a Vivo with Android 13, it works there. It appears to be a device issue. Does not work on my Samsung with Android 10..

**Comment by MM2-0** [comment]
> I am not able to install 1.27, it constantly throws me a App Not Installed error. (It's a thing with Samsung idk)

What version do you have installed? F-Droid version or Github version? You can only upgrade to the same version (but F-Droid version hasn't been updated to 1.27 yet)

> Also, just wondering, what's the lowest Android version supported? I tested on a Samsung with Android 11 and a Vivo with Android 13, it works there. It appears to be a device issue. Does not work on my Samsung with Android 10..

In theory, Android 8.0 and above is supported. However, I only really test it on Android 13 so it is not unlikely that stuff is broken on those older Android versions.

**Comment by Cosmic-Wolf** [comment]
> What version do you have installed? F-Droid version or Github version? You can only upgrade to the same version (but F-Droid version hasn't been updated to 1.27 yet)

F-droid version (1.25) installs just fine. I uninstalled it and then installed the GitHub version (1.27) which throws me the said error.

> In theory, Android 8.0 and above is supported. However, I only really test it on Android 13 so it is not unlikely that stuff is broken on those older Android versions.

Ok this might sound funny but the regular version of kvaesitso does not work. Whereas, Kvaesitso Nightly works like a charm. 😂
