### ISSUE TITLE
[Bug] Adding a quick action does not work anymore

### ISSUE THREAD

**Issue by kud** [MM2-0/Kvaesitso#521]
Hey,

I've created two quick actions:

- spotify
- contacts

They still work when I search something.

However, since the latest version of Quick Action, I can't add any action anymore. 

https://github.com/MM2-0/Kvaesitso/assets/655838/644ad3b2-ea8f-465e-a7e8-4f34ea0171b1

**Comment by kud** [comment]
By the way, the "plus" button hides the web search toggle button.

**Comment by Cosmic-Wolf** [comment]
I attempted the same and am encountering the same issue.

**Comment by MM2-0** [comment]
Can you test if it is fixed in the latest nightly?

**Comment by Cosmic-Wolf** [comment]
I tested on v1.27.0 of nightly. And no, it doesn't seem to be working there either.

**Comment by MM2-0** [comment]
Can you test today's?

**Comment by Cosmic-Wolf** [comment]
> Can you test today's?

Yes, it is working on the latest nightly.
