### ISSUE TITLE
color pallet bug when closing launcher settingd

### ISSUE THREAD

**Issue by ansarimohammed422** [MM2-0/Kvaesitso#524]
Whenever we open launcher settings and change something and then close settings from recent view

The whole launcher reverts to previous color pallet .

But not the one generated by the launcher

And then I have to change the wallpaper to make it go dynamic again

![Screenshot_2023-08-31-14-37-27-233_de mm20 launcher2 release](https://github.com/MM2-0/Kvaesitso/assets/78704469/e4c5bc25-56a1-405e-8f54-c752e24610d2)

See wallpaper color and launcher color

**Comment by MM2-0** [comment]
Can you record a video? I don't quite understand what you mean

**Comment by ansarimohammed422** [comment]
Video:- 

/

**Comment by ansarimohammed422** [comment]
Video:-

**Comment by exstntlmsnthrp** [comment]
@ansarimohammed422 GitHub limits the size of uploads, so you either need to edit the video smaller or reduce the quality so it's smaller. I don't remember, but I believe the limit is 15mb. Maybe that will help you. 

Another option is save the video elsewhere online and just share a link to the video.

**Comment by ansarimohammed422** [comment]
Video:-

Don't pay attention to icon pack ita another bug



https://github.com/MM2-0/Kvaesitso/assets/78704469/aceb7532-8bd7-4b68-b5c1-f9c226a61a19

See launcher color before and after I close settings from recents view

It fall backs to previous wallpaper color

**Comment by ansarimohammed422** [comment]
Any update on this issue

**Comment by MM2-0** [comment]
Yeah: can't reproduce. Anyone else facing this issue? Btw are you on pre-Android 12 or Android 12+?

**Comment by ansarimohammed422** [comment]
Once again this bug occurred see this video...


https://github.com/MM2-0/Kvaesitso/assets/78704469/534e325d-9ddf-4491-8945-85d1e31e1453

**Comment by ansarimohammed422** [comment]
Any fixes for this issue

**Comment by strongville** [comment]
Can we use Material You Compat also for versions 12+ in Kvaesitso?

It seems that some customization layers such as One UI (in my case) or MIUI (on PO's case) don't retrieve a meaningful color on wallpaper change (just on enabling the option from Settings, so cumbersome...), and on previous versions, for example, Android 11, still on One UI, the color is more coherent.
