### ISSUE TITLE
[Enhancement] Launch first app search result when tapping "Done/Search"

### ISSUE THREAD

**Issue by laurentlbm** [MM2-0/Kvaesitso#53]
In order to launch an app more quickly, I would like to be able to search for it and then just tap `→`. 
If no apps match the search, it could launch the first app shortcut found.

I've used this a lot in other launchers and kinda miss it.

**Comment by MM2-0** [comment]
Good idea, I will add this. I guess this would work best if I also implemented #52?

**Comment by laurentlbm** [comment]
> I guess this would work best if I also implemented https://github.com/MM2-0/Kvaesitso/issues/52?

Yes 😆

Thanks for the your work, btw, I really like the launcher!

**Comment by Gedaliya** [comment]
I would also love this option, maybe also with a choice to launch the top app or the top search? Your launcher has the best search based navigation I have seen. In most applications, go/search/return will launch the top app/search/website (if a website is typed in).

I've been experimenting with this for a while now and just switched over to Kvaesitso as my daily driver. I love the philosophy of getting quickly and simply to powerful search and card-based widgets, and I love how responsive you are in development. Thank you!

**Comment by ggdorman** [comment]
Would love to see this implemented. It should also open the first web shortcut when doing a search.

**Comment by ChrisCochrun** [comment]
Came to say, same. Launch on return would be great! Especially with web searches since those don't match anything else. I wish I knew kotlin. If you need help or are super swamped I could attempt but haven't ever done it.

**Comment by FarisZR** [comment]
looks like this broke in one of the latest updates, it used to always work, now it only works on a new start of the launcher.
