### ISSUE TITLE
A way to see updates

### ISSUE THREAD

**Issue by lolpowerluke** [MM2-0/Kvaesitso#535]
It would be nice if the app told me when there is a new version for available, an actual updater in the app isn't necessary for me, cause I know that that would take way to much work and time, but just like a notification saying a new update is available would be nice, and if possible, if you press that notification, it brings you to the github releases page

**Comment by MM2-0** [comment]
You can

- subscribe to releases in this repo (which will give you email notificiations on each release)
- if you use F-Droid, you can add [my repo](https://fdroid.mm20.de)

**Comment by Kskis** [comment]
Obtanium will pull direct also

**Comment by exstntlmsnthrp** [comment]
[Obtanium](https://github.com/ImranR98/Obtainium) for Android. Just select releases. It's an awesome app!
