### ISSUE TITLE
Icon Pack Mismatch

### ISSUE THREAD

**Issue by Cosmic-Wolf** [MM2-0/Kvaesitso#548]
Ok, so I just installed an Icon Pack made using Icon Pack studio and most of it is fine except for a few handful of apps for which it seems that the Icons are mismatched. Amazon has Kvaesitso logo, Whatsapp has Amazon logo, etc. I suspect it has to do something with how Icon Packs are loaded in Kvaesitso. Probably because it hides the launcher app but then forgets to count it and then index it. I don't have this issue and with other launchers so it is definitely not an issue with the icon pack itself.

**Comment by MM2-0** [comment]
Known issue with Icon Pack Studio, if you change the icon pack and reinstall a new version, it isn't registered correctly. Go to Settings > Debug > Clear icon pack cache to fix it.

**Comment by Cosmic-Wolf** [comment]
> Known issue with Icon Pack Studio, if you change the icon pack and reinstall a new version, it isn't registered correctly. Go to Settings > Debug > Clear icon pack cache to fix it.

Clear Cache and Install Icon Pack fixed it. Thanks!
