### ISSUE TITLE
Importing Color Schemes Help

### ISSUE THREAD

**Issue by via80HD** [MM2-0/Kvaesitso#552]
This isn't technically a issue with the app itself & probably more closely aligns with user incompetence but I didn't know where else to ask for help after not finding much info on how to successfully import color schemes. Pretty much all I can tell is that I'd use the button circled in the screenshot attached to import a scheme but I'm not sure where to start. 
![Screenshot_20230924-003318](https://github.com/MM2-0/Kvaesitso/assets/84550322/5fc4104d-8791-4ef5-b3cb-0e8c9043817b)
I guess my main questions are:

1. Where to find/download these color schemes 
&
2. What is the correct file type to download

I tried importing a .ase file that a pallette generator spit out but that caused a crash so it doesn't seem like .ase files are the way to go. 

Thanks in advance. I am really enjoying the launcher though so great work 👍

**Comment by MM2-0** [comment]
> What is the correct file type to download

It's a custom file format (*.kvtheme). You can generate these files by tapping "share" in the 3-dot-menu of each color scheme. The feature is intended for users of this launcher to share their creations with other users.

> Where to find/download these color schemes

Your best shot at the moment is the dedicated topic in [our Telegram group](https://t.me/Kvaesitso/16709) (there are like 4 themes atm). However, people are free to share them wherever they want.

**Comment by via80HD** [comment]
> > Your best shot at the moment is the dedicated topic in [our Telegram group](https://t.me/Kvaesitso/16709) (there are like 4 themes atm). However, people are free to share them wherever they want.

> Thanks! Ill definitely share mine once I get it like that tiny bowl of porridge.... just right.. Appreciate it
