### ISSUE TITLE
Fix calculator percentage

### ISSUE THREAD

**Issue by Drsheppard01** [MM2-0/Kvaesitso#554]
Actions taken:
I enter 6999-7% in the global search.
The result is in error: 6998,93
Correct result: 6509,07

**Comment by MM2-0** [comment]
In what cursed version of math is 6509,07 the correct result to that equation?

**Comment by Drsheppard01** [comment]
Yeah, that's right. Is it possible to reduce the number of actions to '6999 - 7%?'

**Comment by Cosmic-Wolf** [comment]
> Yeah, that's right. Is it possible to reduce the number of actions to `6999 - 7%`?

The best way to write it should be `6999 - 6999 * 7%`. There method that you suggest isn't mathematically correct.

**Comment by KingLucius** [comment]
> In what cursed version of math is 6509,07 the correct result to that equation?

Most calculators ( including the one in windows & android) do this.

**Comment by Drsheppard01** [comment]
Now that we're talking about it again
I'd like to know if this change will be made or not.

**Comment by MM2-0** [comment]
>  I'd like to know if this change will be made or not.

Probably not, at least not anytime soon. I agree that by convention, it would be the right thing to do to allow this kind of calculation, because most other calculator apps allow it as well. However, I didn't write the calculator myself, I am using a third party library. And in this library, there is no way to correct that behavior, so I would need to switch to a different library. Then again, the library I'm currently using ([mXparser](https://mathparser.org/)) isn't FOSS anymore so I am using an outdated version, and switching to a different library (or forking mXparser) would be beneficial in the long term anyway.

**Comment by Drsheppard01** [comment]
I'm not developer, but I can read the code, and I find cuteCalc use this library https://github.com/notKamui/Keval
Maybe it's help you

Best regards, Dr.Sheppard

**Comment by MM2-0** [comment]
> I'm not developer, but I can read the code, and I find cuteCalc use this library https://github.com/notKamui/Keval Maybe it's help you
> 
> Best regards, Dr.Sheppard

I have seen this library, and it looks promising, but in cuteCalc, `10+10%=10.1` which is not what we want, we want it to be `11`.

**Comment by exstntlmsnthrp** [comment]
> > I'm not developer, but I can read the code, and I find cuteCalc use this library https://github.com/notKamui/Keval Maybe it's help you
> > 
> > Best regards, Dr.Sheppard
> 
> I have seen this library, and it looks promising, but in cuteCalc, `10 + 10% = 10.1` which is not what we want, we want it to be `11`. 
> 

I'd argue that is correct mathematics. It should not equal 11; the answer is 10.1. To get 11 it should be `10 + (10 x 10%) = 11`. Another way of writing it is `10 x 1.1 = 11`. So there is nothing incorrect about cuteCalc. 

I'd also add that I think it would be slightly irresponsible to promote or enable the incorrect use of mathematics.

**Comment by MM2-0** [comment]
> > > I'm not developer, but I can read the code, and I find cuteCalc use this library https://github.com/notKamui/Keval Maybe it's help you
> > > Best regards, Dr.Sheppard
> > 
> > 
> > I have seen this library, and it looks promising, but in cuteCalc, `10 + 10% = 10.1` which is not what we want, we want it to be `11`.
> 
> I'd argue that is correct mathematics. It should not equal 11; the answer is 10.1. To get 11 it should be `10 + (10 x 10%) = 11`. Another way of writing it is `10 x 1.1 = 11`. So there is nothing incorrect about cuteCalc.
> 
> As I believe was shared above, another way of writing `10 + 10% = 10.1` is `10 + 0.1 = 10.1`, thus reinforcing that cuteCalc is correct.
> 
> I'd also add that I think it would be slightly irresponsible to promote or enable the incorrect use of mathematics.

I don't disagree with your maths, but I can't think of any real life scenario where anyone would type `10 + 10%` into their calculator and expect the result to be `10.1`. It might be mathematically correct, but the term in itself is nonsense. 

I've tested several calculator apps, and they all understand the term the way the user most likely intends it to be understood:
- Google calculator app
- the calculator on Google search
- the macOS calculator app
- the calculator in Spotlight
- KDE KCalc
- the calculator in KRunner
- the physical hardware calculator that I used in school

**Comment by exstntlmsnthrp** [comment]
> I don't disagree with your maths, but I can't think of any real life scenario where anyone would type `10 + 10%` into their calculator and expect the result to be `10.1`. It might be mathematically correct, but the term in itself is nonsense. 
> 
> I've tested several calculator apps, and they all understand the term the way the user most likely intends it to be understood:
> - Google calculator app
> - the calculator on Google search
> - the macOS calculator app
> - the calculator in Spotlight
> - KDE KCalc
> - the calculator in KRunner
> - the physical hardware calculator that I used in school

Haha 😆 That made me laugh. For me it's just the opposite. I cannot think of any situation where someone would type `10 + 10%` and expect it to equal 11. And I didn't argue the results of any calculator you reference. In my opinion, that equation is missing a term; 10% of what? If one expects the result to be 11, as written that's making the **assumption** that it's 10% of 10, but it's not defined as such. 

I acquiesce. I still think it illogical, but that's just me. Obviously, I'm in the minority, as that seems to be somewhat standardized.

**Comment by exstntlmsnthrp** [comment]
> 
> > I don't disagree with your maths, but I can't think of any real life scenario where anyone would type `10 + 10%` into their calculator and expect the result to be `10.1`. It might be mathematically correct, but the term in itself is nonsense. 
> > 
> > I've tested several calculator apps, and they all understand the term the way the user most likely intends it to be understood:
> > - Google calculator app
> > - the calculator on Google search
> > - the macOS calculator app
> > - the calculator in Spotlight
> > - KDE KCalc
> > - the calculator in KRunner
> > - the physical hardware calculator that I used in school
> 
> Haha 😆 That made me laugh. For me it's just the opposite. I cannot think of any situation where someone would type `10 + 10%` and expect it to equal 11. And I don't argue the results of any calculator you reference. In my opinion, that equation is missing a term; 10% of what? If one expects the result to be 11, as written that's making the **assumption** that it's 10% of 10, but it's not defined as such. 
> 
> I acquiesce. I still think it illogical, but that's just me. Obviously, I'm in the minority, as that seems to be somewhat standardized.
