### ISSUE TITLE
PDF considered as video file in search

### ISSUE THREAD

**Issue by DotDev262** [MM2-0/Kvaesitso#556]
Well from the title as you can tell any pdf file I search tries to open it in the video player.

Included below is a photo about it.

![Screenshot_20230928_091732.jpg](https://github.com/MM2-0/Kvaesitso/assets/127623817/2a95ea4f-6167-49ba-886f-baa16c147a6b)

**Comment by MM2-0** [comment]
What is displayed as MIME type (long press it > type)?

**Comment by DotDev262** [comment]
Sorry for the late response
![Screenshot_2023_0928_175013.png](https://github.com/MM2-0/Kvaesitso/assets/127623817/66a0b474-38f9-4fd9-a97f-29b90d13d208)

**Comment by DotDev262** [comment]
An update to this I found that only some of this files are like this while others are fine .
![Screenshot_2023_1001_191407.png](https://github.com/MM2-0/Kvaesitso/assets/127623817/4d028faa-e60a-4875-b9de-d0e6ac3d40fb)

I will try looking for any difference among these files.

**Comment by DotDev262** [comment]
The only fix I found for now is to edit the metadata for it to be considered as a pdf.

**Comment by MM2-0** [comment]
>  I will close it since it most probably is an error in the tags of my files and not the launchers fault.

I think so too. I'm not sure who sets the mime types (either the Android OS, or the app that created the file), but all the launcher does is read it from a database. Treating a file as video when its mime type says `video/*` is the correct behavior. I have no idea where the `video/*` originated from.
