### ISSUE TITLE
Adding widgets not working Android 14

### ISSUE THREAD

**Issue by lgwapnitsky** [MM2-0/Kvaesitso#558]
I'm running a Pixel 6 pro on the latest pre-release of Android 14. Up until a week ago, I was able to add widgets from multiple applications, but after the latest update, I get logged similar to these for multiple applications. I do not have the same issues in pixel Launcher when testing the same widgets.

This is an example of the log entries after trying to add a widget from Chronus. I received similar log entries after trying JTX and multiple other applications

```
Device: raven
SDK version: 34
====================================
10-01 08:41:58.077  4055 28340 W PackageParser: Unknown element under <manifest>: queries at /storage/emulated/0/Download/com.google.android.projection.gearhead_10.5.633814-release-105633814_minAPI26(arm64-v8a)(nodpi)_apkmirror.com.apk Binary XML file line #274
10-01 08:41:58.085  4055 28340 W PackageParser: Unknown element under <service>: property at /storage/emulated/0/Download/com.google.android.projection.gearhead_10.5.633814-release-105633814_minAPI26(arm64-v8a)(nodpi)_apkmirror.com.apk Binary XML file line #1887
10-01 08:41:58.103  4055 28340 W PackageParser: Unknown element under <manifest>: queries at /storage/emulated/0/Download/F-Droid.apk Binary XML file line #99
--------- beginning of main
10-01 08:44:31.633  4055  4055 W WindowOnBackDispatcher: OnBackInvokedCallback is not enabled for the application.
10-01 08:44:31.633  4055  4055 W WindowOnBackDispatcher: Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
10-01 08:44:31.760  4055  4055 I ImeTracker: de.mm20.launcher2.release:2eb2e3c2: onRequestHide at ORIGIN_CLIENT_HIDE_SOFT_INPUT reason HIDE_SOFT_INPUT
10-01 08:44:31.760  4055  4055 I ImeTracker: de.mm20.launcher2.release:2eb2e3c2: onFailed at PHASE_CLIENT_VIEW_SERVED
10-01 08:44:31.763  4055  4055 I ImeTracker: de.mm20.launcher2.release:fca706df: onRequestHide at ORIGIN_CLIENT_HIDE_SOFT_INPUT reason HIDE_SOFT_INPUT_BY_INSETS_API
10-01 08:44:31.763  4055  4055 I ImeTracker: de.mm20.launcher2.release:fca706df: onCancelled at PHASE_CLIENT_APPLY_ANIMATION
10-01 08:44:50.059  4055  4055 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=falsecallback=android.view.ViewRootImpl$$ExternalSyntheticLambda17@c9edf87
10-01 08:44:56.263  4055  4055 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=falsecallback=android.view.ViewRootImpl$$ExternalSyntheticLambda17@dd74c25
10-01 08:44:56.265  4055  4290 D OpenGLRenderer: endAllActiveAnimators on 0xb4000077716ecd60 (UnprojectedRipple) with handle 0xb4000078015d0c70
10-01 08:44:58.261  4055  4055 W WindowOnBackDispatcher: OnBackInvokedCallback is not enabled for the application.
10-01 08:44:58.261  4055  4055 W WindowOnBackDispatcher: Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
null
```

**Comment by kostaj** [comment]
Same behaviour on pixel 7 with 14 release. A couple betas ago was fine.  Testing it out it can add some like audible, Pulsar, Wallabag, brave widgets without issue. Others like business calendar 2, WhatsApp, smartthings, fairemail cannot be added.

**Comment by MM2-0** [comment]
When you say you can't add widgets, do you mean there is an error ("widget could not be loaded" or similar) or do they not appear at all?

**Comment by kostaj** [comment]
I scroll down, go to edit widgets, add widget, and can see a list of built in + app widgets sorted by app.  If I tap on a widget for an app that doesn't work the screen briefly flashes to my wallpaper then returns to the list of widgets without adding it.  I did try wiping data/cache/uninstall and reinstall the launcher. It seems to work with the default pixel launcher with with at least one of the affected widgets.

**Comment by kostaj** [comment]
Thanks for looking at it. From the log after trying a few:

10-05 12:50:34.101 17300 17300 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=falsecallback=android.view.ViewRootImpl$$ExternalSyntheticLambda17@eb4796f
10-05 12:50:34.414 17300 17300 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=falsecallback=android.view.ViewRootImpl$$ExternalSyntheticLambda17@8b9082d
10-05 12:50:34.419 17300 17300 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=falsecallback=android.view.ViewRootImpl$$ExternalSyntheticLambda17@de3775b
10-05 12:50:34.853 17300 17300 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=falsecallback=android.view.ViewRootImpl$$ExternalSyntheticLambda17@cbd67be
10-05 12:50:38.069 17300 17300 W WindowOnBackDispatcher: OnBackInvokedCallback is not enabled for the application.

**Comment by exstntlmsnthrp** [comment]
I wonder if it's something with the Android 14 beta? 

I just tested on 13 (though technically it's LineageOS) and successfully created several of the widgets that failed for you.

**Comment by MM2-0** [comment]
Could be a permission issue, maybe the bind widget permission got lost during an update or something. Could you make a clean install of the latest nightly and try if it works there?

**Comment by lgwapnitsky** [comment]
Tried adding Chronus and JTX


I've attached a log.

**Comment by kostaj** [comment]
Thanks for your time.  This is with the android 14 release on a stock pixel 7 without any root/modifications. Interesting, it fixed it then didn't work again shortly after:

1. I removed the stable release, installed the nightly via Droidify, opened it, went to edit then add a widget, tapped on a random potential widget, saw the 'Create widget and allow access' screen, tapped through it, saw business calendar 2's widget configuration screen for the widget and figured great it works now. I didn't end up creating the widget and backed out (wanting a different one). Afterwards I am unable to able to create a widget again (wouldn't see the create widget and (...) pop up, wallpaper flashes, back to widget selection screen. Same applies to WhatsApp.
2. I uninstalled nightly, reinstalled. Same behaviour where I can't add this. Tried stopping, clearing cache + data for business calendar.  

Maybe the issue is with that permission screen as the widgets that work don't have it?

**Comment by MM2-0** [comment]
I may have found the issue.

Can you try this:
[app-default-release.zip](https://github.com/MM2-0/Kvaesitso/files/12833368/app-default-release.zip)

**Comment by kostaj** [comment]
Works for me!  I tried adding and removing a few widgets but including backing out of the menu. Thanks again for looking into this.

**Comment by lgwapnitsky** [comment]
That did it for me. I still have a broken widget, but that's not on you

**Comment by GittyMac** [comment]
This still doesn't seem to fully fix widgets. I tried adding the Smartspacer widget, and applying just goes to the widget selection screen. The widget works on other launchers however.
