### ISSUE TITLE
Search delay when using "Launch on enter"

### ISSUE THREAD

**Issue by Sir-Photch** [MM2-0/Kvaesitso#559]
Currently the UI flickers a little bit when you enter a search term, since it is redrawn with every keypress. This is especially noticeable, when a search term only matches the first default quickaction. 

I suggest we add a small delay that needs to pass after a keypress, which the UI waits for and that is reset if another keypress is registered within that delay.

This delay would of course need some tuning, not to hinder UX too much in case search-results take too long to show up. It would probably integrate with haptic feedback (#532) nicely, that is triggered when search-results are updated.

How does this sound to you? Or is there a better way to do this?

**Comment by MM2-0** [comment]
I don't think a delay would help here. The flicker occurs because the list of search results is cleared everytime a new search is executed, so there are 0 results for 1 or 2 frames. We need to make sure to await the first resulte before we update the UI, this should get rid of the flicker.

**Comment by Sir-Photch** [comment]
So to me it seems like the issue is a little bit simpler.
I am playing around with the `searchJob()`-Function and removing the line `bestMatch.value = null` before executing a search query already resolves the flickering, albeit with other issues occurring then.

https://github.com/MM2-0/Kvaesitso/blob/aa0447de7a398411bb51c43865f1e0edccb189f5/app/ui/src/main/java/de/mm20/launcher2/ui/launcher/search/SearchVM.kt#L102-L107
