### ISSUE TITLE
Frequently used apps are not appearing

### ISSUE THREAD

**Issue by starryveshch** [MM2-0/Kvaesitso#56]
When the grid column number equals the count of favorite apps, then the frequently used apps are removed from the favorite section.

Screenshot of 4 column grid layout with 4 favorite apps,
![4_column_layout](https://user-images.githubusercontent.com/55920099/161593952-40f2df7f-f12a-4d64-8521-15a6f73e75ec.jpeg)

Screenshot of 5 column grid layout with 5 favorite apps,
![5_column_layout](https://user-images.githubusercontent.com/55920099/161593468-7d3320a0-4619-451f-9535-fd59c257bba1.jpeg)

**Comment by MM2-0** [comment]
This is the intended behavior. The last row of pinned items will be filled up with frequently used items. If it is already full, no frequently used items will be shown. If you want more, you should pin them. Do you think it would be better to always have one extra row of frequently used items?

**Comment by starryveshch** [comment]
> This is the intended behavior. The last row of pinned items will be filled up with frequently used items. If it is already full, no frequently used items will be shown. If you want more, you should pin them. 

The issue is that when I pinned 3 items on a four column layout, it displayed two rows of applications.

- First Row - Mixture of pinned and frequently used applications
- Second Row - Full of frequently used applications

When I pinned the fourth one, the second row just disappeared. Which made it look like it was some kind of bug.

> Do you think it would be better to always have one extra row of frequently used items?

It might be good, but I think it would be better if we could customize the count of frequently used apps that are displayed in the favorite section. So that even if I don't need that functionality, I can set the count to 0.

**Comment by MM2-0** [comment]
>  - First Row - Mixture of pinned and frequently used applications
>  - Second Row - Full of frequently used application

> When I pinned the fourth one, the second row just disappeared. Which made it look like it was some kind of bug.

Oh, that looks like a bug indeed

**Comment by MM2-0** [comment]
> It might be good, but I think it would be better if we could customize the count of frequently used apps that are displayed in the favorite section. So that even if I don't need that functionality, I can set the count to 0.

The idea was that if you don't want any frequently used items in your favorites, you could simply pin as many items as needed to fill the row.

**Comment by starryveshch** [comment]
> The idea was that if you don't want any frequently used items in your favorites, you could simply pin as many items as needed to fill the row.

I like to keep my favorite apps list as short as possible, and I consider these frequently used apps to be suggestions that can be pinned if necessary. So if I restrict myself to five strictly essential apps, then I will see three apps being suggested when I don't want them.

This is [similar to how the Niagara launcher](https://help.niagaralauncher.app/article/103-suggestion-algorithm) does it. So I was expecting some options to turn off suggestions for frequently used apps.

**Comment by starryveshch** [comment]
> > * First Row - Mixture of pinned and frequently used applications
> > * Second Row - Full of frequently used application
> 
> > When I pinned the fourth one, the second row just disappeared. Which made it look like it was some kind of bug.
> 
> Oh, that looks like a bug indeed

This seems to be fixed in recent versions. I'm closing this now.

> > Do you think it would be better to always have one extra row of frequently used items?
> 
> It might be good, but I think it would be better if we could customize the count of frequently used apps that are displayed in the favorite section. So that even if I don't need that functionality, I can set the count to 0.

Also, thanks for adding an option to turn off frequently used apps from the favorite section.
