### ISSUE TITLE
Use color from dynamic color scheme for clock

### ISSUE THREAD

**Issue by Fxsch** [MM2-0/Kvaesitso#563]
On the lockscreen, a color from the dynamically generated color scheme is used, as you can see here:
![Screenshot_20231008-130006_Kvaesitso](https://github.com/MM2-0/Kvaesitso/assets/77849217/27308e23-e3e9-4a72-bc09-d2ebeea74149)

I think using this color for the clock on the home screen would look better as well and it would fix the issue of it being hard to read when the wallpaper has something white (or almost white) under it. Example:
![Screenshot_20231008-130025_Kvaesitso](https://github.com/MM2-0/Kvaesitso/assets/77849217/636de54f-da7d-4f05-9189-0215bb003103)

**Comment by laaledesiempre** [comment]
> Do you mean the widgets under the clock?

no, the card behind everything, the ones you can set opacity, rounded borders, and more

**Comment by MM2-0** [comment]
> no, the card behind everything, the ones you can set opacity, rounded borders, and more

Cards already use dynamic colors:

![Screenshot_20231011-220753_Kvaesitso](https://github.com/MM2-0/Kvaesitso/assets/15646950/a407839f-b36a-4e76-a4a1-d988412e455b)

But if you want a stronger effect, you can create a custom color scheme (duplicate the default one) and tweak the surface color.

**Comment by quazar-omega** [comment]
Is there already a way to change the clock's color manually, too?

**Comment by MM2-0** [comment]
It's one of these colors:
- OnPrimaryContainer (dark color scheme): if launcher is in dark mode and you are using a dark wallpaper
- PrimaryContainer (light color scheme): if launcher is in light mode and you are using a dark wallpaper
- PrimaryContainer (dark color scheme): if launcher is in dark mode and you are using a light wallpaper
- Primary (light color scheme): if launcher is in light mode and you are using a light wallpaper

You can customize each of these colors using a custom color scheme.

**Comment by Fxsch** [comment]
You can already change the clock color without making a custom palette, this feature has been implemented

**Comment by quazar-omega** [comment]
Oh, my bad then, is it in 1.28 already? The only options I could see for the clock color were:
- Standard
- Material You
- Outlined
- OnePlus

**Comment by Fxsch** [comment]
Material You is the option you're looking for

**Comment by Fxsch** [comment]
Or do you want to set a custom color? I understood you're question as wanting the clock to use the dynamic colors, which would be that option.

**Comment by quazar-omega** [comment]
Yes, I meant custom color. You're right  mayI have confused things a little, should I open another issue for that instead?

**Comment by Fxsch** [comment]
I think so
