### ISSUE TITLE
Unable to add specific widget (meteogram weather widget)

### ISSUE THREAD

**Issue by fthiery** [MM2-0/Kvaesitso#564]
Hi, i was trying out this very promising launcher, and noticed that it is absolutely not possible to add a [Meteogram weather widget](https://play.google.com/store/apps/details?id=com.cloud3squared.meteogram), the display just flashes but nothing happens. Unfortunately that's a dealbreaker for me :-(

Note that i'm running Android 14 on a Google Pixel 7a

Let me kow what i can do to help

**Comment by kostaj** [comment]
See the build in https://github.com/MM2-0/Kvaesitso/issues/558 to solve the issue.

**Comment by fthiery** [comment]
Tried the latest nightly, fixed, thanks !

**Comment by michaelwachter** [comment]
> Tried the latest nightly, fixed, thanks !

Where are these nightly releases?

**Comment by MM2-0** [comment]
> > Tried the latest nightly, fixed, thanks !
> 
> Where are these nightly releases?

You can download them here but i wouldn't recommend them for day-to-day use: https://fdroid.mm20.de/app/de.mm20.launcher2.nightly
