### ISSUE TITLE
Unable to add some app widgets

### ISSUE THREAD

**Issue by wainscape** [MM2-0/Kvaesitso#567]
Hi all,

I have been using Kvaesitso for several months and now can't function without it. It's burned into my muscle memory. 

I recently reinstalled because I switched to the MM20 repo. I have two apps whose widgets I'd been using, but now can't seem to add them. 

I go to Edit widgets and then Add widget. No problems with the launcher widgets. I can add some app widgets. For example,  Qobuz, Amazon, Open Camera all work. On the other hand, when I tap on widgets from Calculator, FairEmail, Messaging, nothing happens. 

I feel like I must be missing something simple, but can't figure it out.

**Comment by MM2-0** [comment]
You aren't missing something, it's just broken on Android 14. I fixed it [here](https://github.com/MM2-0/Kvaesitso/issues/558#issuecomment-1751071624) but I haven't released a new version yet.

**Comment by wainscape** [comment]
Ah, ok. Thank you!
