### ISSUE TITLE
Add time limiting or usage limiter

### ISSUE THREAD

**Issue by Krishna-art-dev** [MM2-0/Kvaesitso#580]
Add inbuilt support for app usage time limiter like blloc's ratio: productivity launcher or stayfree apps's stayfree - screen time tracker Google built in digital wellbeing isn't the good one that's why . And suggested features if you like to add it :- Show a message on opening app and let user to choose how much time he wanna spend on it after that time limit comes pop another message saying you have touched your time limit do you wanna use this app for more 10 min or close the app 
@MM2-0 
Thanks

**Comment by MM2-0** [comment]
There is not really a point in making this part of a launcher:

- the launcher can't stop you from continuing using an app once you started it
- it is really easy to bypass, for example if the app is still in your recents, you can reopen it from there

I'm not even sure if apps are able to access usage stats (I think they can, but I don't know for sure)

**Comment by Krishna-art-dev** [comment]
Hmm you are right. It's really easy to bypass and apps are able to access usage stats, the app I told before (stayfree's app name stayfree screen time tracker) is an app which can access usage stats but of how much days idk I checked by installing it it shows my last 4 days app usage.

And this isn't a necessary features if a user wants it, he can able to download third party app for it

Thanks for the reply
