### ISSUE TITLE
Is Onedrive integration currently unused?

### ISSUE THREAD

**Issue by ClockGen** [MM2-0/Kvaesitso#583]
Is microsoft services related code unused? If so, can I open a PR to remove it? (only imports and references to ms-services module that'd prevent the app from compiling).

That'd make writing new patches and maintaining the F-Droid version much easier, since we have to remove already unused code every build. Ms-services gradle module will remain.

The example can be found here: https://gitlab.com/fdroid/fdroiddata/-/blob/7274f5881cef07ddf35e29d655ca14909b041efe/metadata/de.mm20.launcher2.release/remove_ms_g_2023101300.patch
(This patch removes both references to g-services and ms-services though, but I only propose to remove references to ms-services).

Also, I understand that this is a big task, but maybe as part of some future refactoring, is it possible to implement separate source sets for f-droid flavor? There's only a few of files that need to be different, and for includes gradle already allows to specify per-flavor implementations. It'd allow to completely avoid patching on F-Droid side. enable automatic updates in F-Droid and have a fully FOSS flavor of Kvaesitso.  
As an example, this app implements it: https://github.com/ThePBone/RootlessJamesDSP  
(we still have to patch out gms deps in top-level build.gradle, but this file doesn't change so we don't have to change the patch, and Fdroid flavor itself is completely free of any proprietary libraries and references to them).

**Comment by MM2-0** [comment]
I deactivated it because

1.  I had some issues with R8 and it was broken in release builds
2. the MS SDK has some questionable dependencies that I do not fully understand
3. I'm not using OneDrive anymore

I kept the code in case I need it again because I considered bringing OneDrive integration back in form of a plugin, but if I can just go back in Git history if I ever need to. So feel free to remove it if it makes your work any easier.

**Comment by ClockGen** [comment]
> About the fdroid flavor, what else do you need to patch out? Why would it be beneficial to have a separate source set?

The main benefit would be that there is a completely FOSS flavor of Kvaesitso that can be built without patching anything. Right now we have to manually create a new patch for every new version of Kvaesitso, so the app is only updated in F-Droid with manual intervention. If this would be implemented, we no longer need to create a new patch for every version and we can enable automatic updates on F-Droid side, so updates are automatically picked up and built.

Additionally, this would allow to enable [reproducible builds](https://f-droid.org/docs/Reproducible_Builds/), so your apk signed with your key is published instead.

**Comment by MM2-0** [comment]
But what else needs to be patched, apart from OneDrive?

**Comment by MM2-0** [comment]
I just decompiled version 1.28 (the build from Github, not the F-Droid build) and I can't find any of the classes mentioned [here](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/12443#note_1245670857) (even with R8 disabled). Besides, I don't quite understand, why would that be an issue? google-api-client-android itself is Apache 2.0 licensed, and the GMS classes it uses should fall under the system library exception?

OpenTelemetry, on the other hand was pulled in by the Microsoft SDK, I beliebe, and it was one of the reasons why I decided to remove the MS SDK entirely.

**Comment by ClockGen** [comment]
Perhaps, but F-Droid policy forbids usage of GMS https://f-droid.org/en/docs/Inclusion_Policy/. Also, indeed, google-api-client-android depends on gms as system library, but the resulting apk still has these classes detected: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/12443#note_1243790602 (three gplay-related exceptions), not sure where they're from. 

OpenTelemetry seems to still be present in the release apk, here's 2 scans from App Manager (it uses exodus privacy database), release version from github and f-droid version:

![ResizedImage_2023-10-22_17-22-31_1494](https://github.com/MM2-0/Kvaesitso/assets/12116711/18718e89-2ec8-4dbb-9cc4-e258e0cb24e3)

![ResizedImage_2023-10-22_17-21-44_1768](https://github.com/MM2-0/Kvaesitso/assets/12116711/126f4c71-c209-4499-a48f-60c1551f9bb7)

**Comment by MM2-0** [comment]
Oh, you are right; google-http-client pulls in a OpenCensus library. I will try to remove it:
![Screenshot_20231023_130831](https://github.com/MM2-0/Kvaesitso/assets/15646950/79dc636e-00cd-433b-a98c-9c652ae7f7ec)

As for the GMS dependencies, I cant find any in my APK. Fdroid scanner reports nothing either:

```fdroid scanner app-default-release.apk -v                
2023-10-23 13:18:24,614 DEBUG: Reading 'config.yml'
2023-10-23 13:18:24,616 DEBUG: ipfs_cid not found, skipping CIDv1 generation
2023-10-23 13:18:24,617 INFO: Scanning APK with dexdump for known non-free classes.
2023-10-23 13:18:24,971 DEBUG: > /home/***/.android/Sdk/build-tools/34.0.0/dexdump /tmp/tmpoe0vit1p/classes.dex
2023-10-23 13:18:29,860 DEBUG: > /home/***/.android/Sdk/build-tools/34.0.0/dexdump /tmp/tmpoe0vit1p/classes2.dex
2023-10-23 13:18:33,164 DEBUG: > /home/***/.android/Sdk/build-tools/34.0.0/dexdump /tmp/tmpoe0vit1p/classes3.dex
2023-10-23 13:18:36,192 DEBUG: > /home/***/.android/Sdk/build-tools/34.0.0/dexdump /tmp/tmpoe0vit1p/classes4.dex
2023-10-23 13:18:37,306 DEBUG: > /home/***/.android/Sdk/build-tools/34.0.0/dexdump /tmp/tmpoe0vit1p/classes5.dex
2023-10-23 13:18:38,440 DEBUG: > /home/***/.android/Sdk/build-tools/34.0.0/dexdump /tmp/tmpoe0vit1p/classes6.dex
2023-10-23 13:18:40,226 DEBUG: > /home/***/.android/Sdk/build-tools/34.0.0/dexdump /tmp/tmpoe0vit1p/classes7.dex
2023-10-23 13:18:42,518 DEBUG: scanner is configured to use signature data from: 'suss'
2023-10-23 13:18:42,518 DEBUG: next suss.json cache update due in 23:42:51.475383

```

Am I doing anything wrong?

**Comment by ClockGen** [comment]
Perhaps it was removed in newer versions, the scans in the original MR are from february. I will try to compile and scan on my fdroidserver.

**Comment by ClockGen** [comment]
Hm indeed,I just compiled it and it detected none of these, I then downloaded source code for these 4 libraries. It seems you've used google-api-client-android in the past: https://github.com/MM2-0/Kvaesitso/blob/fbf85ce9091104388ee08400dca0055ee39547f8/settings.gradle.kts#L211  
which indeed had a GMS dependency as shown here https://mvnrepository.com/artifact/com.google.api-client/google-api-client-android/2.0.0, and I also just checked the source code and it indeed had imports from gms and also implemented these exceptions that were detected by the scanner.   

Right now though, you depend on just google-api-client: https://github.com/MM2-0/Kvaesitso/blob/aa0447de7a398411bb51c43865f1e0edccb189f5/gradle/libs.versions.toml#L114  
which doesn't have this dependency anymore (and none in the source code as well) https://mvnrepository.com/artifact/com.google.api-client/google-api-client/2.1.2

**Comment by MM2-0** [comment]
Huh. Maybe I changed it back then when I read that discussion for the first time. Doesn't matter unfortunately. I tried to simply exclude that opencensus library, but it crashes when I try to sign in with Google. So we have to remove the Google API client libraries for F-Droid no matter what.

**Comment by MM2-0** [comment]
Btw, since you're already here @ClockGen, what is F-Droid's position on Shizuku? Its system component isn't FOSS either. Are apps on F-Droid allowed to depend on Shizuku (some users have asked for Shizuku integration)?

**Comment by ClockGen** [comment]
What do you mean by system component? I've seen some apps use shizuku library from maven, but it appears to be FOSS (at least I didn't see any proprietary deps). Shizuku app itself though has some contradicting statements that do along with apache 2, I guess that's why nobody bothered to include it in f-droid https://github.com/RikkaApps/Shizuku#license.

**Comment by MM2-0** [comment]
> What do you mean by system component? I've seen some apps use shizuku library from maven, but it appears to be FOSS (at least I didn't see any proprietary deps). Shizuku app itself though has some contradicting statements that do along with apache 2, I guess that's why nobody bothered to include it in f-droid https://github.com/RikkaApps/Shizuku#license.

I mean the Shizuku app. You have the library that you include in your app (which is FOSS afaik) but in order to make use of it, you need to install the Shizuku app as well, which isn't FOSS (because of the no redistribution clause).

**Comment by licaon-kter** [comment]
Shizuku gets https://f-droid.org/docs/Anti-Features/#NonFreeDep anti-feature

**Comment by ClockGen** [comment]
@MM2-0 Hello, as I understand, you're currently in process of splitting integrations into separate plugins? Do you plan to also separate google drive integration? If that's the case, we no longer need to patch kvaesitso and can enable automatic updates and even reproducible builds (publishing your apks signed by you).

**Comment by MM2-0** [comment]
> @MM2-0 Hello, as I understand, you're currently in process of splitting integrations into separate plugins? Do you plan to also separate google drive integration? If that's the case, we no longer need to patch kvaesitso and can enable automatic updates and even reproducible builds (publishing your apks signed by you).

Yes, that's exactly what I'm planning to do!
