### ISSUE TITLE
HERE weather provider: unparseable date

### ISSUE THREAD

**Issue by johnsto** [MM2-0/Kvaesitso#599]
The HERE weather provider appears to be stumbling on parsing dates returned by their API.

From a cursory glance at the source code, it looks like the format string is wrong as the 'Z' timezone separator is not marked as a literal (but not 100% sure as it's been a while since I did Java or Android dev!)

i.e. the format string in `HereProvider.kt` is currently `yyyy-MM-dd'T'HH:mm:ss.SSSZ` but should probably be `yyyy-MM-dd'T'HH:mm:ss.SSS'Z'` I think. 

# Stack trace 
```
java.text.ParseException: Unparseable date: "2023-10-29T06:00:00.000Z"
	at java.text.DateFormat.parse(DateFormat.java:393)
	at de.mm20.launcher2.weather.here.HereProvider.loadWeatherData$weather_release(HereProvider.kt:17)
	at de.mm20.launcher2.weather.here.HereProvider$loadWeatherData$2.invokeSuspend(HereProvider.kt:17)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:112)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:96)
```

# Device Info
```
APP.VERSION : 1.28.0
APP.VERSIONCODE : 2023101300
APP.SIGNATURE : rx1fSnL7r5/OMoFC0e1KPqTndXQ=
LAUNCHER.APP : de.mm20.launcher2.release
TIMEZONE : Europe/London
VERSION.RELEASE : 14
VERSION.INCREMENTAL : 10808477
VERSION.SDK.NUMBER : 34
BOARD : shiba
BOOTLOADER : ripcurrent-14.0-10807316
BRAND : google
CPU_ABI : arm64-v8a
CPU_ABI2 : 
DISPLAY : UD1A.230803.041
FINGERPRINT : google/shiba/shiba:14/UD1A.230803.041/10808477:user/release-keys
HARDWARE : shiba
HOST : abfarm-release-rbe-32-2004-00198
ID : UD1A.230803.041
MANUFACTURER : Google
MODEL : Pixel 8
PRODUCT : shiba
TAGS : release-keys
TIME : 1694688942000
TYPE : user
```

**Comment by MM2-0** [comment]
Odd. You are probably right, but then I don't understand how it worked all the time (and in fact still is working, at least for me). This wouldn't happen to have anything to do with the end of daylight saving time, would it?

**Comment by johnsto** [comment]
It's been broken for me for a few days at least, just prior to the clocks going back here in the UK. 

However you're right - it did work at least a week ago so I'm puzzled how it worked before either.

My best guess is the API maybe used to return e.g. "+0000" instead of the UTC signifier "Z", and SimpleDateFormat doesn't recognise a literal 'Z'?

**Comment by johnsto** [comment]
Oh looks like the API had an update a few days ago judging by their release notes: https://www.here.com/docs/bundle/destination-weather-api-release-notes/page/topics/overview.html

**Comment by johnsto** [comment]
On closer reading of the [SDF docs](https://developer.android.com/reference/java/text/SimpleDateFormat#iso8601timezone) I think the solution here is to use 'X' not 'Z' as RFC822 ('Z') doesn't support the 'Z' UTC identifier, ironically.
