### ISSUE TITLE
[feature request] horizontal widget resizing

### ISSUE THREAD

**Issue by J4gQBqqR** [MM2-0/Kvaesitso#6]
Currently only widgets horizontally fully width on the screen show up in the widget picker. This greatly limits available widget amount.

Can the launcher support horizontally resizing of widgets to make use of some other widgets that are not full width by default?

**Comment by godalming123** [comment]
Vertical resizing would also be nice as some widgets have a 1:1 aspect ratio but the card for them is more like 3:2 so they get bigger padding on the left and right then on the top and bottom

**Comment by acress1** [comment]
Hi,
to be closed ?:)
++
