### ISSUE TITLE
Can't uninstall work profile apps

### ISSUE THREAD

**Issue by starryveshch** [MM2-0/Kvaesitso#60]
Uninstalling a work profile app is not working and if I had a similar app installed in the normal profile, then that app is uninstalled instead of the work profile app.

**Comment by MM2-0** [comment]
Oh, not good. Thanks for the report.

**Comment by MM2-0** [comment]
I haven't found a way to uninstall apps cross-profile (I know that it is somehow possible, it works in other launchers), so I have disabled the uninstall button for work profile apps. You will be able to uninstall them from the app info screen (which is currently broken as well, but I have fixed that)

Closed in d8b6175.
