### ISSUE TITLE
Add "Edit Widgets" option to hamburger menu of search bar when button is deactivated

### ISSUE THREAD

**Issue by Fxsch** [MM2-0/Kvaesitso#603]
I think it would make sense to add an option to edit the widgets to the hamburger menu, that is on the right side of the search bar when the `Edit Widgets` button is deactivated.

**Comment by stardomains3** [comment]
I second this. I like not seeing that button on my home screen. But it seems you need to re-add it to edit widgets and delete it after finishing editing the widgets.
