### ISSUE TITLE
[Feature] Allow to alias apps (for example `yt` for `YouTube`)

### ISSUE THREAD

**Issue by leleogere** [MM2-0/Kvaesitso#605]
I would be a nice addition to be able to create aliases for some apps. For exemple, I would like that when I search for `yt`, the app `YouTube` would show up, or `fb` for `Facebook`.

For now, we can add a tag `yt` for `YouTube`, but it feels wrong as it means creating a lot of one-app tags.

**Comment by MM2-0** [comment]
Tags are the intended way to do this. What's wrong with one-app tags?

**Comment by leleogere** [comment]
I feel like tags are more like "categories", like I would create a tag #video for YouTube, VLC and other video players. Or a tag #messages for WhatsApp, Messenger, Telegram... Having tags to create aliases for single apps seems more like a workaround than a real solution.

But that's only my impression, and I may be wrong!

**Comment by MM2-0** [comment]
Tags are intended to be a tool to add additional keywords to search results. There is no "right" or "intended" way to use them, it's up to the user.
