### ISSUE TITLE
[Feature Request]Application drawer: Chinese apps are sorted with English apps

### ISSUE THREAD

**Issue by labrusca** [MM2-0/Kvaesitso#61]
like [lawnchair](https://github.com/LawnchairLauncher/lawnchair) did

**Comment by MM2-0** [comment]
Could you please elaborate? Do you mean that Chinese apps should be sorted according to their pinyin transliteration instead of putting them first?

**Comment by labrusca** [comment]
> Do you mean that Chinese apps should be sorted according to their pinyin transliteration instead of putting them first?

Yes, that's what I really mean.
