### ISSUE TITLE
very very slow on GrapheneOS pixel 7 pro and pixel 5

### ISSUE THREAD

**Issue by kuvaldini** [MM2-0/Kvaesitso#613]
interface is laggy on my two pixels with Graphene OS installed. I did not test it on stock FW. 
It looks like 3 to 7 FPS when scrolling.

**Comment by jellytail** [comment]
Same issue on Pixel 6. I believe switching launchers, force stopping the app and clearing cashe, then resetting launcher fixed it. 
Or make a backup and reinstall.

**Comment by TheBready** [comment]
I have the same issue here. I hope there is a fix for it.

**Comment by Rolv-Apneseth** [comment]
I believe there's a couple issues open about this already, like #555 and #257 (and potentially #577). It seems to happen after an update, at least in my case. Only backing up and re-installing fixes it for me, but isn't ideal because you have to set up all your custom widgets again

**Comment by Rolv-Apneseth** [comment]
I don't think so. I was going to, but saw the issue already open here and it appears people with other OS's are having the same problem

**Comment by Doc-4** [comment]
I have this issue as well on a Pixel 8 Pro with GOS. Something that I have found drastically improves performance is disabling any weather integration, or rather never setting it up at all. It also just so happens that using automatic location, instead of set location, seems to result in weather not working at all in the first place. I would disable it for now, hopefully the developer can look into exactly why it seems to perform so badly. My last phone had a Snapdragon 855 Plus and it performed better with weather enabled than the Pixel 8 Pro does with it disabled.

**Comment by Doc-4** [comment]
I've also noticed that this gets much worse the more tasks are running on the phone at the time. It could be a performance bottleneck or a bug causing one. It may not be tied specifically to the pixel but also possibly the difference in processors from other phones. Or maybe it really is GrapheneOS, but I've tested it with all enhanced security features off for compatibility, and the issue still shows up. Makes me wish I had tested stock pixel first to be sure. 

I don't know enough about the things involved to try to troubleshoot the cause, but I'm open to collecting logs to help debug this, or something of that nature.

**Comment by Rudd-O** [comment]
Tested workaround without reinstall:

1. Go to Settings and find Default home app.  In that panel, change the default home from Kvaesitso to Launcher.
2. Find Kvaesitso in the settings and do the following: force stop the app, then delete its cache.
3. Reboot the phone!  This is key.
4. After reboot, wait (could be a while) until GrapheneOS notifies that apps have been optimized, and to tap the notification to restart the apps.
5. Go back to Settings -> Default home app, and change back to Kvaesitso.

Presto, smooth and buttery Kvaesitso again.

This indicates there is definitely some bug somewhere at the intersection of GOS and Kvaesitso, but who's to say that this won't impact future vanilla and vendor Androids down the road, given that GOS is constantly upstreaming improvements into AOSP?

**Comment by Doc-4** [comment]
Yep, restarting in between fixed it for me too, at least for now. Further reboots haven't broken it, lets hope it stays that way

**Comment by exstntlmsnthrp** [comment]
I can confirm, I too was finally hit with the horrible lag on GrapheneOS on the update I got today. 

However, the solution recommended by @Rudd-O was successful! Now Kvaesitso is smooth and beautiful again. 

I'm assuming it's something with GrapheneOS. However, I did wonder if the way that caching is implemented in Kvaesitso has anything to do with it? Given that clearing the cache and rebooting ultimately resolved the problem. 

@MM2-0 is there any chance that could have anything to do with this? Or is it all related to Graphene's method of app hardening?

**Comment by Greysys** [comment]
> Tested workaround without reinstall:
> 
> 1. Go to Settings and find Default home app.  In that panel, change the default home from Kvaesitso to Launcher.
> 2. Find Kvaesitso in the settings and do the following: force stop the app, then delete its cache.
> 3. Reboot the phone!  This is key.
> 4. After reboot, wait (could be a while) until GrapheneOS notifies that apps have been optimized, and to tap the notification to restart the apps.

I managed to do everything up to this point. I don't understand though, grapheneOS never optimises apps for me, or at least I'm not receiving any notifications related to app optimization. Is there a setting I need to turn on to get this to work? Thanks.

**Comment by chaptergy** [comment]
I've taken a look at the system trace, and it seems drawing a single frame in the app drawer takes about 200ms:
![image](https://github.com/MM2-0/Kvaesitso/assets/26956711/8ffbdc22-892e-4190-9529-6c03e4c7ebcc)

**Comment by Greysys** [comment]
I have managed to work around the lag also by setting the AOSP launcher as default, and force stop/delete the cashe BEFORE restarting the system following the GOS update. Unfortunately, this is the only way to not get the launcher incredibly laggy. It may be indeed that GOS is failing to optimize Kvaesitso properly.

**Comment by Greysys** [comment]
> Has been fixed for the next release of GrapheneOS

Much appreciated, Daniel. Excited to see how it turns out on the next update.

**Comment by MM2-0** [comment]
> The reason it happens for this app in particular is because no baseline profile is included. This could be included to improve performance outside GrapheneOS and also for the first boot of a new update on GrapheneOS before the background app compilation finishes after booting:
>
> https://developer.android.com/topic/performance/baselineprofiles/overview

Can you include baseline profiles in APKs? I always thought you'd have to distribute your app on Google Play to make use of this.

**Comment by Sir-Photch** [comment]
I can say that after the current GOS update, the issue seems to be gone. Hooray! This Issue can probably be closed.

**Comment by kuvaldini** [comment]
thank you very much
i love GOS
you make it better
