### ISSUE TITLE
Use `mutableStateListOf<Searchable>()` instead of `mutableStateOf<List<Searchable>>` in `SearchVM`

### ISSUE THREAD

**Issue by Sir-Photch** [MM2-0/Kvaesitso#617]
Is there a specific reasoning behind not using a state-list in searchvm over a mutable state that contains a list? If I understand correctly, this would make it possible to `.animatePlacement()` of search result items, by changing the list contents, instead of re-assigning the list that is wrapped by a `mutableState`.

https://github.com/MM2-0/Kvaesitso/blob/5a7600a418a25ca44fc042f7a0d60ed7a2a88565/app/ui/src/main/java/de/mm20/launcher2/ui/launcher/search/SearchVM.kt#L59-L69

Even without using `.animatePlacement()`, this way we should be able to just directly modify the lists with the results of `searchService`, instead of creating new lists.

**Comment by MM2-0** [comment]
You might be right. I always forget that `StateList` and `StateMap` exist. But the reason I don't use `animatePlacement` is that the card background is part of the items and that animating them would rip holes in the background.
