### ISSUE TITLE
[bug] Crashes when scrolling in "edit favorites" menu

### ISSUE THREAD

**Issue by radeeyate** [MM2-0/Kvaesitso#624]
Kvaesitso (Nightly) crashes when scrolling in the "not pinned - frequently used" section of the edit favorites menu.
https://github.com/MM2-0/Kvaesitso/assets/124477460/7120da0f-ce79-498e-9a31-9fa1fda4e758

**Comment by MM2-0** [comment]
Try settings > debug > clean up database

**Comment by radeeyate** [comment]
Thanks, that fixed it.
