### ISSUE TITLE
Quick access to website when swiping to the side

### ISSUE THREAD

**Issue by Fxsch** [MM2-0/Kvaesitso#642]
I would like it if I could swipe to the side to quickly have access to my Home Assistant dashboard, that's why I'd like the option to specify a website that can be accessed that way by utilising the system webview. 

Here's a video demonstration to explain it better:

https://github.com/MM2-0/Kvaesitso/assets/77849217/4522077a-cb88-4643-942e-fdb54b6fc257

It would also be useful if an app could be placed there instead of a website but I don't know if that's even possible. For my use case it doesn't matter tho because the Home Assistant app and the web interface look the same anyway.

**Comment by MM2-0** [comment]
Can't you just install the Home Assistant app, and set swipe left or swipe right gesture action to open that app?

**Comment by Fxsch** [comment]
Sorry, I didn't know this existed, should have probably looked first
