### ISSUE TITLE
Allow renaming or hiding the Favorites tab beneath the Favorites list when tags are enabled. 

### ISSUE THREAD

**Issue by xusiai** [MM2-0/Kvaesitso#645]
When the Favorites app list is pinned above the app drawer (settings > search > favorites) in combination with tags the _Favorites_ tab/label beneath the Favorites app list takes up a lot of space. I would like to be able to either hide it or rename it in order to allow for additional space for more visible tags without having to search for them.

**Comment by jay-knight** [comment]
I use emoji instead of words for my tags which take up less room and are easier for me to identify at a glance. It would be nice to have the favorites button just be a star without the text label.

**Comment by exstntlmsnthrp** [comment]
> I use emoji instead of words for my tags which take up less room and are easier for me to identify at a glance. It would be nice to have the favorites button just be a star without the text label.

I strongly support this idea. I also use emoji for tags and would love to see favourites just be a star. 

I would also like to be able to hide favourites from the app drawer, similar to what can be done with tags. 

Why can't favourites be treated like any other tag and have all the same features? And why can't tags have all the same features as favourites? That just seems like a simpler solution to me. 

@MM2-0 is there any specific reason why tags and favourites have different feature sets?
