### ISSUE TITLE
Keep up the great work going 🙏

### ISSUE THREAD

**Issue by mhdsnj** [MM2-0/Kvaesitso#65]
Thanks to everyone behind this wonderful project and please keep those updates coming as it is a bit rough around the edges. THANK YOU once again!! ❤️🙏

**Comment by MM2-0** [comment]
Thank you ❤️

>as it is a bit rough around the edges

Do you have some examples? (I'm aware that it is far from perfect but some fresh eyes / other users' perspectives are always helpful to find those little details that you stop noticing once you get used to them)

**Comment by mhdsnj** [comment]
Glad to hear from you! 

Sure here are a few examples!

1. I'm getting an empty block when I search for a contact:

![1.jpg](https://user-images.githubusercontent.com/100271889/163881293-9f6f5987-d00f-48a3-b09f-71e599c8647e.jpg)


2. This is what I get when clicking on the date widget:

![2.jpg](https://user-images.githubusercontent.com/100271889/163881987-9bf90905-45e1-426d-89d2-00dc7c34d7f3.jpg)

It would've been nice to either get taken to the default calendar app or to be able to set it to do nothing when clicked


P.S. I'm really sorry if I seem too nit picky.. I just really want to see this project to be at it's best and you to succeed. ❤️

**Comment by MM2-0** [comment]
Thanks, appreciate it.

> I'm really sorry if I seem too nit pick

Don't worry, that's exactly the kind of things I've asked for.

> It would've been nice to either get taken to the default calendar app or to be able to set it to do nothing when clicked

This is what should happen. When you click on the date in the clock widget or on the little arrow icon in the calendar widget, you should get taken to the default calendar app. May I ask, what calendar app you are using? Also what is that app that is launched instead?

**Comment by mhdsnj** [comment]
I use Proton Calendar. It launches this (https://www.f-droid.org/packages/at.tomtasche.reader/)

**Comment by mhdsnj** [comment]
It would also be nice to disable the clock completely if you don't need it as right now even if you chose the option of not having one on the home screen clicking on that area would still open the clock app. I'm sure y'all are trying to make this better and these are just my humble suggestions...❤️🙏

**Comment by MM2-0** [comment]
Oh, I didn't realize, that's definitely not how it's supposed to be, thanks for the report

**Comment by mhdsnj** [comment]
![1.jpg](https://user-images.githubusercontent.com/100271889/165642557-5b4f123c-9cfd-4931-a9d8-f7478335ba87.jpg)

How to read time from this?. Thank You!.

**Comment by MM2-0** [comment]
It's a binary clock.
Hours and minutes are both converted to [binary](https://en.m.wikipedia.org/wiki/Binary_number). A light square stands for 1, a dark square for 0.

The first 4 squares represent the hour (in 12-hour format):
0010 -> 0*8 + 0*4 + 1*2 + 0*1 = 2

The last 6 squares represent the minute:
100011 -> 1*32 + 0*16 + 0*8 + 0*4 + 1*2 + 1*1 = 35

So the time is either 02:35 or 14:35.

Tip: if you want to convert a binary number to decimal, you can type the binary number prefixed with "0b" into the search bar, for example "0b100011"
