### ISSUE TITLE
Notification badges not working and issues with the music widget 

### ISSUE THREAD

**Issue by KOC11** [MM2-0/Kvaesitso#657]
Notification badges on application icons don't appear when i use kvaesisto launcher on my Samsung galaxy A03 core and also the music widget seems to have issues when I press play on the music widget before opening the music app first it doesn't work

**Comment by exstntlmsnthrp** [comment]
I can confirm the media widget has not been working since the recent update.

**Comment by KOC11** [comment]
What about the notification badges issue, will i be helped

**Comment by KOC11** [comment]
Will notification badges issue on Samsung galaxy A03 core be fixed in the
next update?
