### ISSUE TITLE
Widget Options bug

### ISSUE THREAD

**Issue by DumbledoreCalrissian** [MM2-0/Kvaesitso#658]
Expected Behaviour - Widget Options shows up.

Observed Behaviour - Nothing happens when tapping on widget.

I cannot add any widget with options, it bugs out. See the attached gif. The gif shows different widgets offered by an app called 'Yearly Progress'. When tapping the events progress widget, it should show me a menu/screen asking for which event. But this doesn't happen. 
On the other hand, the monthly progress widget has no such options menu/screen, so that works properly.

https://github.com/MM2-0/Kvaesitso/assets/97137197/a8244d30-f2d0-41a5-8d42-61d5936c8407

**Comment by curp2** [comment]
I had this behavior (The OP issue, not the permissions problem) on 1.28.0 but not on the nightly build. I'm not sure where it was fixed.

**Comment by DumbledoreCalrissian** [comment]
This is fixed in 1.28.0

**Comment by MM2-0** [comment]
Reopening because there are still widgets that don't work, for example Smartspacer.
