### ISSUE TITLE
[Feature request] Be able to hide applications in the drawer

### ISSUE THREAD

**Issue by sandorfimarci** [MM2-0/Kvaesitso#67]
The title says it all. There are a lot of unnecessary application and it would be nice if we could hide these applications.

**Comment by MM2-0** [comment]
Do you mean something like this?
![Screenshot_20220426-114753_Kvæsitso~3](https://user-images.githubusercontent.com/15646950/165273262-9bbe3da0-927b-4ccd-ab54-877ec137df55.png)

**Comment by sandorfimarci** [comment]
Ohh. Okay, I didn't find this option. My bad.
But it would be nice to do it from a list (like uncheck if you want the hide the app, leave checked if you want to keep it visible), but this is not a must-have, so I can live without it.

Thanks again, and keep this project going. It has huge potential.

**Comment by MM2-0** [comment]
Not a bad idea, I might add this later. The reason I've opted for this solution is that you can not only hide apps but also exclude other things (contacts, files, …) from the search results and it wouldn't make sense to have a list where you can uncheck every single possible search result. But for apps it would make sense, I agree.

**Comment by sandorfimarci** [comment]
Implemented in Version 1.11.0.
