### ISSUE TITLE
[Feature request] One tap on the home screen to search

### ISSUE THREAD

**Issue by sandorfimarci** [MM2-0/Kvaesitso#69]
One tap on the home screen (empty space) could open the keyboard and launch search.
It would make the whole process much faster.

**Comment by MM2-0** [comment]
Would it really? Is tapping that much faster than swiping?

**Comment by sandorfimarci** [comment]
I slept on it and thought that the whole gesture-based system could be rethought.
It could be set by the user (of course there will be a default solution). For example:
Swipe down: Open notification bar
Swipe up: Widgets
1 Tap: Open app drawer / search
2 Tap: Lock the screen
(Maybe left and right swipe can be added as well.)

So the user could decide what he/she likes.
(Maybe with that, the #39 would be easier to solve (let the user decide [about that](https://github.com/MM2-0/Kvaesitso/issues/39#issuecomment-1069476926)).

What do you say? (It is just a brainstorming, but for me personally would be useful)

**Comment by MM2-0** [comment]
Single and double tap at the same time is suboptimal. Either you need to delay the reaction for the single tap (wait if there is a second tap) or you open the app drawer immediately and lock the screen if there is a second tap within a set time but that could potentially lead to accidential screen locks if you tap to open the search and then tap again to launch an app.

**Comment by sandorfimarci** [comment]
I've never implemented anything like this before but I guess that GestureDetector does the job for you.
[onSingleTapConfirmed ](https://developer.android.com/reference/android/view/GestureDetector.SimpleOnGestureListener.html#onSingleTapConfirmed(android.view.MotionEvent))and [onDoubleTap ](https://developer.android.com/reference/android/view/GestureDetector#setOnDoubleTapListener(android.view.GestureDetector.OnDoubleTapListener))could work in my opinion.

[A sample code on developer.android.com.](https://developer.android.com/training/gestures/detector#detect-all-supported-gestures)

Maybe you're right but in other launchers they are implemented so I guess it is possible. (Like in KISS)

**Comment by sandorfimarci** [comment]
I see what you say, but probably the GestureDetector can handle this "issue". I would say give it a try if you have enough time and enable it as an experimental feature. (Or I can implement it but not in the near future).

Usability is obvious to me (in other launchers), so I have no problem with it. And I don't think other users will either or if they had a problem, developers wouldn't implement it in other launchers.

Here you can see KISS's [implementation](https://github.com/Neamar/KISS/blob/2d93134980bb70fb82d16acb1a082bf4fcc900a1/app/src/main/java/fr/neamar/kiss/forwarder/ExperienceTweaks.java). Starting at line 78. (And [this one ](https://github.com/Neamar/KISS/blob/master/app/src/main/java/fr/neamar/kiss/utils/LockAccessibilityService.java)is necessary too to lock the screen.)

**Comment by MM2-0** [comment]
Oh, my bad, I didn't see that. onSingleTapConfirmed looks promising indeed. I currently don't have much time but I'll look into it later.

**Comment by sandorfimarci** [comment]
Maybe it worth to consider to implement single tap [in this ticket](https://github.com/MM2-0/Kvaesitso/issues/120) as well.

**Comment by MM2-0** [comment]
You're right. I'm closing this issue in favor of #120
