### ISSUE TITLE
[Feature Request] Search on apps integration with Google Maps

### ISSUE THREAD

**Issue by Wv369** [MM2-0/Kvaesitso#691]
As the title says, add the possibility to create a quick action on the searchbar for searching on Google maps, feel like that one is quite useful.

**Comment by MM2-0** [comment]
Should be possible by adding a web search with `https://www.google.com/maps/search/${1}` as its URL. Unless I misunderstood what you meant?

**Comment by Wv369** [comment]
Oh I thought this would open the browser version, but it opens the app! Didn't think it would work like that, thanks. I'm so sorry for bothering.

**Comment by MM2-0** [comment]
It opens the app if the apps support it. Which isn't always the case (looking at you, Google app), but it's always worth trying.
