### ISSUE TITLE
[Bug/feature request?] Add an animation for predictive back gestures

### ISSUE THREAD

**Issue by mbestavros** [MM2-0/Kvaesitso#692]
[Predictive back](https://developer.android.com/guide/navigation/custom-back/predictive-back-gesture) is a fairly new Android feature that (on stock launchers) provides a nice animation when a back gesture takes the user back to their homescreen. Kvaesitso does not currently handle these gracefully - the transition is fairly janky, as demonstrated below:

https://github.com/MM2-0/Kvaesitso/assets/10786787/a82fc567-3a96-4ca7-a65c-e90ccb157fdd

Kvaesitso should add support for the new gesture.

**Comment by mbestavros** [comment]
I noticed that there was a mention of predictive back not being implemented yet in https://github.com/MM2-0/Kvaesitso/issues/578, so I figured this could be a more direct tracking issue.

**Comment by MM2-0** [comment]
I noticed this as well, but I'm not aware of a better way to handle this. To me this looks like a typical Google move to "forget" that 3rd party launchers exist. Or do you know of any 3rd party launcher that does it better?

**Comment by mbestavros** [comment]
> Or do you know of any 3rd party launcher that does it better?

Unfortunately not. A quick survey of Nova Launcher, Niagara, and Lawnchair indicate they all share the same issue, so it seems like it's indeed an upstream bug.

As a workaround, users can disable predictive back animations in developer settings (at least on a Pixel). It sucks that we have to lose such a nice QoL feature, though.

**Comment by MM2-0** [comment]
So I've upgraded to Android 14 now and what I noticed is that when you reboot your device after changing your launcher to a third party launcher, the predictive back animation from app to home screen gets disabled.  Which isn't great, of course, but at least not as bad as in your video. And at least predictive back within apps still works.
