### ISSUE TITLE
tag widget has lots of space

### ISSUE THREAD

**Issue by basings** [MM2-0/Kvaesitso#696]
![Screenshot_20240220-080708](https://github.com/MM2-0/Kvaesitso/assets/92867705/dff343ab-f296-46f5-84a7-e7860d9542f2)
![Screenshot_20240220-080655](https://github.com/MM2-0/Kvaesitso/assets/92867705/9ca00428-cfb6-47b0-b889-16b0ca1f7c13)

The second image shows the collapsed state where there is a lot of unused space. 

I'd love to see it being more compressed.

**Comment by MM2-0** [comment]
Fixed in 1.29.1
