### ISSUE TITLE
[bug] Themed icons disable after restart

### ISSUE THREAD

**Issue by n3rd3x3** [MM2-0/Kvaesitso#70]
After restarting with themed icons setting on, all of the icons revert back to being not themed. The only way to resolve this currently is to toggle themed icons off and then back on after every restart.

**Comment by shruuub** [comment]
Did you check if you have the latest version? Had the issue a while ago, but it fixed itself after an update. Otherwise, it's usually the icon provider not starting after a restart/power on.

**Comment by n3rd3x3** [comment]
Yep, I am currently on the latest version. Other launchers (Pixel launcher etc,) do not seem to have this issue, so I am assuming it does not have to do with the icon provider.

**Comment by MM2-0** [comment]
I can't reproduce this but I may have found a possible cause for this issue so this will probably be fixed in the next update. Please report back once the update is released.

**Comment by n3rd3x3** [comment]
Sorry for the late response. Seems to be fixed for me after the newest update. Thanks!
