### ISSUE TITLE
[BUG]: Calendar widget colors look "washed out"

### ISSUE THREAD

**Issue by Robin-Sch** [MM2-0/Kvaesitso#702]
I've set my calendar color to #FF0000 (pure red). In my calendar app it also shows this pure red color, however, on the calendar widget it shows the color like some washed out lighter red.

**Comment by Robin-Sch** [comment]
FYI, this only is for red and shades of red. For green/blue it's fine.

**Comment by MM2-0** [comment]
Intended behavior, to ensure legibility.
