### ISSUE TITLE
Calendar - no events today

### ISSUE THREAD

**Issue by summoner001** [MM2-0/Kvaesitso#711]
The calendar is not working properly. It was supposed to show a full day of events today but it just said "No events today" but there are. It also incorrectly predicts the next event.

**Comment by MM2-0** [comment]
Tap edit widgets > tap on the settings icon for the calendar widget > check that your calendars are selected

**Comment by summoner001** [comment]
The calendar is correctly selected in another widget works, just not here since the update.

**Comment by summoner001** [comment]
It seems that I just had to update the calendar in google calendar. Now everything is fine.
