### ISSUE TITLE
[Feature Suggestion] UI Plugins

### ISSUE THREAD

**Issue by thornySoap** [MM2-0/Kvaesitso#718]
It's a very silly question, because it probably would need some sort of rewrite of everything, but wouldn't it be nice if there were UI plugins next to the provider plugins? So if I wanted a small tweak or extra feature that most of the people don't want I could just write a small plugin, so there is no need to build every update on my own only for the small thing. Just an idea that shouldn't be taken too seriously.

**Comment by MM2-0** [comment]
Could you give some examples what kind of plugins you would create with such an API?

It's not an easy task to transmit UI information between apps, but maybe I can think of something.

**Comment by thornySoap** [comment]
The thing I thought of was to have an option to turn the dock (and only the dock) into monochrome icons. Since for the the whole list they're either incoherent or, when forced, sometimes hard to recognize, whereas I know the apps in the dock obviously better so I don't rely on the icons and I can turn them monochrome for aestethics on the home screen

**Comment by thornySoap** [comment]
Another idea was to let the clock (and widgets) not occupy the whole page but only so much that the search widget peaks out even without scrolling like 2cm every time

**Comment by MM2-0** [comment]
I don't even know how an API that allows such a level of customization would look like.

**Comment by TimoNotThy** [comment]
> Another idea was to let the clock (and dock) not occupy the whole page but only so much that a search widget I use peaks out even without scrolling like 2cm every time

Try disabling 'fill screen height' for the clock widget and adding an empty widget between the clock and the search bar. If you tinker a bit with the widget height of the invisible widget you should be able to achieve this.

**Comment by TimoNotThy** [comment]
> > Try disabling 'fill screen height' for the clock widget and adding an empty widget between the clock and the search bar. If you tinker a bit with the widget height of the invisible widget you should be able to achieve this.
> 
> That's a cool idea, thank you. Unfortunately you can't add widgets above the clock. Your workaround would work really well with the clock beeing at the top. I even managed to get it in the middle by resizing the external clock widget. But it's not possible to have it at the bottom, is it?

It's less gracefully but you can always set the clock to empty and add another clock.
