### ISSUE TITLE
Google Gemini or ChatGPT response in home search

### ISSUE THREAD

**Issue by vikasgola** [MM2-0/Kvaesitso#722]
**Feature**
- integration of Google Gemini api or ChatGPT api in home search.
- It could really save a lot of time to have ai assistant answers in the home search itself instead of going to their respective websites.

**Suggestion for, how to achieve**
- A user should get his/her api key from `https://aistudio.google.com/app/apikey` for Google Gemini and at the backend we should be able to get a response from Google Gemini API and display it in the homepage.
- Similar thing can be done for ChatGPT.

**Comment by derei** [comment]
@vikasgola you could install the ChatGPT app and add the widget on the screen. Same goes with Perplexity.

**Comment by TimoNotThy** [comment]
This would not be a direct implementation but if you go to kvaesitso settings > Search > Quick actions, you can add in-app search as an option.

**Comment by derei** [comment]
> This would not be a direct implementation but if you go to kvaesitso settings > Search > Quick actions, you can add in-app search as an option.

That's even better indeed and would address @vikasgola request fully.
