### ISSUE TITLE
Weather widget 

### ISSUE THREAD

**Issue by tatacaw13** [MM2-0/Kvaesitso#727]
Weather widget says "no data available". Adding the manual location didn't update it either. 
![Screenshot_20240313_081703_Kvaesitso](https://github.com/MM2-0/Kvaesitso/assets/124025926/9463a0e5-ac61-456d-a15e-da1c7bf8b9ae)

**Comment by exstntlmsnthrp** [comment]
Have you tried using one of the other weather providers or tried using the experimental OpenWeathermap plug-in? 

I've had good luck since using the plug-in.

**Comment by tatacaw13** [comment]
@exstntlmsnthrp sorry for really noob question, but how do you do that?

**Comment by exstntlmsnthrp** [comment]
@tatacaw13 No problem at all. We all have to learn and easiest way to do that I'd asking questions!

First, you'll need to download and install the plug-in APK from the developer's other repo [here](https://github.com/Kvaesitso/Plugin-OpenWeatherMap).

Once installed, you'll need to enable in the plug-in settings in kvaesitso. From there, open the OpenWeathermap plug-in and it should look like this:

![Screenshot_20240313-203625.png](https://github.com/MM2-0/Kvaesitso/assets/57594290/8c9727c8-dc4b-4624-b71d-16a0ec726a5b)

Before you get much further (or possibly even before doing all of that), you will need to create a free OpenWeathermap API key. Follow the instructions [here](https://docs.openweather.co.uk/appid) and select "How to start work with our API". The instructions are very easy and the free API is more than you'll need to get the weather in kvaesitso. 

Once you have your API key, you'll need to enter it in the plug-in settings by clicking the gear in the upper right corner. 

![Screenshot_20240313-204306.png](https://github.com/MM2-0/Kvaesitso/assets/57594290/1dc717bb-e90a-4a97-bb83-6d344d4ff4c3)

The page is very simple and you just enter the API key that you created. 

![Screenshot_20240313-204449.png](https://github.com/MM2-0/Kvaesitso/assets/57594290/1fa247bd-b47e-46f0-b54a-7c67b821c971)

Click save. 

Then click on Weather integration settings. Make sure that OpenWeathermap is selected and either give permission for it to get your location or manually enter your location. 

From there or should work! Oh, I guess you should add the kvaesitso weather widget if you don't already have it. 

Let me know if you have questions or don't understand this.

**Comment by tatacaw13** [comment]
This worked!! 
Thank you so much for such a detailed explanation. It was really helpful and I learnt something new today, so i really appreciate it. 😊
![Screenshot_20240314_071447_Kvaesitso](https://github.com/MM2-0/Kvaesitso/assets/124025926/d996f062-ea14-4d71-94ff-6eeabc01cb0f)

**Comment by exstntlmsnthrp** [comment]
Brilliant! I'm glad it was successful.
