### ISSUE TITLE
Gestures (like swipe down, right, left) dont work stabily

### ISSUE THREAD

**Issue by ssolid20** [MM2-0/Kvaesitso#737]
Like a title says Gestures offered by app dont work properly. By this i mean that when you turn them on in accesability menu, they stop working after some time and need to be turned on again, even if they worked nicele before.

Poco x6 Pro , Hypero os 1.0.7

**Comment by MM2-0** [comment]
https://kvaesitso.mm20.de/docs/user-guide/troubleshooting/granted-permissions.html

**Comment by ssolid20** [comment]
Thanks a lot , It actually helped
