### ISSUE TITLE
Icons of apps bundled with bubblewrap are being cut off

### ISSUE THREAD

**Issue by BANanaD3V** [MM2-0/Kvaesitso#741]
Bubblewrap is a tool to create trusted web app. It adds a small white padding to the icon and kvaesitso does not zoom in the icon like other launchers do. Top is kvaesitso, bottom is default (asus) launcher
![image](https://github.com/MM2-0/Kvaesitso/assets/68944906/dad6474b-60a8-4c5f-9e77-21191b9d9f0b)
![image](https://github.com/MM2-0/Kvaesitso/assets/68944906/c9c72212-39e8-4472-8b22-6bd2f402bb33)

The icon itself looks like this:
![image](https://github.com/MM2-0/Kvaesitso/assets/68944906/19cc80af-91d4-4cc1-8628-f3054a533078)

**Comment by TimoNotThy** [comment]
Is there a use to the white border? If not I suggest making this a bubblewrap issue.

**Comment by BANanaD3V** [comment]
this got fixed with updating the launcher.
