### ISSUE TITLE
Send to home

### ISSUE THREAD

**Issue by ema-dg** [MM2-0/Kvaesitso#75]
Having no home means that you can't send webpages to home in browsers like Firefox, so you can't use PWA as installed apps. What about having the chance to put the in the drawer?

**Comment by MM2-0** [comment]
When you select add to home in Firefox (or other apps), it should be pinned to the favorites in the launcher. Is that not working for you?

**Comment by ema-dg** [comment]
It works fine, maybe it didn't work because I was in incognito mode. Thanks!

Il 16 maggio 2022 19:37:38 CEST, "U. N. Owen" ***@***.***> ha scritto:
>When you select add to home in Firefox (or other apps), it should be pinned to the favorites in the launcher. Is that not working for you?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/MM2-0/Kvaesitso/issues/75#issuecomment-1127951162
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
Emanuele De Grandi
-- 
Inviato dal mio dispositivo Android con K-9 Mail.

**Comment by Porrumentzio** [comment]
Hi I'm commenting on this:

For me having the PWA added to the favourites isn't working, since I use no favourites. My main five-app-bar changes with the use of the apps.

Could it be possible to have the PWA added as a normal, not favourited app?
