### ISSUE TITLE
Kvaesitso's icon search does not find all available icons within an icon pack

### ISSUE THREAD

**Issue by xusiai** [MM2-0/Kvaesitso#757]
Kvaesitso's own view of manual icon search does not find all available icons within an icon pack. For example when using the _Arcticons Material You_ icon pack you can - within the icon pack application - search and find icons for _Graphene OS_ and  _Starfield_ but these icons do not show up when searching within Kvaesitso's icon selection view and therefore cannot be selected as icons in Kvaesitso. 

I don't know how Kvaesitso handles icon search but a simple solution could be adding an option to select the icon from within the icon pack itself. This is how other launchers like Nova handles manual icon selection.

**Comment by exstntlmsnthrp** [comment]
I noticed this as well, recently. For example, the Actions You updated the icon for ICSx⁵ (and ironically there is an app name mismatch now). Searching within kvaesitso, the icon does not show up for me. But searching directly within the Arcticon app does show the icon.

**Comment by Areg472** [comment]
Same

**Comment by MM2-0** [comment]
Fixed in 9c5f1e9
