### ISSUE TITLE
App drawer stays opened after opening an app and using 'home' or 'back' gesture afterwards

### ISSUE THREAD

**Issue by resiehnnes** [MM2-0/Kvaesitso#761]
Steps to reproduce:

1. Swipe down at home screen (or tap 'search' field) to open app drawer.
2. Type in a name of an app or anything else you want to open.
3. Tap go on your keyboard.
4. After your app (or whatever it is) is opened go back home with a home or back gesture.

You will see app drawer with the input text in search field you had at  step 3.

Expected behavior is to get back to home screen after step number 4 is done, using home or back gesture + clear the search field for the next app drawer call.

Tested on two different devices, having same behavior.

Huawei P30 Pro (Android 10)
Samsung Galaxy S8+ (Android 9)

Video showing all five steps to reproduce the issue:

https://github.com/MM2-0/Kvaesitso/assets/52158526/e5f22a60-2d5f-4df0-8fe9-4a2ecf3505d5

**Comment by MM2-0** [comment]
Intended, you need to wait 20 seconds until it is closed
