### ISSUE TITLE
[BUG] Rounding Error in Calculations

### ISSUE THREAD

**Issue by Bhardwaj10Ankit** [MM2-0/Kvaesitso#777]
@MM2-0 The launcher is producing **rounding errors in mathematical calculations**. 

eg: calculations like, **100+12% answer should be 112 while the launcher gives an output =100.12**.

**Comment by Sir-Photch** [comment]
Possibly a duplicate of #554.

But also:

12 per cent -> 12 per hundred -> 12 / 100 -> 0.12
thus, 100 + 0.12 = 100.12.

Also "100 + 12%" is not typical math necessarily.

**Comment by Bhardwaj10Ankit** [comment]
@3b1b please enlighten us.

**Comment by MM2-0** [comment]
Closing this in favor of #554
