### ISSUE TITLE
Add Support for Breezy Weather Data Sharing

### ISSUE THREAD

**Issue by Humorist2601** [MM2-0/Kvaesitso#780]
Hello

Love the launcher but want to suggest a new feature. Currently Breezy Weather has a Data Sharing feature which can send the weather data to apps like [Gadgetbridge](https://codeberg.org/Freeyourgadget/Gadgetbridge) and [Generic Weather Plugin](https://github.com/pacjo/SmartspacerPlugins/blob/main/app/src/genericweather/README.md) for SmartSpacer

If this is implemented then the launcher can get weather information from Breezy Weather which include many more providers.

Thank You

**Comment by MM2-0** [comment]
That would be awesome, do you have more information on how to do that?

**Comment by Humorist2601** [comment]
Currently an issue is open on Breezy Weather's GitHub to document their weather spec [Issue.](https://github.com/breezy-weather/breezy-weather/issues/863).

We could ask papjul of [Breezy Weather](https://github.com/breezy-weather/breezy-weather/)  or pacjo of [Generic Weather Plugin](https://github.com/pacjo/SmartspacerPlugins/blob/main/app/src/genericweather/README.md) for help.

**Comment by summoner001** [comment]
Best idea ever! Can't wait for this.

**Comment by MM2-0** [comment]
https://github.com/Kvaesitso/Plugin-BreezyWeather

**Comment by Humorist2601** [comment]
Thank you so much for completing this request in such a short notice. Plugin is working awesomely
