### ISSUE TITLE
Can you make offline version of app 

### ISSUE THREAD

**Issue by Gamer750** [MM2-0/Kvaesitso#782]

**Comment by TimoNotThy** [comment]
Do you mean a version that doesn't acces the internet? There is an [android setting](https://duckduckgo.com/?q=deny+internet+acces+for+specific+app) for that.

**Comment by Gamer750** [comment]
> Do you mean a version that doesn't acces the internet? There is an [android setting](https://duckduckgo.com/?q=deny+internet+acces+for+specific+app) for that.

I know we can block internet access of apps by firewall like karma firewall and netguard . I want a version which does not access internet

**Comment by MM2-0** [comment]
No. I see no why I should maintain two mostly identical apps when you can simply disable all online features or block the app's internet access.
