### ISSUE TITLE
Media widget notification access

### ISSUE THREAD

**Issue by PRLoki** [MM2-0/Kvaesitso#784]
The media playback widget keeps wanting notification access to be activated even though this has already happened.
![Screenshot_2024-05-01-09-56-05-203_de mm20 launcher2 release](https://github.com/MM2-0/Kvaesitso/assets/168626770/9aa2319a-6e45-4fc3-a8e8-0ab7aa5a4d1d)

**Comment by PRLoki** [comment]
The same problem also exists with the notification stickers. Both options have access and everything worked. However, the prompt appeared again after a short time!
![Screenshot_2024-05-01-09-58-52-706_de mm20 launcher2 release](https://github.com/MM2-0/Kvaesitso/assets/168626770/f87ab736-f316-4a1f-94a6-de6b82393514)

**Comment by MM2-0** [comment]
https://kvaesitso.mm20.de/docs/user-guide/troubleshooting/granted-permissions.html
