### ISSUE TITLE
App drawer opens in widget edit screen 

### ISSUE THREAD

**Issue by sairamkumarm** [MM2-0/Kvaesitso#785]
**Steps to reproduce**
- click edit widgets on home screen
- swipe right/left (gesture selected) to open app drawer

Apps can be opened from here and when closed with the back button,  go back to the edit widgets option.
Didn't seem like an intended feature.

**Comment by derei** [comment]
Does it negatively impact functionality or causes bugs?
Even if may not be intended behavior, it may be useful if is not breaking anything.
