### ISSUE TITLE
Pressing the home button while app drawer is open reopens keyboard

### ISSUE THREAD

**Issue by HerrHellmus** [MM2-0/Kvaesitso#79]
With version 1.10, I notice that the home button doesn't work when the app drawer is open. I'd expect to go back to the home screen, but instead it opens or reopens the keyboard. I'm not sure whether this is a feature or a bug, but I'm not a fan of it.

**Comment by MM2-0** [comment]
it's a bug. I didn't notice because I'm not using button navigation anymore, so thanks for the report.

**Comment by Gedaliya** [comment]
Confirming that this is still an issue in 1.13.1-20.

**Comment by HerrHellmus** [comment]
Is there any timing on when this will be fixed?

**Comment by MM2-0** [comment]
Ah, sorry, I kinda forgit about this one. I'll prioritize this once I'm back from vacation.
