### ISSUE TITLE
[BUG]: Cursor goes one digit behind when setting manual dp value for widgets

### ISSUE THREAD

**Issue by AgeusG** [MM2-0/Kvaesitso#791]
As the title says, whenever I try to set a manual dp value for a widget (it happens with all types of widgets), the cursor would go one digit behind, for some reason. 

For example, if the initial value is 150 and I want to set a new value, it would delete it as it normally should, until it reaches the 1 digit. Then, it I want to set it to 160, it won't let me do it easily. It will push the cursor left to the 6 digit when I type it, and I need to place the cursor right to it to keep going. Then, when I insert the 0 digit, it would go, once again, to one digit behind.

Here's a screen recording attached showing this bug more clearly:
https://github.com/MM2-0/Kvaesitso/assets/168986614/e872955b-c57c-42eb-b391-c92fce6fdf39

If you could fix this in the next update, that would be greatly appreciated.

Have a great day,
AgeusG

**Comment by Paulchemouni** [comment]
I have the same issue
