### ISSUE TITLE
[BUG] Weird back animation 

### ISSUE THREAD

**Issue by airon-main** [MM2-0/Kvaesitso#795]
https://github.com/MM2-0/Kvaesitso/assets/122789671/62df76f4-6e74-4180-9af5-93a258ac5473

**Comment by airon-main** [comment]
device: infinix note 12 2023
android 12

**Comment by airon-main** [comment]
version: 1.13.0 Release

**Comment by UcraNerd** [comment]
Have the same issue

**Comment by aidzmtsk** [comment]
I can confirm that I'm experiencing the same issue.

Device: Poco X6 Pro 5G (Arm Mali-G615 MC6)

**Comment by Paulchemouni** [comment]
I have the same issue on m'y Samsung Galaxy S20 FE

**Comment by airon-main** [comment]
Please fix. Even the nightly still have this bug
