### ISSUE TITLE
Really slow after 1.30 update

### ISSUE THREAD

**Issue by Jojoba24** [MM2-0/Kvaesitso#797]
After updating to 1.30, the launcher is unusably slow.

**Comment by exstntlmsnthrp** [comment]
I initially noticed this as well after updating to 1.30.0. However, going to ```Settings > Debug > Clean up database``` solved the problem for me and it's back to normal now.

**Comment by Jojoba24** [comment]
I tried and it doesn't work for me.
However, clearing all app data seems to resolve the problem and recovering my old settings from a Backup I did reintroduced the problem. 

I guess I will just get a new setup for now :)

**Comment by Jojoba24** [comment]
I just changed the clock and the search bar and its laggy again :(

**Comment by MM2-0** [comment]
>    I just changed the clock and the search bar and its laggy again :(

Can you change it back and try if that fixes it? And what did you change?
