### ISSUE TITLE
Hidden apps are no longer hidden in Favourites since 1.30.0

### ISSUE THREAD

**Issue by kud** [MM2-0/Kvaesitso#799]
Hey,

Hope you're doing well.

I just wanted to let you know that starting from version 1.30.0, the hidden apps are no longer hidden in the Favorite category.

Maybe I missed something with this new version, but I've tried different methods to filter them, like adjusting filters, and still no luck.

Can you please look into this?

Thanks.

**Comment by exstntlmsnthrp** [comment]
I'm also using 1.30.0 and do not have any issues with this. Have you tried going to Settings > Debug > Clean up database? That might help.

**Comment by MM2-0** [comment]
> I just wanted to let you know that starting from version 1.30.0, the hidden apps are no longer hidden in the Favorite category.

Intentional change. Before, you couldn't hide an app from the app that was pinned to favorites, because it would remove it from favs as well. Now, this is possible.

**Comment by Sir-Photch** [comment]
Hm, I oppose this. I'm the type of guy that hides apps that I (have to) use, but don't want to use. Now, they appear in my recents. Aaahh! D:

**Comment by Apollucas** [comment]
I also oppose this. There are certain hidden apps that I have to use from time to time, but I don't want them to show up in my favorites. They're hidden for a reason. Adding an option to toggle this would make everyone happy, though!

**Comment by MM2-0** [comment]
They shouldn't appear in frequently used apps. That's a bug. They should only appear after you pinned them.
