### ISSUE TITLE
[feature request] search Chinese and Japanese by Roman characters

### ISSUE THREAD

**Issue by J4gQBqqR** [MM2-0/Kvaesitso#8]
For international users, Asian characters in search is always a painful point in open source applications. 

Can the search be extended to pinyin of Chinese and hiragana of Japanese?

For example, "gao" would match "高" in Chinese pinyin, "te" would match "て" in Japanese.

There are online libraries for these search functions for sure.

**Comment by MM2-0** [comment]
Sounds like a good idea, I can look into that though I'll probably need some help since I'm not at all familiar with Asian languages.
So I imagine there is an official mapping between Chinese/Japanese symbols and latin transcriptions? Could you give some more examples of what you would type into the search and what search results you would expect?

**Comment by J4gQBqqR** [comment]
I am not familiar with Kotlin nor Java. However, let me do some research in the next few hours try to find a usable existing implementation for you.
Thanks!

**Comment by J4gQBqqR** [comment]
OK, so here are some of my primary resources for the reserve translation (Chinese to PinYin):
******************************************************
The current most used/famous library is:
https://github.com/promeG/TinyPinyin
This library is claimed to be fast and fully featured. [Here is a brief introduction](https://blog.csdn.net/LosingCarryJie/article/details/79371960), you can Google translate it.
******************************************************
The other mentioned library is:
https://github.com/qzw1210/jpinyin
documentation: http://pinyin4j.sourceforge.net/
This one is old and probably not as feature complete as the first one.
******************************************************
There are some barebone implementation that is light but not feature complete:
https://gist.github.com/D-clock/7a6e33f42c0177439a49d85b73f1e600
An example of the usage of this is in this dialer app:
https://github.com/MoKee/android_packages_providers_ContactsProvider
They use a newer version of the same class in this file:
https://github.com/MoKee/android_packages_providers_ContactsProvider/blob/mkl-mr1/src/com/android/providers/contacts/HanziToPinyin.java
As far as I know, this class is taken out directly from AOSP. But I am not sure where to find the original class definition.
The dialer app support search Chinese contacts with pinyin and sort Chinese characters mixed with English contacts. 
For example, "高“ (with pinyin "Gao") would be sorted before George and after Franklin.
******************************************************

Google somehow supports it, I am not android developer, so the best I can find is:
https://developer.android.com/reference/java/util/Locale?hl=fi#Locale(java.lang.String)
https://developer.android.com/reference/kotlin/android/icu/util/ULocale.html?hl=ar
https://developer.android.com/reference/android/content/ContentResolver.html?hl=fi#QUERY_ARG_SORT_LOCALE
https://developer.android.com/reference/kotlin/android/provider/ContactsContract.PhoneticNameStyle?hl=ca#pinyin

**Comment by MM2-0** [comment]
Thanks for your research, I will look into it.
Just to be clear, you type either pinyin or english text, but never a mix of both? So all you have to do is try to convert the input to Chinese. If that succeeds, use the Chinese transcription as search query; if it doesn't just keep the latin letters? Also I would probably only enable this feature if the phone's locale is set to chinese. Does that make sense? Or is it common to set your phones language to english?

**Comment by J4gQBqqR** [comment]
> you type either pinyin or english text, but never a mix of both?
Under the specific use case of launcher app, I do not use mixed language, i.e. Chinese characters + emglish letters. I either use only Chinese or only English characters (pinyin or English)

> So all you have to do is try to convert the input to Chinese. If that succeeds, use the Chinese transcription as search query; if it doesn't just keep the latin letters? 
Not really. I would search Chinese characters "高" using pinyin(English characters) "gao". Or I would search "高" using "高". I would not try to convert in search.

> Also I would probably only enable this feature if the phone's locale is set to chinese. Does that make sense? Or is it common for chinese people to set their phone's language to english?
I think it would be better to enable it under all scenarios where Chinese characters are detected.  It is normal for Chinese users to apply system language to English since some app's Chinese translation are not usable at all. 
For western users, they simply should not have apps that are named in Chinese Characters, so this should be transparent to western users.
Transcode Chinese characters and index/sort/search them in pinyin by default is probably the best solution.

**Comment by MM2-0** [comment]
Ok, so currently there is a list of applications and each application has a `label` field. When the user types something in, this list of application is filtered by the search query. If I understand correctly, you would just add another field `labelLatin` which would contain the pinyin transcription (Or any other transcription in case of other non-latin-alphabets. We could even use that field to remove accents and umlauts, so even western languages would benefit from that).  Then, when the user does a search, you would just look for matches in both, the `label` and the `labelLatin` field?

**Comment by J4gQBqqR** [comment]
Sounds exactly the behavior in this feature request!

**Comment by J4gQBqqR** [comment]
I wonder if the same can be done to apply to contacts search and other search entries. But having this feature on app name search beats 100% of open source launchers solutions. As far as I know, no open source launcher supports this by now.

**Comment by MM2-0** [comment]
Probably not. The launcher does not maintain its own database for contacts, calendar, files and so on. Instead it relies on the content providers provided by the Android system. For contacts, there appears to be a phonetic name field in the contact provider db, but I don't know if this field is auto-generated or if it has to be specified by the user. Other than that, I think the only other alternative would be to transscribe the search queries and hope for the best.

**Comment by MM2-0** [comment]
I have added Pinyin support to the app search in b6f6c0c. Could you have a look whether it works as you'd expect it @J4gQBqqR?

[app-release.zip](https://github.com/MM2-0/Kvaesitso/files/8190691/app-release.zip)
(There is an APK file in this zip because I cannot upload an APK file here)

**Comment by J4gQBqqR** [comment]
Hi, thanks for the update. I've tried and verified the pinyin support work as expected.

There is one extra feature that I noticed:
The PinYin for 相机 is "Xiang Ji"
I can use "xiangji" to search for it.
I can also use "iangi" to search for it.
I can also use "angi" to search for it.

However, I cannot use "xj" to search for it.
Is this behavior intentional or unintentional?

**Comment by MM2-0** [comment]
I wouldn't say it's intentional, but that's just how the matching works (in other languages as well). It's not searching for individual characters, it's searching for substrings (plus a bit of fuzzy matching to account for typos). Searching for "yt" doesn't match "YouTube", for example, because it's not a substring. The same logic would apply to "xj" and "Xiang Ji"; it's not a substring so it doesn't match. Is this a big deal?

**Comment by J4gQBqqR** [comment]
This is not a big deal. It is just one extra feature that people use to search for PinYin: the usage of first Latin/Roman Character for fast PinYin search.

Again, not a big deal. I think the current search functionality is good. For contacts, I will need to add  phonetic name myself.

**Comment by MM2-0** [comment]
Thanks, I will leave it how it is then.

> Again, not a big deal. I think the current search functionality is good. For contacts, I will need to add phonetic name myself.

Yes, but also this is not implemented yet.

**Comment by MM2-0** [comment]
Phonetic name search for contacts has been implemented in 68cba4b. I think that's all I can do so I'm going to close this issue now.
