### ISSUE TITLE
Date-time section padding changed? (v1.30)

### ISSUE THREAD

**Issue by JetpackJackson** [MM2-0/Kvaesitso#804]
Hi, I recently updated to 1.30 and noticed that the padding on the date-time section of the launcher changed:
![ResizedImage_2024-05-07_21-18-15_2547_1](https://github.com/MM2-0/Kvaesitso/assets/88674707/489b134a-8b58-4fcb-897c-3979c23a74f7)
The picture on the left is the old padding, see the vertical bar placement.

I hesitate to mark this as a bug since I have no idea whether it was an intentional change when the new clock styles were added. And the padding also negatively affects the music widget as well in my case because it cuts off the song/artist labels much more than the older version.
If this is a feature, is it possible to re-add the old padding style as a "traditional/classic/legacy" option?
If this is a bug, what can I do to help fix it?
Thanks in advance.

**Comment by KrisadaFantasy** [comment]
@MM2-0 I'm sorry for comment in closed issue, but the padding for default layout is changes as well. I try using custom widget from clock app but I doesn't looks as neat so I have to dug up this issue.

![0](https://github.com/MM2-0/Kvaesitso/assets/85682504/a1d0ce61-3478-4e05-bbfe-78eb83822f7c)
