### ISSUE TITLE
Can't install release apk version 1.30.2 because of Play Protect

### ISSUE THREAD

**Issue by neronguyenvn** [MM2-0/Kvaesitso#807]
It shows me App blocked to protect your device, Google Play Protect.

**Comment by exstntlmsnthrp** [comment]
If I remember correctly, Google Play Protect usually has an option for you to override this and accept the risk. 

One option and in my opinion the easiest option, is to disable Google Play Protect and install the app. That opinion is considered controversial by some people. Some people will disable it to install an app and then turn it back on after it's installed. 

However, other people (like me) think that Play Protect is just Google's way of trying to prevent users from installing apps from other locations, like Fdroid or GitHub.

**Comment by 8227846265** [comment]
Can't install Version 1.30.2 because of Play Protect as well.

**Comment by neronguyenvn** [comment]
I create a empty project with AccesibilityService basic setup, it stilll faces this problem.

**Comment by MM2-0** [comment]
Should be fixed in 1.30.3 (hopefully?)

**Comment by 8227846265** [comment]
It's fixed on my end with version 1.30.3

**Comment by neronguyenvn** [comment]
can you point me how to fix it?. I got through yours from 1.30.2 but didn't see any specific code to solve this issue.

**Comment by MM2-0** [comment]
> can you point me how to fix it?. I got through yours from 1.30.2 but didn't see any specific code to solve this issue.

This is what fixes it: 055a088

And this is why it was added in the first place: #704
