### ISSUE TITLE
[Feature Request] Expandable dock

### ISSUE THREAD

**Issue by TJonCooper** [MM2-0/Kvaesitso#835]
Is it possible to add a feature whereby we can control the number of rows shown on the dock? For example, between 0-3. Thank you for such a fantastic launcher.

**Comment by derei** [comment]
@TJonCooper You can use Favorites Widget instead of dock for that. Anyway, the first row on dock is the first row on Favorites.

The only difference is Favorites has card background.

**Comment by TJonCooper** [comment]
Ah, got it. Very useful widget. Thanks!
