### ISSUE TITLE
`Location.openingHours.isOpen` fails for opening hours past midnight

### ISSUE THREAD

**Issue by Sir-Photch** [MM2-0/Kvaesitso#838]
On a monday at roughly 10PM

Shown:

![markup_1000020840.png](https://github.com/MM2-0/Kvaesitso/assets/47949835/893def19-9288-4d44-b833-0677f5b6a071)

Actually:

![markup_1000020841.png](https://github.com/MM2-0/Kvaesitso/assets/47949835/c067271d-8051-4b48-8156-4fe7aaeafcd2)

Maybe it would make sense to write some unit tests for OSM parsing?

**Comment by MM2-0** [comment]
I'd say OSM parsing is fine, but `isOpen` is buggy isn't working correctly.
