### ISSUE TITLE
[Function Request] Place small objects in two columns in the small objects interface, some small objects are relatively small and take up more space if they occupy one row.

### ISSUE THREAD

**Issue by wentywenty** [MM2-0/Kvaesitso#839]
[Function Request] Place small objects in two columns in the small objects interface, some small objects are relatively small and take up more space if they occupy one row.![Image_1715671104687.jpg](https://github.com/MM2-0/Kvaesitso/assets/63338034/89dbdb63-c945-48c8-9012-ba5ab077cb03)

**Comment by MM2-0** [comment]
Duplicate of #380
