### ISSUE TITLE
can't switch layout on Gboard using long press on spacebar

### ISSUE THREAD

**Issue by yotama9** [MM2-0/Kvaesitso#841]
Hi,

I'm using kvaesitso on Samsung S24Plus. Since yesterday (I didn't notice if there was an update), I cannot switch keyboard layout on long press. The menu opens and closes immediately. 

Switching keyboard layout using the switch key works regularly.

The interface works well on other windows.

**Comment by BlackberrieCake137** [comment]
having this issue as well. can't select languages to switch for translate either

**Comment by loulou921222** [comment]
+1, can't select languages

**Comment by BlackberrieCake137** [comment]
The issue of not being able to switch languages arises from the forced switch-to-language function the launcher now has. For example if you force the language to, say, Interlingua in your settings, your keyboard will be forced into using it, even if the language isn't on Gboard beforehand. 

This should have a toggle on and off. Forcibly changing keyboard language can be useful to many, but simultaneously a definite annoyance as in this case (and the case of one not wanting to have to press their language switch key every time they open an app)

**Comment by MM2-0** [comment]
Appears to be fixed
