### ISSUE TITLE
[Bug] Visual bug in settings

### ISSUE THREAD

**Issue by OmegaSunkey** [MM2-0/Kvaesitso#843]
Version: Kvaesitso 1.30.4 
OS: One UI 3.1
Android Version: 11

On Kvaesitso 1.30.4, there's a visual bug in settings which happens upon exiting a subsection of settings.

Footage was recorded on Kvaesitso 1.30.3 but still happens on 1.30.4.

https://github.com/MM2-0/Kvaesitso/assets/94485936/586fa616-234c-44c1-9d6a-026c733b41fd

**Comment by MM2-0** [comment]
Duplicate of #795
