### ISSUE TITLE
cant access hidden apps

### ISSUE THREAD

**Issue by farfromrefug** [MM2-0/Kvaesitso#85]
I just installed 1.11 and can't seem to be able to access hidden apps anymore. the menu entry is gone. is there another way?
also could you add an option for the search bar to also look in hidden apps? 
it would be very helpful
thanks

**Comment by MM2-0** [comment]
It's at the end of the search results now but I'll probably change it again soon

**Comment by farfromrefug** [comment]
@MM2-0 I don't see hit. I see an eye button but it leads to the visibility settings page.
by the way it you go into the settings inside any is section. go home click on the eye button at the end of the drawer then it goes back to that setting page. have to go black to close it then opening it again show the visibility setting page again

**Comment by MM2-0** [comment]
The settings page is supposed to replace the previous hidden items panel. But I already realized that this is not a good idea so I will bring back the previous panel in a future update.

**Comment by MM2-0** [comment]
Fixed in 1.11.1

**Comment by farfromrefug** [comment]
thanks !
