### ISSUE TITLE
Kvaesitso virtually unresponsive on the Samsung Note 9

### ISSUE THREAD

**Issue by SerbianApeSociety** [MM2-0/Kvaesitso#852]
Hey mates, I've been using Kvaesitso for quite a while on my other devices, but recently when I installed it on my Samsung Note 9, it appears to be lagging absolutely horribly. I've uploaded a (extremely compressed) screen recording which shows the issue better. I've also uploaded the recent logs from the application (mind ya even the settings lag just as much as the rest of the launcher).

https://github.com/MM2-0/Kvaesitso/assets/148651892/c8a8d193-79e0-48ef-a433-c0f535f9244d

Also here's the logs just incase:
[DOC-20240520-WA0005.txt](https://github.com/MM2-0/Kvaesitso/files/15374922/DOC-20240520-WA0005.txt)

**Comment by John-Goff** [comment]
Also have a Samsung Note 9, I experienced horrible degraded performance after the latest update. Just got around to updating today and it's made my phone unusable 😞

**Comment by SerbianApeSociety** [comment]
Glad to hear it isn't an isolated issue here

**Comment by John-Goff** [comment]
Not sure when this issue was resolved but with the latest Kvaesitso I am no longer experiencing this issue!

**Comment by SerbianApeSociety** [comment]
> Not sure when this issue was resolved but with the latest Kvaesitso I am no longer experiencing this issue!

Yep, it seems to work just fine now! Completely forgot about it after all this while.
