### ISSUE TITLE
[Feature request] Allow PWA app shortcuts to be added to Tags

### ISSUE THREAD

**Issue by borisb13** [MM2-0/Kvaesitso#856]
Currently, if you use the "Add to Home Screen" or "Install" options on a website, it puts that shortcut into the Favorites bar. However, there is no way to assign it to a Tag. Tags only show the "real" app shortcuts.

It would be great if those PWA were treated just like any other app shortcut, and had the ability to be added to Tags

**Comment by exstntlmsnthrp** [comment]
This option does exist. I have several PWAs and have them all tagged and removed from favourites. 

Similar to a regular app, long press the PWA, select the ellipsis (the dots), and select customize. You should then be able to add tags.

**Comment by borisb13** [comment]
That's great, and thanks for letting me know
