### ISSUE TITLE
[Bug] Search box stays focused after dismissing the keyboard

### ISSUE THREAD

**Issue by quadsteel** [MM2-0/Kvaesitso#859]
### Problem:
The search box stays focused after dismissing the keyboard, indicated by the flashing cursor. The problem it causes is that if you then go to say, rearrange your favorites, the moment you hold on an icon to drag it, the keyboard shows up; it both dismissed the held item so you have to drag it again and it gets in the way of doing your work. You can dismiss the keyboard again, but once you hold another icon there it goes again.

<details>
<summary>Demonstration</summary>

1. First a normal interaction moving around favorites.
2. Then after doing a random search, I dismiss the keyboard but the cursor is still flashing indicating focus.
3. I tap on empty space in an attempt to take it away but it doesn't work.
4. I go back to edit my favorites.
5. The moment I hold onto an app to drag it around, the keyboard shows up

https://github.com/MM2-0/Kvaesitso/assets/74920104/927a18c4-9c8f-4df9-b023-e0050e13d37d

</details>

### Suggestion:
Take away focus from the search box after the keyboard is dismissed. It doesn't help anyway because if you intended to search again you would still have to tap on the box to get the keyboard to reappear.
Alternatively, make it so it takes away focus when you tap on empty space (as is with most software).

**Comment by MM2-0** [comment]
I think this is fixed by 64ce0747
