### ISSUE TITLE
[Feature Request] Ability to scroll in a widget

### ISSUE THREAD

**Issue by laxmanpradhan** [MM2-0/Kvaesitso#862]
Many widgets from apps like news readers, calendars, stock lists etc occupy a certain area on the home screen of the launcher but also have the ability to scroll within ti widget to see more info. For example the google news widget may occupy say 400x400 px on the screen and show 3 news articles, but you can scroll up and see additional articles. The widget essentially acts like a window that has a fixed size but you can interact with the widget itself. This is the default behaviour of most widgets. 

In Kvaesitso there is no ability to scroll on any of the app widgets. Being able to do so would greatly increase the usability of the widgets.

**Comment by KrisadaFantasy** [comment]
You can use two fingers to scroll on widgets.

**Comment by KrisadaFantasy** [comment]
I have another trick. Try having one finger to keep widget in place and use another finger to scroll it.
