### ISSUE TITLE
🐛 BUG: cannot call out input method switch panel in searchbar

### ISSUE THREAD

**Issue by yuxiangwende** [MM2-0/Kvaesitso#870]
System: Android 12(LineageOS 19)

I use Gboard and Fcitx5 as my keyboard apps.

when I click the search bar in the bottom of the launcher and the type indicator is in the search bar, I cannot call out the keyboard switch panel, it shows and soon disappears.

Sorry for bad English.

**Comment by MM2-0** [comment]
Duplicate of #841
