### ISSUE TITLE
[Bug] Google app doesn't show up in Recents when searched using intent

### ISSUE THREAD

**Issue by imranmollajoy** [MM2-0/Kvaesitso#878]
Hi,
When I search using Web search, or a custom intent (android.intent.action.WEB_SEARCH with query as extra key), the google app doesn't show up on the recents screen. However, it does show up when I use the intent from other apps, such as Shortcut Maker. So I think the issue might be in the Kvaesitso app. Thank you.

https://github.com/MM2-0/Kvaesitso/assets/60538555/3494e04a-4e51-442e-9d58-e5ab53a2f21d

https://github.com/MM2-0/Kvaesitso/assets/60538555/583a02c4-5f44-48f8-ac34-a535023f6c30

**Comment by MM2-0** [comment]
Fixed in 252eea17
