### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by bottlerocketjonny** [MM2-0/Kvaesitso#885]
I've been running Kvaesito 1.30.4 happily for the past few weeks, however yesterday the launcher started to lag and this morning it completely crashed throwing an OOM error. []()![2024-06-16 09:12:52_crash.txt](https://github.com/user-attachments/files/15856657/2024-06-16.09.12.52_crash.txt)

**Comment by bottlerocketjonny** [comment]
Seems like others have been experiencing this too: #823, #825

**Comment by MM2-0** [comment]
Closing this in favor of #897
