### ISSUE TITLE
Blurred wallpaper flickering

### ISSUE THREAD

**Issue by vvhiite** [MM2-0/Kvaesitso#887]
As the title suggests, the wallpaper is flickering when blurred in enabled (with the default settings). By that I mean that the wallpaper is flickering from blurred image into unblurred.
In my case to recreate the bug, you can just open the app drawer and start typing, or navigate through the widgets which will cause flickering when scrolling through them.
My device is a Pixel 8 and I am a new user. Just installed the launcher and the flickering occured right away. No weird issues when blurred is disabled.

**Comment by MM2-0** [comment]
I can't recreate this on my Pixel 8. Is this still happening on version 1.31?

**Comment by vvhiite** [comment]
> I can't recreate this on my Pixel 8. Is this still happening on version 1.31?

just updated to 1.31.2. seems to be fixed as i cant recreate it either, thank you
