### ISSUE TITLE
[Feature Request] Setting to always keep the list of tags expanded

### ISSUE THREAD

**Issue by AllesMeins** [MM2-0/Kvaesitso#892]
I relay heavily on tags to organize my most used apps ( in fact I use them almost like folders). So I would love to have an option that keeps the list of tags in the drawer always expanded. Currently they keep collapsing to one line after some time and I've to scroll through all the tags to expand it again. So I would appreciate a setting that turns this off and just keeps the tag-list expanded all the time so I can reach the tag I'm looking for faster. 

**_always expand this list of tags:_**

![Screenshot_20240624-103932_1](https://github.com/MM2-0/Kvaesitso/assets/2261844/eb11f846-3299-47a8-87e6-6b3346d82e15)

Would this be possible? Thanks for all the work you've already put in this great launcher!

**Comment by TableCoffee** [comment]
Seconded here for what it's worth. While I use search a lot and love it I tag my apps and always end up forgetting names of apps I'm looking for, so I use the favourites widget a ton and having the tags auto expanded is the one little thing I'd love to have.

**Comment by MM2-0** [comment]
It's supposed to remember its last state, does it not work?

**Comment by AllesMeins** [comment]
Not for me at least. It does remember it for some time but every now and then it collapses back. I wasn't able to find a regularity but it usually doesn't stay expanded longer than a few hours

**Comment by TableCoffee** [comment]
Same on my end, not consistently. If I expand it will stay expanded for the next few times I swipe the widgets up, but haven't noticed when/what causes it to revert.

**Comment by MM2-0** [comment]
Ok, let me have a look. You are all talking about the widget, right? Not the favorites section in search.

**Comment by AllesMeins** [comment]
Yes, the one that comes up when you pull from the bottom upwards on the home screen. 
But the favorites section in the search seems to behave the same. Randomly staying expanded and than collapsing again after some time (but not necessarily at the same time as the widget).
