### ISSUE TITLE
I like the vertical scrolling homescreen but there is only one flaw if I didn't miss anything

### ISSUE THREAD

**Issue by sahalkabeer** [MM2-0/Kvaesitso#895]
Although the vertically scrolling homepage is a unique concept I just realized my most used widgets which was the calendar timeline and Keep notes couldn't be useful as much, I just dropped both of em in and realized I couldn't scroll down the widget instead it just scrolls down the home screen. Probably this is one of the flaws of a vertically scrolling home screen.

**Comment by KrisadaFantasy** [comment]
You can use two fingers to scroll the widget.

**Comment by sahalkabeer** [comment]
Oh wow that's great, let me give that a try. Thank you.
