### ISSUE TITLE
Contacts cards do not support commas

### ISSUE THREAD

**Issue by glemco** [MM2-0/Kvaesitso#899]
In phone numbers, commas can be used to insert pauses, that's useful while calling some call centres, if we know they'd ask us to press 1, we can append a `,1` to the phone number and we may get what we want quicker (doesn't always work).

Kvaesitso doesn't seem to support this and, if a contact contains a comma, that character is simply skipped and tapping on the contact would dial the wrong number, e.g.
1. I want to call 12345678 and press 1 after dialling
2. I save it among my contacts as 12345678,1
3. I search for that contact in Kvaesitso
4. I see 123456781 as number (which is a wrong number)

It probably boils down to just accept one more character in a regex to identify phone numbers somewhere.

**Comment by MM2-0** [comment]
The more you know. Thanks, will change it

**Comment by glemco** [comment]
Thanks for the swift fix! Exactly as I imagined it's a simple regex, just in case I would add also `;` . I have never used it but it seems to be some kind of wait for prompt. Maybe also spaces? They sometimes look nicer and I don't think they interact with the dialling.
Also, since several call centres use `*` and `#`, I would add also those. In general maybe let's perhaps add all those characters the input method allows you to insert in the phone number's field (there's also `.` I have no idea what is for).

Side note, shouldn't the comma (or any new character) be _inside_ the range?
```diff
-- val phone = it.replace(Regex("[^+0-9],"), "")
++ val phone = it.replace(Regex("[^+0-9,]"), "")
```

**Comment by MM2-0** [comment]
You are right, I don't know how this is working lol. I will just remove the regex altogether, don't even remember why it was there in the first place.

**Comment by glemco** [comment]
Yeah actually, if that comes from the contacts it should be validated already!
