### ISSUE TITLE
Downloading icons showing up on app drawer

### ISSUE THREAD

**Issue by doonoo** [MM2-0/Kvaesitso#90]
![Screenshot_20220601-182318](https://user-images.githubusercontent.com/18385494/171511846-ca4e7596-1d2e-4ce9-9d1e-ef7aff2219fa.png)
![Screenshot_20220601-182310](https://user-images.githubusercontent.com/18385494/171511853-3bb2fbbd-1ffb-419e-ac61-72e8fe0196eb.png)

I can't explain how to produce this bug, but the only thing I've done is install the app recently. I like the launcher, fits Android 12 really well. Just can't explain this bug.

**Comment by MM2-0** [comment]
It's Google Play installing system updates. It usually goes away after a device reboot but I should probably do something about it.

**Comment by doonoo** [comment]
Restart fixed it, thanks.

**Comment by MM2-0** [comment]
Fixed in a064e80
