### ISSUE TITLE
Visual bug in 1.31.0 - background missing in search bar and results

### ISSUE THREAD

**Issue by Zarkorix** [MM2-0/Kvaesitso#902]
On the main home page, the search bar is now missing it's usual dark-grey background:

![Screenshot_20240630-220809](https://github.com/MM2-0/Kvaesitso/assets/170099158/51a0e08f-96eb-4fea-8ca8-c1957d33bbc5)

However it reappears when any scrolling is initiated:

![Screenshot_20240630-220815](https://github.com/MM2-0/Kvaesitso/assets/170099158/78e81a68-8ce2-47b6-b11b-3ad31158a29a)

This behaviour is also seen in the search results and pull down app drawer.

**Comment by MM2-0** [comment]
Intentional. The search bar no longer has a shadow, hence it has lower elevation, hence it has a darker (lighter in light mode) color.
