### ISSUE TITLE
Option to change order of favorites.

### ISSUE THREAD

**Issue by CaidenBlock** [MM2-0/Kvaesitso#905]
The new order in 1.31 puts my "most favorite" apps at the top, where they are in a spot that is more annoying to reach by thumb, and puts auto-sorted apps and frequently used apps in the most reachable bottom rows.

(New behavior)

![Screenshot_20240630-190735](https://github.com/MM2-0/Kvaesitso/assets/34176510/06c5e3a0-c22e-42fe-bd51-1243a034d283)

I looked through the settings but can't find a way to get the old behavior back without pinning extra apps to my favorites and reversing the order.

(Old behavior, for reference)

![Screenshot_20240501-014527](https://github.com/MM2-0/Kvaesitso/assets/34176510/fd5ad391-3b8c-475c-84d0-7de495966837)

**Comment by CaidenBlock** [comment]
I see now that tegs has also been moved to the bottom, which I think is a good thing, but I would still like my favorites to sort bottom-up like the drawer and search results do.

**Comment by exstntlmsnthrp** [comment]
I agree, I like the tags at the bottom. 

@CaidenBlock my tagged apps appear to be sorting from bottom up on the newest version.

**Comment by CaidenBlock** [comment]
Hmm, maybe a reset will fix.

Not the first time I've had weird behavior after updates.

**Comment by exstntlmsnthrp** [comment]
Have you tried cleaning up the database or clearing the app cache?

**Comment by CaidenBlock** [comment]
> Have you tried cleaning up the database or clearing the app cache?

Yep, tried troubleshooting short of a full data clear before submitting a bug report.

A full data wipe and reinstall did not change the behavior, regardless of whether I restored a backup or not.

**Comment by BoltCitizen** [comment]
I still have the old behavior. Just installed the latest version on GOS
