### ISSUE TITLE
Bug in 1.31.0+ App activity shortcuts missing

### ISSUE THREAD

**Issue by Doc-4** [MM2-0/Kvaesitso#906]
Pressing and holding on an app in previous versions let you see all available shortcuts. For example, if I were to press and hold on a chromium based browser app (in this case kiwi browser or vanadium), I would see shortcuts for both "new tab" and "incognito tab." After this update, I only see new tab, although I can search for and find the function via the search bar and still find it.

**Comment by exstntlmsnthrp** [comment]
After seeing your comment, I now notice that the available options with a long press for several apps have changed. One example is that on Firefox, I now see a 'Passwords' shortcut. Previously this was not an option, at least not visible to me. The other odd thing is that I have the built-in Firefox password manager set to disabled. 

I also notice a change in various options on FairEmail as well.
