### ISSUE TITLE
[Notes widget] Prevent list from wrapping text at 10+ items

### ISSUE THREAD

**Issue by Crazy-Unicooorn** [MM2-0/Kvaesitso#908]
It seems that the space allowed is not enough for double digit number?

In any case, here is what this code will produce:

```MD
1. un
1. deux
1. trois
1. quatre
1. cinq
1. six
1. sept
1. huit
1. neuf
1. dix
1. onze
1. douze
```

![Screenshot_20240701_153545_Kvaesitso.jpg](https://github.com/MM2-0/Kvaesitso/assets/30509883/90dd9ce9-637a-4393-addc-894e8d72fdaa)

**Comment by MM2-0** [comment]
> It seems that the space allowed is not enough for double digit number?

Huh, works fine on my end. Anyway, I increased the space.
