### ISSUE TITLE
[Feature request?] Blur setting blocked

### ISSUE THREAD

**Issue by totchi-lagawi** [MM2-0/Kvaesitso#910]
The setting to blur the background (Home screen/Blur background) is currently blocked, saying that "This feature is not available on your device". Right. But why? There isn't anything on the documentation, hence I ask here.

**Comment by MM2-0** [comment]
Wallpaper blur is available if:
- the device runs Android 12 or higher
- battery saver is not enabled

Furthermore, the device has to have support for cross [window blur](https://source.android.com/docs/core/display/window-blurs?hl=en). This is a flag that has to be enabled by the device manufacturer (or ROM builder in the case of custom ROMs). The minimum requirement is that the GPU is powerful enough to handle the extra load and that the render engine implementation supports it.

**Comment by totchi-lagawi** [comment]
After a check it appears that my devices doesn't support blur. Thanks for your answer.

**Comment by Gl17chV** [comment]
@MM2-0 As a suggestion, it would be nice to add an option where the Wallpaper is generated with blur and stored in cache to appear only in the app drawer as other launchers do.
