### ISSUE TITLE
Clock "Show alarms" setting regression

### ISSUE THREAD

**Issue by Doc-4** [MM2-0/Kvaesitso#914]
This setting is not currently working correctly. I don't know the upper limit, but according to the description, it's only supposed to show the next alarm within 15 minutes, but with it enabled on the latest version it's showing almost all the time with values easily exceeding that, like below:
![Screenshot_20240701-210737](https://github.com/MM2-0/Kvaesitso/assets/60247583/4adedfcb-5c27-4521-ac8e-55b54cc829b7)

**Comment by Sir-Photch** [comment]
This was changed in #882.
But I actually agree that 12 hours is a bit too much? I have an alarm set every morning anyway.

**Comment by Doc-4** [comment]
I see, I also have an alarm every morning. Making it user configurable and/or have a default in the middle somewhere would probably be preferable.
