### ISSUE TITLE
Proposal for Work Profile applications drawer switching

### ISSUE THREAD

**Issue by iRomanyshyn** [MM2-0/Kvaesitso#918]
Thanks for the best launcher I've seen. My proposal is too add "swipe" switching between the drawers of Personal and Work apps, it may dramatically improve the UX.
![Screenshot_20240703-171135](https://github.com/MM2-0/Kvaesitso/assets/11888301/638c6ddc-8535-4f61-85a6-22a2c9ca71b8)

**Comment by MM2-0** [comment]
Duplicate of #864
