### ISSUE TITLE
not really an issue, instead appreciation

### ISSUE THREAD

**Issue by Thomashighbaugh** [MM2-0/Kvaesitso#92]
I can't tell you how long I have tirelessly sought a launcher for my phone that enabled me to not have a clutter home, easy access to apps, supported widgets and custom icon packs. I'm a man of simple taste, never needed all the bells and whistles nor paid themes often offered by the play store launchers, but often paid for them just so I could have my minimal desired features and still was always let down. 

Then on a whim the other day, downloaded your launcher from F-Droid and wow it's like I'm not a rambling lunatic and someone else wanted the same streamlined, no bs but not hideous Font-face on  primary colors with no way to check my email at a glance either. Perfectly, exactly what I wanted with exactly the amount of customization needed and that's it. Like it so much I figured out how to type the æ character to find the project on F-Droid to tell you how totally tubular it is, rock on! 

Solid project, great feature set and open sources! Paragons of development virtue everyone who worked on this project, thanks for restoring a little of my faith in humanity.

**Comment by MM2-0** [comment]
Thank you ❤️
