### ISSUE TITLE
Widget edge showing at bottom of screen

### ISSUE THREAD

**Issue by exstntlmsnthrp** [MM2-0/Kvaesitso#93]
First, I just want to say I completely agree with the commenter on [Issue #92](https://github.com/MM2-0/Kvaesitso/issues/92). I've probably tried using the 25 most popular home apps in the play store and most were too complex, while others had virtually no usable (to me) features. This hits all the perfect points for me and I have used it every day since finding it! It makes using my phone more enjoyable.

___

I do have one minor issue.

**Expected behaviour:**

When the search bar is hidden at the bottom of the screen, all widgets at the bottom will be hidden and not visible below the clock.

**Actual behaviour:**

 As seen in the screenshot, I keep the search bar hidden until I touch the screen. However, the top of the weather widget (that's the widget I have placed on top) shows below the clock despite being fully pulled down.

Device: Google Pixel 4XL
OS: LineageOS 19.1 (19-220505.002) 
App version: 1.11.1-20220529
App source: Github

If you need additional information, please ask.

**Comment by exstntlmsnthrp** [comment]
Here is the referenced screenshot
![Screenshot_Kvæsitso_1](https://user-images.githubusercontent.com/57594290/173242948-a5bf8714-b8a2-417a-9c89-b381818c850d.png)
.

**Comment by MM2-0** [comment]
It might have something to do with that you've hidden the status bar? Thanks for the report, I'll have a look

**Comment by exstntlmsnthrp** [comment]
Thanks for the really quick response. You are correct! It is caused because of the difference in pixels that account for the status bar being hidden. With status bar visible, it looks as I would expect. With status bar hidden, it appears as I report above. Is this something that could be fixed in a future update?

**Comment by MM2-0** [comment]
I think I might have fixed it already by accident. I can't reproduce it on my debug builds (I can however reproduce it on the latest release version)

**Comment by exstntlmsnthrp** [comment]
Haha. That's great. Thanks. Then I will just wait for the next release version. It wasn't going to prevent me from using the app, but did seem like a minor bug.
