### ISSUE TITLE
[Bug] Material You Icon color bug

### ISSUE THREAD

**Issue by suitably** [MM2-0/Kvaesitso#934]
Hi,

I'm not sure if this is the right place, but after the recent update, I'm facing an issue when I try to change an icon. I use Lawnicons, where two colors are provided in select mode, but regardless of what I choose, it's always the 2nd color. The issue persists even when I change the color scheme.

![1720475709571](https://github.com/MM2-0/Kvaesitso/assets/151583332/b4965b3b-cd57-42c0-9d7f-1c4b5204df95)
![1720475651943](https://github.com/MM2-0/Kvaesitso/assets/151583332/ebee6925-44e9-4fe5-aea6-21dec801b944)

**Comment by MM2-0** [comment]
fixed in cf398f66
