### ISSUE TITLE
Text in highlighted item in black and white theme has the wrong color

### ISSUE THREAD

**Issue by Monoxide8969** [MM2-0/Kvaesitso#938]
![Screenshot_20240710_212228_Kvaesitso_1](https://github.com/MM2-0/Kvaesitso/assets/108904135/bce66d40-1b26-4e9c-b616-03dec15d99f3)

As shown in the image.

If the box is white, the text should be black instead of white when highlighted.

I think it's an issue of the default theme and not related to my colors/system/wallpaper

**Comment by MM2-0** [comment]
Fixed in 1.32.0

**Comment by Monoxide8969** [comment]
Thank you!
