### ISSUE TITLE
[Bug] calendar widget skips Sunday

### ISSUE THREAD

**Issue by user13v31** [MM2-0/Kvaesitso#941]
Hi there

If I use the arrows to change the calender view to tomorrow etc I am not able to look up Sundays, and the drop down menu also doesn't show them. I guess this is not intentional?

Kind regards

![Screenshot_20240710-230514](https://github.com/MM2-0/Kvaesitso/assets/61806592/9c86f3d5-70b9-4fed-981f-24d5d733b876)

**Comment by MM2-0** [comment]
It only lists dates that have events scheduled.

**Comment by user13v31** [comment]
Sorry for the late reply
Yeah ok, I fell for a stupid coincidence. Thanks for clearing it up.
gz dijak
----------------------------------------

12.07.2024 20:05:49 MM2-0 ***@***.***>:
