### ISSUE TITLE
[Bug] Hidden apps are back again in recent item list

### ISSUE THREAD

**Issue by kud** [MM2-0/Kvaesitso#942]
Hey hey!

Hope you're doing well.

Thanks for the last update.

Sadly, there is a bug which came back since the new version.

Hidden applications have resurfaced in the latest version 1.31.2 of the recent item list. I think, they are meant to remain concealed.

Thanks!

**Comment by MM2-0** [comment]
Apps whose visibility is set to "search only" can appear in favorites. Apps whose visibility os set to "hidden" can not.

**Comment by kud** [comment]
Ha, oh, oh! I've just discovered you added in customise the "Show in". Makes sense now. Thanks!

**Comment by SuNNjek** [comment]
> Apps whose visibility is set to "search only" can appear in favorites. Apps whose visibility os set to "hidden" can not.

So I can hide an app in the list but it might still appear on my home screen if I use it frequently enough? That seems wrong to me. If I set it to "search only", then that's where I would want it to show up, only in the search. Would it be possible to at least get a toggle for this?

**Comment by kud** [comment]
@MM2-0 introduced a granularity of hiding. The only sad point is the retro compatibility, where there was no migration from the behavior before and after. I had to select all the apps I wanted to hide and change their visibility. It could have been great, while introducing this new feature, to also migrate all the settings to have the same behavior as before.
