### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by labrusca** [MM2-0/Kvaesitso#96]
https://github.com/MM2-0/Kvaesitso/blob/adab3f686133a63ad36dc53a716af3a93cf6c635/i18n/src/main/res/values/strings.xml#L231

Did you mean ‘save'?
It's a spelling mistake,right?

**Comment by labrusca** [comment]
Sorry,my bad. it's German...

**Comment by MM2-0** [comment]
It was a typo but it should be fixed. How did you find this?

**Comment by labrusca** [comment]
Sorry, I should have checked the newest commits.
