### ISSUE TITLE
Regression: Reassigning App icons bugged

### ISSUE THREAD

**Issue by Doc-4** [MM2-0/Kvaesitso#964]
I cleared app storage before testing this to ensure this was a bug with the new version and not a bug caused by updating. This bug was not present in the previous version. You can see it below:

https://github.com/user-attachments/assets/45e4f57d-f2a3-49a5-be33-f8ed87c85914

It seems to primarily happen with outline icons, as if theming is turned on and forced on, even though it isn't.

**Comment by Teddy-Kun** [comment]
I can confirm this bug on Android 14. The themed icons setting is disabled and user defined icons stand out a lot.
![Screenshot_20240721-100947](https://github.com/user-attachments/assets/70a85700-11d0-4828-a6e4-e60de7ee7f31)

**Comment by exstntlmsnthrp** [comment]
I can also confirm this on Android 14, Pixel 7 Pro and app from GitHub.

**Comment by JamoDevNich** [comment]
@MM2-0 Thanks for fixing this so quickly ❤️
