### ISSUE TITLE
Regression: Show hidden apps filter no longer works

### ISSUE THREAD

**Issue by Doc-4** [MM2-0/Kvaesitso#965]
If an app is set to be shown never, it can still be seen from the reveal hidden apps button, but the show hidden apps search filter doesn't show or hide anything. This behavior was different last version.
Shown below:

https://github.com/user-attachments/assets/13f7fa6b-e018-46ab-abe2-24019683d0de

**Comment by exstntlmsnthrp** [comment]
I can confirm this. The hidden search results button no longer appears to do anything.

**Comment by exstntlmsnthrp** [comment]
@Doc-4 Off topic, but what app icons are you using?

**Comment by Doc-4** [comment]
@exstntlmsnthrp uk.co.randomvector.outline in play store.

**Comment by Doc-4** [comment]
@MM2-0 Heads up, this isn't fixed in the latest release or nightly, what's in the video is still reproducible. What was fixed is that the filter now works when there is no search query, but still doesn't show an app even if it matches the query.

**Comment by exstntlmsnthrp** [comment]
This now appears to be fixed in version 1.32.2. I can no longer reproduce the issue.
