### ISSUE TITLE
🌱 `Feature Request` — Automatic Wallpaper Changer

### ISSUE THREAD

**Issue by 8227846265** [MM2-0/Kvaesitso#970]
Hello, I would like to suggest adding a function to have Kvaesitso itself display different home screen wallpapers through the Unsplash API (Similar to what this app can do: https://play.google.com/store/apps/details?id=com.b_lam.resplash)

Suggested Key Features:
- Automatic Wallpaper Changer
- Set Wallpaper Blur Settings

Similar apps that have wallpaper changer features baked-in:
- Smart Launcher: https://play.google.com/store/apps/details?id=ginlemon.flowerfree
- Microsoft Launcher: https://play.google.com/store/apps/details?id=com.microsoft.launcher

**Comment by MM2-0** [comment]
You can use Resplash, or Wall You, or Walpy, or any other app that supports Unsplash for that.
