### ISSUE TITLE
APPs does not sort correctly when the search bar at the bottom

### ISSUE THREAD

**Issue by labrusca** [MM2-0/Kvaesitso#98]
Some APPs(English apps and Chinese apps) does not sort correctly
version 1.12.0
by the way:
`
Pinyin character:
 '拨号' = 'bohao'
'半导小芯' =‘bandaoxiaoxin’
`

![Screenshot_2022-06-14-21-05-07-02_94226bc2e387a4f039bd6db013273604](https://user-images.githubusercontent.com/10952515/173584511-ef5ad441-5729-4eaa-a984-03960024324d.jpg)

**Comment by MM2-0** [comment]
Looks fine to me?
Apps in this layout are sorted from bottom left to top right, like this:
```
[ 11 ] [ 12 ] [ 13 ] [ 14 ] [ 15 ]
[  6 ] [  7 ] [  8 ] [  9 ] [ 10 ]
[  1 ] [  2 ] [  3 ] [  4 ] [  5 ]
```

So I don't see anything wrong with this or am I missing something?

**Comment by labrusca** [comment]
> Looks fine to me? Apps in this layout are sorted from bottom left to top right, like this:
> 
> ```
> [ 11 ] [ 12 ] [ 13 ] [ 14 ] [ 15 ]
> [  6 ] [  7 ] [  8 ] [  9 ] [ 10 ]
> [  1 ] [  2 ] [  3 ] [  4 ] [  5 ]
> ```
> 
> So I don't see anything wrong with this or am I missing something?

oh, If that's the case, it's Looks fine to me too

but it's better for me like this:
```
[ 15 ] [ 14 ] [ 13 ] [ 12 ] [ 11 ]
[ 10 ] [  9 ] [  8 ] [  7 ] [  6 ]
[  5 ] [  4 ] [  3 ] [  2 ] [  1 ]
```

**Comment by MM2-0** [comment]
Closing this in favor of #121
