### ISSUE TITLE
latest update makes groups show up next to the actual app

### ISSUE THREAD

**Issue by owosoup** [MM2-0/Kvaesitso#982]
I have Organic Maps and Gmaps WV installed, put in the "map" app group. When searching the term "map" I see both apps twice, I suppose because both the group and and individual apps correspond to the search term. Before 132.0, it worked fine without duplicates.
![Screenshot_2024-07-24-13-22-59-12_94226bc2e387a4f039bd6db013273604](https://github.com/user-attachments/assets/4f93cfae-254c-4975-a63e-1a408c889d3a)

**Comment by MM2-0** [comment]
This has already been fixed in 1.32.1
