### ISSUE TITLE
[Bug] Wikipedia search not working 

### ISSUE THREAD

**Issue by urmomseksy** [MM2-0/Kvaesitso#997]
Using version 1.32.2

When I enable wikipedia in the search settings, I don't get any instant results when trying to search for a topic that would be on Wikipedia.

Does the default URL of https://en.wikipedia.org need to be tweaked to make the search work?

**Comment by Sir-Photch** [comment]
Do you tap on "web results" in the filterbar?

**Comment by urmomseksy** [comment]
> Do you tap on "web results" in the filterbar? (Or "online results", not sure how it's called with english locale)

Thanks for your input. That actually works, but I don't know if that's the intended behavior.

Example:
- type a country name like "Germany" into the search
- receive no instant search results 
- Press "Online Results" and then the wiki for Germany appears.

Alternatively
- type a country name like "Germany" into the search
- receive no instant search results
- Press "Wikipedia" (which is six buttons to the right of "Online Results)
- Receive no results 

I have no idea why the online results button will give a different output from the Wikipedia button 

I also thought that when you enabled Wikipedia search that it would be similar to the unit converter and give you instant results for whatever you type into the search bar without having to press one of those buttons.

**Comment by MM2-0** [comment]
> Thanks for your input. That actually works, but I don't know if that's the intended behavior.

Yes it is. Wikipedia is an online search, so it isn't queried by default in order to protect your privacy. You can change the default filter in settings > search > default filter.

> I have no idea why the online results button will give a different output than the Wikipedia button.

Good point. The label is a bit misleading. It should be something more generic like "definitions" or "articles", this would make it more clear.

**Comment by urmomseksy** [comment]
Thanks. I'll close this issue now.

**Comment by m1212e** [comment]
Hey, I also had this "problem" and was able to solve it by following the steps you provided. I'd recommend to place this somewhere more prominently since I searched through the settings multiple times and didn't get the memo. A bit confusing as a user. Just my two cents, works great now!
